### ISSUE TITLE
Trimming recording

### ISSUE THREAD

**Issue by farazmoradi** [SpikeInterface/spikeinterface#1053]
Hi,

I have loaded a recording with BinaryRecordingExtractor. I want to cut the first hour of data as it was noisy and then perform the spike sorting. How do you do that?

**Comment by alejoe91** [comment]
You can do the following:

```
recording_trimmed = recording.frame_slice(start_frame=int(3600*recording.sampling_frequency))
```

**Comment by farazmoradi** [comment]
Thanks a lot!

**Comment by alejoe91** [comment]
No worries!
