### ISSUE TITLE
specifying a unit's channel when extracting waveforms or computing quality metrics

### ISSUE THREAD

**Issue by Yizhar-Lab** [SpikeInterface/spikeinterface#1068]
### Discussed in https://github.com/SpikeInterface/spikeinterface/discussions/1066

<div type='discussions-op-text'>

<sup>Originally posted by **Yizhar-Lab** November  9, 2022</sup>

I've a binary recording from 16-electrode bundles, where each electrode typically records different spikes/units, and the sorting is done manually for each channel separately. I created a NumpySorting object and ran extract_waveforms() according to the tutorials. I understood that you [choose the channel with the "most negative" template amplitude](https://github.com/SpikeInterface/spikeinterface/issues/421#issuecomment-997932249). I'm wondering if I can overwrite this by explicitly specifying the channel of each sorted unit when extracting waveforms?

Thanks,
Asaf</div>

**Comment by alejoe91** [comment]
Hi @Yizhar-Lab 

The best approach here is to use the grouping feature. First you set each channel to belong to a different group:
```
recording.set_channel_groups(range(16))
recordings_dict = recording.split_by("group")
```
Now `recordings_dict` is a dictionary of 16 elements, with the group as key and a mono-channel recording as values.
You can similarly load your `NumpySorting` objects into a `sortings_dict` dictionary with the same structure and then extract waveforms for each channel separately:
```
waveforms_dict = {}
for group in range(16):
    recording = recordings_dict[group]
    sorting = sortings_dict[group]
    we = si.extract_waveforms(recording, sorting, folder=f"group{group}")
    waveforms_dict[group] = we
```

I think this should work in your situation, but let me know if I misunderstood!
