### ISSUE TITLE
questions on using Mountainsort4 

### ISSUE THREAD

**Issue by ChenK19** [SpikeInterface/spikeinterface#107]
Hi everyone, 
We used mountainsort4 to sort our recorded data previously in our lab, now we are trying to switch to Spikeinterface.

 However, we meet a problem with the firing.mda file generated by ss.run_mountainsort4.

When we use the MS4  before, the first row of firing.mda supposed to be the channels detecting the corresponding units, where they are all zero now. 

Does that mean all the spikes are detected on the channel zero?  But in the phy visualization interface, we can see the corresponding relationship between channels and units not belonging to channel zero.

**Comment by alejoe91** [comment]
Hi,

The first column of the mda file.is not used anymore, because it was MS4 specific. You can use Phy to get the max channel for each unit.
