### ISSUE TITLE
Multiprocessing fails with too many jobs when recording spans several files

### ISSUE THREAD

**Issue by TomBugnon** [SpikeInterface/spikeinterface#1076]
Hi Samuel, Alessio

Pfiou this one has been quite a headache to debug...

Here's what I'm doing:
1- For several files: create a single segment SpikeGLXRecordingExtractor
2- Select frames (shorten) single segment recordings
3- Concatenate segments from each files
4- Save to bin with `write_binary_recording`
This is with version 0.96.2.dev0,  commit df6e572f on master from 2days ago

`write_binary_recording` (and, I gather, all of multiprocessing) works with many jobs on a single file (tested with up to 150 jobs on a 2h recording):

> N files:  1
> N jobs: 50
> Add segment: time_range=(0, 200) FrameSliceRecording: 384 channels - 1 segments - 30.0kHz - 200.000s
> Recording: ConcatenateSegmentRecording: 384 channels - 1 segments - 30.0kHz - 200.000s
> write_binary_recording with n_jobs = 50 and chunk_size = 29999
> Success

And with "few" jobs when the recording spans several files...: 

> 
> N files:  24
> N jobs: 1
> Recording: ConcatenateSegmentRecording: 384 channels - 1 segments - 30.0kHz - 240.000s
> write_binary_recording with n_jobs = 1 and chunk_size = 29999
> Success
> 
> 
> 
> N files:  24
> N jobs: 20
> Recording: ConcatenateSegmentRecording: 384 channels - 1 segments - 30.0kHz - 240.000s
> write_binary_recording with n_jobs = 20 and chunk_size = 29999
> Success

But fails with "too many" jobs and several files:

> N files:  24
> N jobs: 50
> Recording: ConcatenateSegmentRecording: 384 channels - 1 segments - 30.0kHz - 240.000s
> write_binary_recording with n_jobs = 50 and chunk_size = 29999
> Exception in initializer:
> Traceback (most recent call last):
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
>     initializer(*initargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/job_tools.py", line 328, in worker_initializer
>     _worker_ctx = init_func(*init_args)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/core_tools.py", line 184, in _init_binary_worker
>     worker_ctx['recording'] = load_extractor(recording)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 904, in load_extractor
>     return BaseExtractor.from_dict(file_or_folder_or_dict, base_folder=base_folder)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 372, in from_dict
>     extractor = _load_extractor_from_dict(d)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in _load_extractor_from_dict
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in <listcomp>
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 849, in _load_extractor_from_dict
>     extractor = cls(**kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 51, in __init__
>     NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id,
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 43, in __init__
>     _NeoBaseExtractor.__init__(self, block_index, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 25, in __init__
>     self.neo_reader = get_reader(self.NeoRawIOClass, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 15, in get_reader
>     neo_reader.parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/baserawio.py", line 179, in parse_header
>     self._parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 97, in _parse_header
>     data = np.memmap(info['bin_file'], dtype='int16', mode='r', offset=0, order='C')
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/numpy/core/memmap.py", line 228, in __new__
>     f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
> BlockingIOError: [Errno 11] Resource temporarily unavailable: '/Volumes/NeuropixelNAS2-data1/CNPIX15-Claude/8-30-2022/SpikeGLX/8-30-2022_g0/8-30-2022_g0_imec1/8-30-2022_g0_t2.imec1.lf.bin'
> Exception in initializer:
> Traceback (most recent call last):
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
>     initializer(*initargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/job_tools.py", line 328, in worker_initializer
>     _worker_ctx = init_func(*init_args)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/core_tools.py", line 184, in _init_binary_worker
>     worker_ctx['recording'] = load_extractor(recording)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 904, in load_extractor
>     return BaseExtractor.from_dict(file_or_folder_or_dict, base_folder=base_folder)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 372, in from_dict
>     extractor = _load_extractor_from_dict(d)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in _load_extractor_from_dict
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in <listcomp>
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 849, in _load_extractor_from_dict
>     extractor = cls(**kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 51, in __init__
>     NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id,
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 43, in __init__
>     _NeoBaseExtractor.__init__(self, block_index, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 25, in __init__
>     self.neo_reader = get_reader(self.NeoRawIOClass, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 15, in get_reader
>     neo_reader.parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/baserawio.py", line 179, in parse_header
>     self._parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 97, in _parse_header
>     data = np.memmap(info['bin_file'], dtype='int16', mode='r', offset=0, order='C')
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/numpy/core/memmap.py", line 228, in __new__
>     f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
> BlockingIOError: [Errno 11] Resource temporarily unavailable: '/Volumes/NeuropixelNAS2-data1/CNPIX15-Claude/8-30-2022/SpikeGLX/8-30-2022_g0/8-30-2022_g0_imec1/8-30-2022_g0_t8.imec1.ap.bin'
> Exception in initializer:
> Traceback (most recent call last):
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
>     initializer(*initargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/job_tools.py", line 328, in worker_initializer
>     _worker_ctx = init_func(*init_args)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/core_tools.py", line 184, in _init_binary_worker
>     worker_ctx['recording'] = load_extractor(recording)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 904, in load_extractor
>     return BaseExtractor.from_dict(file_or_folder_or_dict, base_folder=base_folder)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 372, in from_dict
>     extractor = _load_extractor_from_dict(d)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in _load_extractor_from_dict
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in <listcomp>
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 849, in _load_extractor_from_dict
>     extractor = cls(**kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 51, in __init__
>     NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id,
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 43, in __init__
>     _NeoBaseExtractor.__init__(self, block_index, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 25, in __init__
>     self.neo_reader = get_reader(self.NeoRawIOClass, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 15, in get_reader
>     neo_reader.parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/baserawio.py", line 179, in parse_header
>     self._parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 80, in _parse_header
>     self.signals_info_list = scan_files(self.dirname)
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 252, in scan_files
>     meta = read_meta_file(meta_filename)
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 345, in read_meta_file
>     with open(meta_file, mode='r') as f:
> BlockingIOError: [Errno 11] Resource temporarily unavailable: '/Volumes/NeuropixelNAS2-data1/CNPIX15-Claude/8-30-2022/SpikeGLX/8-30-2022_g0/8-30-2022_g0_imec1/8-30-2022_g0_t6.imec1.lf.meta'
> Exception in initializer:
> Traceback (most recent call last):
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
>     initializer(*initargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/job_tools.py", line 328, in worker_initializer
>     _worker_ctx = init_func(*init_args)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/core_tools.py", line 184, in _init_binary_worker
>     worker_ctx['recording'] = load_extractor(recording)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 904, in load_extractor
>     return BaseExtractor.from_dict(file_or_folder_or_dict, base_folder=base_folder)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 372, in from_dict
>     extractor = _load_extractor_from_dict(d)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in _load_extractor_from_dict
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 838, in <listcomp>
>     kwargs[k] = [_load_extractor_from_dict(e) for e in v]
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 832, in _load_extractor_from_dict
>     kwargs[k] = _load_extractor_from_dict(v)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/base.py", line 849, in _load_extractor_from_dict
>     extractor = cls(**kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/spikeglx.py", line 51, in __init__
>     NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id,
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 43, in __init__
>     _NeoBaseExtractor.__init__(self, block_index, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 25, in __init__
>     self.neo_reader = get_reader(self.NeoRawIOClass, **neo_kwargs)
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 15, in get_reader
>     neo_reader.parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/baserawio.py", line 179, in parse_header
>     self._parse_header()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/neo/rawio/spikeglxrawio.py", line 97, in _parse_header
>     data = np.memmap(info['bin_file'], dtype='int16', mode='r', offset=0, order='C')
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/site-packages/numpy/core/memmap.py", line 228, in __new__
>     f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
> BlockingIOError: [Errno 11] Resource temporarily unavailable: '/Volumes/NeuropixelNAS2-data1/CNPIX15-Claude/8-30-2022/SpikeGLX/8-30-2022_g0/8-30-2022_g0_imec1/8-30-2022_g0_t7.imec1.ap.bin'
> Traceback (most recent call last):
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/pipeline_tests/test_multiprocessing_n_jobs_error.py", line 95, in <module>
>     write_binary_recording(
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/core_tools.py", line 278, in write_binary_recording
>     executor.run()
>   File "/home/tbugnon/projects/ecephys_dev_si_pipeline/spikeinterface/spikeinterface/core/job_tools.py", line 312, in run
>     for res in results:
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/process.py", line 570, in _chain_from_iterable_of_lists
>     for element in iterable:
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
>     yield _result_or_cancel(fs.pop())
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
>     return fut.result(timeout)
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/_base.py", line 458, in result
>     return self.__get_result()
>   File "/home/tbugnon/miniconda3/envs/ecephys_dev_si_pipeline/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> 

I don't know exactly what "too many" jobs or "too many" files mean. 
It is not that njobs should be <= nfiles (I had it work with 24 files and 25jobs).
I'm having trouble replicating it but I kinda think I did and also did NOT observe this error running multiple times the same data/njobs, either with different segment duration or even with the exact same data. I'm thinking it might make sense that this error appears somewhat erratically and involves CPU/IO speed at the moment of execution if it's a matter of when exactly the different jobs are opening/closing files
Best
Tom

**Comment by samuelgarcia** [comment]
Hi Tom,
I guess you are on linux.
On linux there a max open file hard limit which is generally set on 1000 for ubuntu.
With 30 files and 50 jobs (that all open the underlying files) you rapidely reach thus limits.

You can check it an check it using the `ulimit` linux command.
Tell if it works.

**Comment by TomBugnon** [comment]
I'm afraid this is not solved by increasing the open file limit (value showed by `ulimit -n`) to 500000 (lol)

**Comment by alejoe91** [comment]
Thanks @TomBugnon 

We'll try to investigate! Maybe it could be due to a preprocessing step..could you try by removing one by one the preprocessing functions?

**Comment by samuelgarcia** [comment]
@TomBugnon : does your memory usage increase for always ?

@maxjuv laos experience some memmap problem that consums too much memory with spikeglx

**Comment by TomBugnon** [comment]
@alejoe91 This happens also with the raw (concatenatesegment)recording, so not due to preprocessing

@samuelgarcia I didn't notice anyting weird regarding memory usage.

Has anyone been able to replicate this?

**Comment by samuelgarcia** [comment]
Apparently the memory usage from @maxjuv was only on widows finally.

**Comment by alejoe91** [comment]
> @alejoe91 This happens also with the raw (concatenatesegment)recording, so not due to preprocessing
> 
> @samuelgarcia I didn't notice anyting weird regarding memory usage.
> 
> Has anyone been able to replicate this?

Thanks for looking into it @TomBugnon 
Definitely this narrows it down!

**Comment by maxjuv** [comment]
Yep, On my linux cluster everyhting is fine. As mentionned, I have to increase my "ulimit -n" when I submits my jobs, otherwise I got a 'too many files open" error 
On my local windows, when I use memmap, the RAM keeps growing upto ~98%. Although, the computer rarely swap, even if other memory-consuming softwares are launched. So windows may free some memory (used by memmap) on demand.

**Comment by h-mayorquin** [comment]
@TomBugnon 
Is this the thing that we solved in Slack? Can we close it or is this a different issue?

**Comment by alejoe91** [comment]
@TomBugnon should be fixed by #1674. @TomBugnon feel free to repone if not the case ;)
