### ISSUE TITLE
Crash during export_to_phy when compute_amplitudes=True

### ISSUE THREAD

**Issue by esutlie** [SpikeInterface/spikeinterface#1088]
When running export_to_phy with compute_amplitudes=True, the spike_amplitudes.py script throws an error when loading the sorting extractor. It appears to happen because the 'sampling_frequency' and 'multisortingcomparison' fields in the extractor dict are blank.

# Error traceback:
Exception in initializer:
Traceback (most recent call last):
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\concurrent\futures\process.py", line 230, in _process_worker initializer(*initargs)
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\site-packages\spikeinterface\core\job_tools.py", line 294, in worker_initializer
_worker_ctx = init_func(*init_args)
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\site-packages\spikeinterface\toolkit\postprocessing\spike_amplitudes.py", line 202, in _init_worker_spike_amplitudes
    sorting = load_extractor(sorting)
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\site-packages\spikeinterface\core\base.py", line 902, in load_extractor
    return BaseExtractor.from_dict(file_or_folder_or_dict, base_folder=base_folder)
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\site-packages\spikeinterface\core\base.py", line 339, in from_dict
    extractor = _load_extractor_from_dict(d)
  File "C:\Users\Elissa\Anaconda3\envs\spike_sorting\lib\site-packages\spikeinterface\core\base.py", line 850, in _load_extractor_from_dict
    extractor = cls(**kwargs)
TypeError: __init__() missing 2 required positional arguments: 'sampling_frequency' and 'multisortingcomparison'

# Error producing code
```
recording = se.read_spikeglx(recording_path, stream_id='imec0.ap')

recording_cmr = recording
recording_f = si.bandpass_filter(recording, freq_min=300, freq_max=6000)
recording_cmr = si.common_reference(recording_f, reference='local', operator='median',
                                    local_radius=(30, 200))
kwargs = {'n_jobs': n_jobs, 'total_memory': '8G'}
recording = recording_cmr.save(format='binary', `folder=recording_folder,` **kwargs)

sorter_params = {"keep_good_only": True}
ks3_sorter = ss.run_sorter(sorter_name='kilosort3', recording=recording, output_folder=kilosort3_folder,
                           verbose=False, docker_image=use_docker, **sorter_params)
sorter_params = {"keep_good_only": False}
ks2_5_sorter = ss.run_sorter(sorter_name='kilosort2_5', recording=recording,
                             output_folder=kilosort2_5_folder,
                             verbose=False, docker_image=use_docker, **sorter_params)

consensus = sc.compare_multiple_sorters(sorting_list=[ks3_sorter, ks2_5_sorter],
                                        name_list=['kilosort3', 'kilosort2_5'], verbose=False,
                                        delta_time=.2,
                                        match_score=.3,
                                        spiketrain_mode='union')
consensus = consensus.get_agreement_sorting(minimum_agreement_count=2)

waveforms = si.WaveformExtractor.create(recording, consensus, waveforms_folder)
waveforms.set_params(ms_before=3., ms_after=4., max_spikes_per_unit=500)
waveforms.run_extract_waveforms(n_jobs=n_jobs, chunk_size=30000)

sparsity_dict = dict(method="radius", radius_um=50, peak_sign='both')
job_kwargs = {'n_jobs': n_jobs, 'total_memory': '8G'}
export_to_phy(waveforms, phy_folder, compute_pc_features=True, compute_amplitudes=True, copy_binary=True,
              remove_if_exists=True, sparsity_dict=sparsity_dict, max_channels_per_template=None,
              **job_kwargs)
```

**Comment by alejoe91** [comment]
Hi @esutlie 

The "problem" is that the `consensus` sorting is in memory, and cannot be saved to a file (which is required for parallel processing.

You can fix it by adding the following line after creating it: `consensus=consensus.save(folder='consensus')`

Let me know if that fixes it! And happy Thanksgiving!
