### ISSUE TITLE
Add RecordingExtractor for NeuroExplorer

### ISSUE THREAD

**Issue by CodyCBakerPhD** [SpikeInterface/spikeinterface#1093]
Neo RawIO here: https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/neuroexplorerrawio.py

Would be great to have a `NeuroExplorerRecordingExtractor` as well

Examples files: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuroexplorer

**Comment by h-mayorquin** [comment]
See the coments here:
https://github.com/SpikeInterface/spikeinterface/issues/1773#issuecomment-1707859676

**Comment by zm711** [comment]
@CodyCBakerPhD, just want to bump @h-mayorquin's message. Heberto implemented a reader for NeuroExplorer. Is that enough for your issue or does [216](https://github.com/catalystneuro/neuroconv/issues/216) require the most recent format? I'm trying to do a little post-release clean-up.

**Comment by h-mayorquin** [comment]
I will ask the @CodyCBakerPhD for the data and open a new issue. I will close this.
