### ISSUE TITLE
Find a proper way to handle recording when not compatible with microVolts

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeinterface#1099]
Because spikeinertface is for spike sorting all the recording are supose to be compatible with microVolt.
And the get_trace(return_scaled=True) must give uV.
Something a recording has nothing to do with an extra cellular recording.
We need to handle this correctly with proper flags and/or annotations.
This would avoid patch like this #1098.

**Comment by zm711** [comment]
What's the status of this one @alejoe91 and @samuelgarcia ? Is this actionable currently? Or should we close. It is stale by 2 years...

**Comment by alejoe91** [comment]
Yeah this is prehistoric! let's close :)
