### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#11]
We should release all packages and spikeinterface soon :)

**Comment by samuelgarcia** [comment]
Agree but first the doc must auto build and all other doc/readme from other package must be cleaned.

**Comment by samuelgarcia** [comment]
Maybe we could make a fast cycle with 0.5, 0.6, 0.7 for si before te 1.0.
I think targetting 1.0.0 for end sebtember is wise.

**Comment by samuelgarcia** [comment]
Before the release, we should finish to port all sorter that live in spikeforest but not in spikesorters like waveclust or jrclust.
