### ISSUE TITLE
Unable to save waveforms and post-processed data for curated units

### ISSUE THREAD

**Issue by ABehal2020** [SpikeInterface/spikeinterface#1109]
I'm going through this spikeinteface tutorial: https://github.com/SpikeInterface/spiketutorials/blob/master/Official_Tutorial_SI_0.96_Oct22/SpikeInterface_Tutorial.ipynb

The line of code below gives me the associated stack trace below:
`we_curated = we.select_units(keep_unit_ids, new_folder="waveforms_curated")`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [106], line 1
----> 1 we_curated = we.select_units(keep_unit_ids, new_folder="waveforms_curated")

File /opt/anaconda/anaconda3/envs/si_env/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py:529, in WaveformExtractor.select_units(self, unit_ids, new_folder, use_relative_path)
    527 for ext_name in self.get_available_extension_names():
    528     ext = self.load_extension(ext_name)
--> 529     ext.select_units(unit_ids, new_waveform_extractor=we)
    531 return we

File /opt/anaconda/anaconda3/envs/si_env/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py:1124, in BaseWaveformExtractorExtension.select_units(self, unit_ids, new_waveform_extractor)
   1122 new_extension = self.__class__(new_waveform_extractor)
   1123 new_extension.set_params(**self._params)
-> 1124 new_extension_data = self._select_extension_data(unit_ids=unit_ids)
   1125 new_extension._extension_data = new_extension_data
   1126 new_extension._save()

File /opt/anaconda/anaconda3/envs/si_env/lib/python3.9/site-packages/spikeinterface/postprocessing/template_metrics.py:53, in TemplateMetricsCalculator._select_extension_data(self, unit_ids)
     51 def _select_extension_data(self, unit_ids):
     52     # filter metrics dataframe
---> 53     new_metrics = self.template_metrics.loc[np.array(unit_ids)]
     54     return dict(metrics=new_metrics)

AttributeError: 'TemplateMetricsCalculator' object has no attribute 'template_metrics'

**Comment by alejoe91** [comment]
Thanks for the report! It's a small bug on our side due to a recent refactoring. I'll push a fix soon!
