### ISSUE TITLE
Too little documentation around handling of segmentations of recordings

### ISSUE THREAD

**Issue by FelixAntonSchneider** [SpikeInterface/spikeinterface#1111]
Hi,

posting this as a result of a discussion on the neuropixels slack.

When handling large recordings, it might be necessary to chunk it up into smaller pieces for the individual processing steps, since it would otherwise take too much RAM.

Apparently, everytime a function or method actually writes or processes traces, one can specify the chunk_duration parameter.
This is usually part of the job_kwargs.

It would be neat if there was a little more documentation around this feature

**Comment by alejoe91** [comment]
Now covered in [Module documentation](https://spikeinterface.readthedocs.io/en/latest/modules/core.html#manipulating-objects-slicing-aggregating)
