### ISSUE TITLE
Kilosort3 parameters documentations

### ISSUE THREAD

**Issue by jonathanlin1210** [SpikeInterface/spikeinterface#1127]
Hi, 

I am working on maxwell data with kilosort3 sorters and would like to play with the sorter parameters but couldn't find any documentation for what the parameters do. Is there anywhere I can find documentation/descriptions about what each parameter does?
Attached are the KS3 parameters that I am trying to work with.
![Screenshot 2022-11-30 150332](https://user-images.githubusercontent.com/86271353/204926763-c2fd739d-c0bf-42d0-b13b-9ab5e5f3580b.png)

Thanks,

**Comment by samuelgarcia** [comment]
`Kilosort3Sorter.params_description()` should give you info.

The best is to directly ask kilosort devs.

Note that is you use maxwell and do not have to much drift or motion I would recommand to use kilosort2.

**Comment by alejoe91** [comment]
Actually, we also have a specific function to get parameter descriptions:
```
import spikeinterface.sorters as ss
ss.get_sorter_params_description("kilosort3")
```

I agree with @samuelgarcia: try Kilosort2 first :)
