### ISSUE TITLE
Importing EDF Files

### ISSUE THREAD

**Issue by farazmoradi** [SpikeInterface/spikeinterface#115]
Hi, Is there any way that we can import EDF files directly to the spike interface?

**Comment by alejoe91** [comment]
Hi @farazmoradi 

EDF files are currently not supported. If you have Python code to load them, it's pretty straightforward to write an extractor for it. We have some instructions on how to do it here: https://spikeinterface.readthedocs.io/en/latest/recording_extractor.html

**Comment by samuelgarcia** [comment]
I plan to do it in neo since many years.
So it would also avaliable here.
I would be happy to help if you start a PR for EDF in neo.
Note that python-mne handle it already.

**Comment by farazmoradi** [comment]
Thanks, I get that!

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/853
