### ISSUE TITLE
write_to_h5_dataset_format for combinato

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spikeinterface#117]
Hi guys, going back to how to write h5 files for the combinato sorter.  What do you prefer?:

- making a function write_to_h5_**flat**_dataset_format inside the combinato spikesorter code
- adding a new argument (or including a special case in some of the existing ones) to the existing write_to_h5_dataset_format function.

And about how to remark that combinato can't handle multichannel recording, will be raising an error. Do you agree?

**Comment by samuelgarcia** [comment]
Hi Fernando.
For me you can extend the `write_to_h5_dataset_format()` if the default behavior is unchanged.
It will be simpler and more easy to read.

**Comment by samuelgarcia** [comment]
Closed with #134
