### ISSUE TITLE
Fix auto_merge randomness

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#1170]
@samuelgarcia @DradeAW 

The `auto_merge()` function fails now and then: https://github.com/SpikeInterface/spikeinterface/actions/runs/3765257303/jobs/6400671903#step:23:102

Could you look into it?

**Comment by DradeAW** [comment]
If I had to guess, I would say that the correlogram or template step is failing (few number of spikes means randomness.

https://github.com/SpikeInterface/spikeinterface/blob/fbc92d2c44f8954c62b15bc63765c44030f38ede/spikeinterface/curation/tests/test_auto_merge.py#L25

We could try setting a higher `duration` and/or `firing_rate` to see if things stabilize, but it might make the test take more time to run.

**Comment by alejoe91** [comment]
@DradeAW my bad!! In a recent PR, I unified the return values of ISI_violations and RP_violations, but I didn't change it in the curation module. Fixed it now :) Sorry about the false blaming!
See commit https://github.com/SpikeInterface/spikeinterface/pull/1142/commits/46871fba4dfe801d4cdc55dc96bc2a311f19f320
