### ISSUE TITLE
Error in the curation step 

### ISSUE THREAD

**Issue by kshtjkumar** [SpikeInterface/spikeinterface#1178]
I am working on the .rhs neural data file. Following your pipeline I was able to do most of the steps but, on the Curation step when I run :
we_curated = we.select_units(keep_units_ids, new_folder = "waveform")

I get an error: 'TemplateMetricsCalculator' object has no attribute 'template_metrics".

![curated error](https://user-images.githubusercontent.com/68465910/210179982-1874aa4d-39c7-4b64-859d-11ac175a6d57.PNG)

Can someone please help with the installation of  this while from the source ? I am relatively new to this :) 

Thank you.

**Comment by alejoe91** [comment]
You can find the instructions here: https://spikeinterface.readthedocs.io/en/latest/installation.html :)

**Comment by samuelgarcia** [comment]
Yes this should be fix in the master.
See also this for beginners :  https://github.com/SpikeInterface/spikeinterface/tree/master/installation_tips
