### ISSUE TITLE
error in opening sorted results with Phy

### ISSUE THREAD

**Issue by yinrocky** [SpikeInterface/spikeinterface#1179]
The sorted results were exported to phy. When loading the results to phy, the following error message shows up. 
I'm running Ubuntu 22.04 LTS.  I tried to downgrade the pyqtwebengine and pyqt5 version to 5.12, but doesn't work. In Windows 10, all works fine.
Many thanks!
![Screenshot from 2023-01-01 12-43-25](https://user-images.githubusercontent.com/63995346/210181706-f931371a-6464-4842-806e-a1ab59940bab.png)

**Comment by alejoe91** [comment]
Hi, Phy installation is quite tricky with the QT dependencies. Can you open an issue on the Phy GitHub page since that is an external package?

**Comment by yinrocky** [comment]
> Hi, Phy installation is quite tricky with the QT dependencies. Can you open an issue on the Phy GitHub page since that is an external package?

Okay, I see. thanks
