### ISSUE TITLE
[feat-postprocessing]: implement missing template metrics

### ISSUE THREAD

**Issue by davoudian** [SpikeInterface/spikeinterface#1185]
While most of the template/waveform metrics from the original [ecephys pipeline](https://github.com/AllenInstitute/ecephys_spike_sorting/tree/master/ecephys_spike_sorting/modules/mean_waveforms) are implemented via: `si.calculate_template_metrics(we)`, a 1D (and all 2D) metrics are missing including:

1D:
- [x] duration

2D:
- [ ] Waveform spread
- [ ] velocity above the soma
- [ ] velocity below the soma

**Comment by alejoe91** [comment]
@davoudian 

Duration is implemented and called `peak_to_valley` :) We'll work on the rest!
