### ISSUE TITLE
[sc-implementation] WaveformDenoiser component - inference

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1192]
This should come after [#1124](https://github.com/SpikeInterface/spikeinterface/issues/1124). The idea is to add the inference part (the transform method). 

There are some general points that should come with this PR:
* The infraestructure to handle model versioning, storage and serving should be provided (e.g. Hugging Face). Also, maybe a way to handle local models.
* General Denoiser abstract class that specificies in general how denoisers should behave (speciify input and output shapes and methods for example).

ETA since in progress
2-3 weeks.

**Comment by alejoe91** [comment]
closed via #1282
