### ISSUE TITLE
Port from spiketoolkit examples.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeinterface#12]
Some NB need also to be prt to spikeinterface doc:
  * curation_sorting_extractor_example.ipynb
  * quality_metrics_curation_example.ipynb
  * validation_example.ipynb

The second one depend on a dataset and so cannot be include for an auto build.
Unless the file would be directly downloadable and quite lightweigh.

What the plan.

I can start porting the first and third one.

@colehurwitz @alejoe91

**Comment by samuelgarcia** [comment]
validation_example.ipynb is totally oudated and not relevant.
Could you confirm ?

**Comment by alejoe91** [comment]
I believe so. @colehurwitz can confirm!

**Comment by colehurwitz** [comment]
Yep, validation example totally worthless now. Should be removed.
