### ISSUE TITLE
check_your_install.py fails

### ISSUE THREAD

**Issue by ablot** [SpikeInterface/spikeinterface#1200]
`python check_your_install.py` fails with an indent error because the window case of the `if` L94 is commented. Not sure if it should be uncommented or if it's better to add a `pass`.

https://github.com/SpikeInterface/spikeinterface/blob/87d19bca105bfe9483dbda9de8be89c3a5f2882b/installation_tips/check_your_install.py#L94

**Comment by alejoe91** [comment]
Thanks for the report!!
