### ISSUE TITLE
`cluster_si_unit_ids.tsv` from `export_to_phy` output is not updated properly in phy

### ISSUE THREAD

**Issue by a-zmz** [SpikeInterface/spikeinterface#1202]
Hi,

In the output of `export_to_phy`, I get a `cluster_si_unit_ids.tsv` file, and it does not get  proper update with merge/split. As a result, I have some units that do not have `si_unit_id`, and units ids loaded from `sorting.unit_ids` do not correspond to `cluster_info.tsv`, although the total number of units are the same...

![Screenshot from 2022-12-05 14-03-31](https://user-images.githubusercontent.com/77285087/212386860-862f25b7-fc1b-4444-86e2-be7a9cce736c.png)

This causes a problem in subsequent analyses when I need to access units, I cannot be sure whether I am accessing the information of the unit that I intended to.

What is the function of this `cluster_si_unit_ids.tsv` file, is it necessary as a output of `export_to_phy`? Can it be removed as it causes much confusion, so we can just access each unit by their `cluster_id`... Thanks!

**Comment by alejoe91** [comment]
Hi @a-zmz 

The `si_unit_id` represents the unit id in SpikeInterface. The `id` column, instead, needs to be a linearly increasing `int`. If you reimport the phy data to SpikeInterface, the original id (for unmerged/unsplitted units) would be lost. Note that when loading back to SI (`read_phy`), new `si_unit_id`s are assigned automatically to units that don't have it!

So I recommend not to remove it, but if you are not planning to reimport to SpikeInterface, then it doesn't matter

**Comment by a-zmz** [comment]
Hi Alessio thanks for quick replying.

It is still a bit confusing for me:
1. the results from running ks3 through si does not have `si_uni_id`, unit ids of sorting object from importing these results into si correspond to `cluster_id` in `cluster_info.csv`, i.e., uni ids in si are the same as cluster id. If this works for si without `si_uni_id` then `export_to_phy` output should also work?
2. i did try `read_phy` and `read_kilosort`, the sorting obj i got have the correct number of units. you mentioned that new `si_unit_id` will be assigned, but will the new assignment be saved/cached somewhere so i can map it to `cluster_id`? cuz the `cluster_info.tsv` is not updated...

Thanks!

**Comment by alejoe91** [comment]
> Hi Alessio thanks for quick replying.
> 
> It is still a bit confusing for me:
> 
> 1. the results from running ks3 through si does not have `si_uni_id`, unit ids of sorting object from importing these results into si correspond to `cluster_id` in `cluster_info.csv`, i.e., uni ids in si are the same as cluster id. If this works for si without `si_uni_id` then `export_to_phy` output should also work?

That is only true for Kilosort, because it outputs linearly increasing unit ids as integers (which is what phy needs). Note that if you remove empty units, the phy units and spikeinterface units will not match anymore. Say you manually flag some units as noise and then you reload the phy folder in spikeinterface, the `si_unit_id` will make sure that the newly loaded `unit_ids` correspond to the original unit_ids.

> 2. i did try `read_phy` and `read_kilosort`, the sorting obj i got have the correct number of units. you mentioned that new `si_unit_id` will be assigned, but will the new assignment be saved/cached somewhere so i can map it to `cluster_id`? cuz the `cluster_info.tsv` is not updated...
> 
The new `si_unit_id` will appear as `unit_ids`. All available columns from phy will be loaded accordingly. 

I hipe this is clearer!

**Comment by a-zmz** [comment]
hi Alessio, after `read_phy`, I i did get all units from the sorting object, but columns in phy are not updated, i.e., the file `cluster_si_unit_id.tsv` and `cluster_si_unit_ids.tsv` are not updated...

**Comment by alejoe91** [comment]
yes the files are not updates, because it's a `read_*` function. Why do you need to update the `.tsv` files?

**Comment by a-zmz** [comment]
lol right...
Because currently many of my subsequent analyses rely on `cluster_info.tsv`, and i index units using `cluster_id` in this file. I guess essentially i wonder if there is a way to map `si_unit_ids` to `cluster_id`?

**Comment by alejoe91** [comment]
@a-zmz maybe the best option then would be to load all columns of the cluster_info as properties, so we are 100% sure that we are assigning them correctly. I'll make a PR so you can test it out

**Comment by a-zmz** [comment]
@alejoe91 that sounds great thanks!
