### ISSUE TITLE
Add 'extra requirement' for quality metric sub-module 

### ISSUE THREAD

**Issue by CodyCBakerPhD** [SpikeInterface/spikeinterface#1223]
Issue discovered by adjusting dependencies on https://github.com/catalystneuro/neuroconv/pull/234, an extractor used in the testing suite uses some methods from the quality metrics submodule, and has minimal spikeinterface + scikit-learn installed, but ultimately results in some obscure errors about some level of `compute_quality_metrics` returning `None` instead of an object with a `_fields` attribute

The same code was previously working without issue, the only thing changed on that PR is the order and extend of secondary dependencies so I suspect that's the source of the problem

A simple fix would be to add an additional 'extra_requires' category for using the QM module, since I don't expect to need everything in `[full]` (or do I?)

**Comment by alejoe91** [comment]
@CodyCBakerPhD that's a good idea. We could definitely make module specific extra requirements!

**Comment by CodyCBakerPhD** [comment]
Uhh I might be misusing it on the NeuroConv testing suite, granted, but [according to that](https://github.com/catalystneuro/neuroconv/blob/main/requirements-testing.txt#L5-L6) it's

```
scikit-learn  # For SI Waveform tests
numba; python_version <= '3.10'  # For SI Waveform tests
```

when otherwise only using minimal SI (not `full`) installation
