### ISSUE TITLE
`test_calculate_drift_metrics` is failing on master

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1240]
I noticed this while working on #1227. I think that #1209 broke the test but because it is in a different module did not trigger the CI (this seems like a problem with our CI). Maybe it was even before that (could be #1143 ?).

Anyway, I propose to put the test on pause so we can continue working / merging while we repair this.

When this issue is closed this should also close #1239.

**Comment by alejoe91** [comment]
Thanks Ramon, I'll take a look rn

**Comment by alejoe91** [comment]
I agree we could pause the test for now, can you make a PR so I can merge it?

**Comment by h-mayorquin** [comment]
Done.  I also added another marker so this is ran whenever there is a change in sorting components to keep track of it. 

Probably, we should modify the CI in such a way that if a test imports a module, changing the imported module should run the tests. Maybe this can be done with importlib or by parsing the PATH. I wonder how much of hack that would be.
