### ISSUE TITLE
Problem using export_to_phy with BinaryFolderRecording

### ISSUE THREAD

**Issue by arturoptophys** [SpikeInterface/spikeinterface#1259]
Hi !

When trying to export a spikesorting results to phy, without saving the binary, while recording is an BinaryFolderRecording :
si.__version__ = '0.96.2.dev0'

---------------------------------------------------------------------------

> KeyError                                  Traceback (most recent call last)
> Input In [115], in <cell line: 21>()     
>      20 phy_folder = sorter_output_path / 'phy_folder'
> ---> 21 si.export_to_phy(
>      22     we,
>      23     phy_folder,
>      24     compute_pc_features=True,
>      25     compute_amplitudes=True,
>      26     sparsity=None,
>      27     copy_binary=False,
>      28     remove_if_exists=False)
> 
> File ~/spikeinterface/spikeinterface/exporters/to_phy.py:114, in export_to_phy(waveform_extractor, output_folder, compute_pc_features, compute_amplitudes, sparsity, copy_binary, remove_if_exists, peak_sign, template_mode, dtype, verbose, **job_kwargs)
>     112     write_binary_recording(recording, file_paths=rec_path, verbose=verbose, dtype=dtype, **job_kwargs)
>     113 elif isinstance(recording, BinaryRecordingExtractor):
> --> 114     rec_path = recording._kwargs['file_paths'][0]
>     115     dtype = recording.get_dtype()
>     116 else:  # don't save recording.dat
> 
> KeyError: 'file_paths'
> 

###################

Reason:

This is probably due to BinaryFolderRecording being instance of BinaryRecordingExtractor and trying to access kwargs['file_paths'],
however for BinaryFolderRecording only 'folder_path' is available

in extract_waveforms:

```
if copy_binary:
        rec_path = output_folder / 'recording.dat'
        write_binary_recording(recording, file_paths=rec_path, verbose=verbose, dtype=dtype, **job_kwargs)
elif isinstance(recording, BinaryRecordingExtractor):
        rec_path = recording._kwargs['file_paths'][0]
        dtype = recording.get_dtype()
else:  # don't save recording.dat
        rec_path = 'None'
```

#################
Potential fix, adding before the BinaryRecordingExtractor check

```
elif isinstance(recording, BinaryFolderRecording):
      rec_path = recording._kwargs['folder_path']
      dtype = recording.get_dtype()
```

Best,
Artur

**Comment by alejoe91** [comment]
Thanks for the report! Indeed what you suggest sounds like a good fix.
I'll try to push a PR tomorrow
