### ISSUE TITLE
Incorrect channel IDs in `SpikeGadgetsRecordingExtractor`

### ISSUE THREAD

**Issue by khl02007** [SpikeInterface/spikeinterface#1260]
Recordings from SpikeGadgets hardware have two possible channel maps: HWChan (a channel map defined by the amplifier) and Trodes channel map (for displaying on Trodes, the data acquisition software for SpikeGadgets). Both of these are in the header of the file that contains the recording (in `.rec` format). The channel IDs one gets with `get_channel_ids` from a `SpikeGadgetsRecordingExtractor` is in the Trodes order, which is sensible. But the order of the traces is completely scrambled (neither Trodes nor HWChan). Seems like this recording extractor relies on `neo`. @samuelgarcia @alejoe91 Could you take a look?

**Comment by alejoe91** [comment]
Hi @khl02007 

Can you post the issue on NEO and share a test data file?

**Comment by khl02007** [comment]
sure, now here https://github.com/NeuralEnsemble/python-neo/issues/1215

**Comment by zm711** [comment]
Closed by https://github.com/NeuralEnsemble/python-neo/pull/1496

Will require an install from source for now.
