### ISSUE TITLE
read SpyKingCircus2 sorter

### ISSUE THREAD

**Issue by ahubert69** [SpikeInterface/spikeinterface#1280]
Hi,

I was wondering if is was possible to read SpyKingCircus2 sorting?
Actually spykingcircus and spykingcircus2 are availaible when running a sorter, but read_spykingcircus function is unable to read spykingcircus2 folder and read_spykingcircus2 don't exist.

Any solution?
Thanks in advance,
Arnaud.

**Comment by ahubert69** [comment]
Thanks for the fast answer.
However I get the following error:

AttributeError: module 'spikeinterface.full' has no attribute 'read_sorter'. Did you mean: 'run_sorter'?

neither spikeinterface.extractors has this attribute.

**Comment by yger** [comment]
Sorry. I meant si.read_sorter_folder()

**Comment by ahubert69** [comment]
Working.
Thanks a lot!
