### ISSUE TITLE
Move to src package structure

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1344]
We have some errors like #1316 and #1333 that would have not been an issue had we used a src structure:
https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

Plus this is the recommended way of the python packaking authority:
https://github.com/pypa/sampleproject

I honestly don't know any downside of using that strcuture other than aestethical concerns that it looks bad (maybe this is my chance to learn some good ones).

What do you guys think of making this change?

**Comment by samuelgarcia** [comment]
We already discuss this when refactoring to pyproject.toml.
I do not like it but I admit that it avoid many beginners installation errors.

**Comment by alejoe91** [comment]
@h-mayorquin after discussing with @samuelgarcia we agree that this should be the way to go!

**Comment by h-mayorquin** [comment]
Great, I am thinking that we can do this after #1354. As that is a big change of its own, what do you think?

**Comment by samuelgarcia** [comment]
Can we wait a bit more ?

**Comment by h-mayorquin** [comment]
Yes, when do you think is a good point @samuelgarcia?  Do you have some PRs on the line that would be disturbed by this? 

This needs to be done quick as it will stop all the repo on the rails.  Maybe we can agree to do it at the end of weekly meeting. I prepare everything, we quickly checking everything together and we merge. I reckon it will take around 15 minutes of our time.

**Comment by h-mayorquin** [comment]
I think this is another error that was generated by the workflow of importing from the base #1388.

**Comment by alejoe91** [comment]
should also fix #1465

**Comment by h-mayorquin** [comment]
We are moving forward with this. I will keep a list of the PRs that have to be merged:
* #1477 changes in docs. Nothing to be done.
* #1475 this is merged in #1478
*  #1471 change in docs. Nothing to be done.

**Comment by h-mayorquin** [comment]
This is done
