### ISSUE TITLE
 'Spike sorting failed' following new installation 0.98.0.dev0-py3.9

### ISSUE THREAD

**Issue by bradlytstone** [SpikeInterface/spikeinterface#1352]
I have successfully installed and imported the newest version of spikeinterface. Following my pipeline which previously _worked_, in this new version, I do get the same warning previously brought up in #1333 :

# Detect bad channels
bad_channel_ids, channel_labels = spre.detect_bad_channels(reader_filtered)

# Warning 
C:\Users\SuperComputer1\miniconda3\lib\site-packages\scipy\signal\_spectral_py.py:2014: UserWarning: nperseg = 244 is greater than input length  = 32, using nperseg = 32
  warnings.warn('nperseg = {0:d} is greater than input length 

Disregarding the warning, for the sake of moving forward, I go on to attempt to run the spike sorting processes. 

# Set common reference params
recording_cmr = si.common_reference(reader_filtered, reference='global',\
                    operator='median',ref_channel_ids = [str(x+1) for x in ref_channel_inds])

# Spike sort
sorting_spyk = ss.run_sorter(sorter_name="spykingcircus2", recording = recording_cmr,\
                            output_folder='spykcirc2_output1', apply_preprocessing=False)

# Warning 
C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\core\baserecordingsnippets.py:217: UserWarning: There is no Probe attached to this recording. Creating a dummy one with contact positions
  warn(
Traceback (most recent call last):
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sorters\basesorter.py", line 226, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sorters\si_based_sorters\spyking_circus2.py", line 111, in _run_from_folder
    labels, peak_labels = find_cluster_from_peaks(recording_f, selected_peaks, method='random_projections',
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sortingcomponents\clustering\main.py", line 39, in find_cluster_from_peaks
    labels, peak_labels = method_class.main_function(recording, peaks, params)
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sortingcomponents\clustering\random_projections.py", line 205, in main_function
    labels, peak_labels = remove_duplicates_via_matching(we, noise_levels, peak_labels,
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sortingcomponents\clustering\clustering_tools.py", line 566, in remove_duplicates_via_matching
    spikes, computed = find_spikes_from_templates(sub_recording, method='circus-omp', method_kwargs=method_kwargs,
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sortingcomponents\matching\main.py", line 62, in find_spikes_from_templates
    spikes = processor.run()
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\core\job_tools.py", line 339, in run
    res = self.func(segment_index, frame_start, frame_stop, worker_ctx)
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sortingcomponents\matching\main.py", line 108, in _find_spikes_chunk
    with threadpool_limits(limits=1):
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 373, in _load_modules
    self._find_modules_with_enum_process_module_ex()
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'

Traceback (most recent call last):

  File "C:\Users\SuperComputer1\AppData\Local\Temp\ipykernel_18772\657437815.py", line 1, in <module>
    sorting_spyk = ss.run_sorter(sorter_name="spykingcircus2", recording = recording_cmr,\

  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sorters\runsorter.py", line 143, in run_sorter
    return run_sorter_local(**common_kwargs)

  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sorters\runsorter.py", line 163, in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)

  File "C:\Users\SuperComputer1\miniconda3\lib\site-packages\spikeinterface-0.98.0.dev0-py3.9.egg\spikeinterface\sorters\basesorter.py", line 262, in run_from_folder
    raise SpikeSortingError(

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in spykcirc2_output1/spikeinterface_log.json

# A look at the json file
{
    "sorter_name": "spykingcircus2",
    "sorter_version": "2.0",
    "datetime": "2023-02-21T09:50:18.419807",
    "runtime_trace": [],
    "error": true,
    "error_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sorters\\basesorter.py\", line 226, in run_from_folder\n    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sorters\\si_based_sorters\\spyking_circus2.py\", line 111, in _run_from_folder\n    labels, peak_labels = find_cluster_from_peaks(recording_f, selected_peaks, method='random_projections',\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sortingcomponents\\clustering\\main.py\", line 39, in find_cluster_from_peaks\n    labels, peak_labels = method_class.main_function(recording, peaks, params)\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sortingcomponents\\clustering\\random_projections.py\", line 205, in main_function\n    labels, peak_labels = remove_duplicates_via_matching(we, noise_levels, peak_labels,\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sortingcomponents\\clustering\\clustering_tools.py\", line 566, in remove_duplicates_via_matching\n    spikes, computed = find_spikes_from_templates(sub_recording, method='circus-omp', method_kwargs=method_kwargs,\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sortingcomponents\\matching\\main.py\", line 62, in find_spikes_from_templates\n    spikes = processor.run()\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\core\\job_tools.py\", line 339, in run\n    res = self.func(segment_index, frame_start, frame_stop, worker_ctx)\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\spikeinterface-0.98.0.dev0-py3.9.egg\\spikeinterface\\sortingcomponents\\matching\\main.py\", line 108, in _find_spikes_chunk\n    with threadpool_limits(limits=1):\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 171, in __init__\n    self._original_info = self._set_threadpool_limits()\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 268, in _set_threadpool_limits\n    modules = _ThreadpoolInfo(prefixes=self._prefixes,\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 340, in __init__\n    self._load_modules()\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 373, in _load_modules\n    self._find_modules_with_enum_process_module_ex()\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 485, in _find_modules_with_enum_process_module_ex\n    self._make_module_from_path(filepath)\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 515, in _make_module_from_path\n    module = module_class(filepath, prefix, user_api, internal_api)\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 606, in __init__\n    self.version = self.get_version()\n  File \"C:\\Users\\SuperComputer1\\miniconda3\\lib\\site-packages\\threadpoolctl.py\", line 646, in get_version\n    config = get_config().split()\nAttributeError: 'NoneType' object has no attribute 'split'\n",
    "run_time": null
}

# Concerns
So my initial concerns are that it says I have no probe attach, but when I check this, 'recording_cmr.get_probe()' I most certainly do have a probe (I set this within my pipeline). Further, the errors that come after are a bit uninterpretable to me. Thank you for your assistance!

**Comment by yger** [comment]
This error is likely due to a problem of version mismatch between the different packages. I guess it has nothing to do with spikeinterface per se

See for example https://github.com/scikit-learn/scikit-learn/issues/24238

I guess maybet the following combination is worth trying, as said in the link?
numpy                     1.21.5           py39h7a0a035_3
scikit-learn              1.1.3            py39hd77b12b_0
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge

**Comment by bradlytstone** [comment]
I have manually installed each of the versions in that link (numpy 1.21.5, scikit-learn 1.1.3, and threadpoolctl 3.1.0), yet I have the same error message. Again, I am using **0.98.0.dev0-py3.9**, which likely differs from the link you sent -- which worked for the user back in December.

**Comment by alejoe91** [comment]
How did you install SI? Can you try with the released version?
`pip install spikeinterface[full]==0.97.0`

**Comment by alejoe91** [comment]
Also, try to visualize the traces that you pipe into the sorter (`sw.plot_timeseries(recording_cmr)`) to see if they look fine (and sortable!)

**Comment by bradlytstone** [comment]
Did the latest verison (0.97.0) come out prior to two weeks ago? If so, I worry that I will just be uninstalling the 98 version, and having to reinstall it to account for the other bugs (brought up in the channel_order issue #1333)?

Further, I have tried and loaded another file (where I use optogenetics to induce spiking -- and it seems to "run"), however, the warning "There is no Probe attached to this recording. Creating a dummy one with contact positions" is still present. This is an issue I have brought up, as well, and concerns me because I have (using steps discussed with your team) 'attached' the probe to the recording. 

When you say "sortable", that worries me. What "cut-offs' or specifications do you _typically_ use as guidelines to users to determine if something is sortable? In the file(s) that I brought these issues up with, I can certainly (visually) see spikes.... but whether or not there are "enough" for the algorithms to detect is a different story, which is why I am asking. What size recordings do you recommend users record, to obtain a _minimum_ detectable/sortable events?

Thanks.

**Comment by alejoe91** [comment]
If you see spikes, that is enough ;) just as a quality check!

0.97 was released a couple of weeks ago. We'll release a patch in the next days. Did you try other sorters? Indeed it's weird that it gives the probe warning is when you do `recording_cmr.get_probe()` you get a probe object.

Can you try the following?
`reader = reader.save(folder="binary")`

This saves the TDT reader (which migh be the cause of the problem, for example for parallel access to the files) to a binary file in the "binary" folder. 
Of course this would fix (hopefully) the symptom and not the cause, but it's a start!

**Comment by bradlytstone** [comment]
Great, thanks :)

Yes, I have tried several sorters (e.g. tridesclous, spykingcircus2). I consistently get the 'There is no probe attached to this recording...' error. When I do 'recording_cmr.get_probe()' I get 'Probe - 32ch - 1shanks' (which, to me, indicates the probe was successfully attached).

Where in the processing pipeline (e.g. before or after spike sorting command) do you suggest I do this "reader.save()" command? 

Thanks for your continued support! Super appreciated.

**Comment by alejoe91** [comment]
Right after you load it:

```
reader = se.read_tdt(...)
reader = reader.save(folder="binary")
```

**Comment by bradlytstone** [comment]
Thank @alejoe91, this seemed to have worked. As an update, in order to run the sorter, because we saved the reader in binary and then filtered, I had to do the following: recording_cmr.annotate(is_filtered=True) to eliminate the runtime error (found in the json file).

**Comment by alejoe91** [comment]
Yes. Note that you can also first filter and then save ;) In that case you don't have to re-add the `is_filtered` annotation
