### ISSUE TITLE
Documentation Help

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#1380]
I noticed a few minor words missing in the documentation. Just wanted to see if you wanted an extra pair of eyes in the readthedocs or whether you already had the documentation help you needed.

**Comment by alejoe91** [comment]
Hi Zach,

Of course it would be great if we could borrow your extra pair of eyes :) 
Thanks for the suggestion!!

**Comment by zm711** [comment]
One quick question for the documentation. It goes back and forth between spikeinterface and SpikeInterface. Which is the preferred way to refer to the package or does the capitalization change the meaning of what is specifically being referred to?

I'm happy to work on making it consistent in the docs if the group has a preference.

**Comment by alejoe91** [comment]
Mmm that's a good question. In general the project tis called SpikeInterface, but maybe we can just leave that in the title/index page and use lower case in the actual modules documentation. Sounds fair?

**Comment by h-mayorquin** [comment]
Thanks for your contributions @zm711. I am closing this issue. If anybody reads this in the future let it be know that contributions to documentation are highly welcomed and encouraged.
