### ISSUE TITLE
Singularity tests failing on master

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1392]
Full tests are failing on master:
https://github.com/SpikeInterface/spikeinterface/actions/runs/4323218924/jobs/7546566323

Related to #1386
I think the reason isthat the new singularity tests don't have access to the dev path. We can do two things:
* Add the dev path to the full tests so the singularity tests are ran there.
* Remove the singularity tests from the full tests with marking machinery.

What's better?

**Comment by alejoe91** [comment]
Second option :)

We should actually skip all `sorters_external` tests for code cov! The files are skipped in the codecov.yml

**Comment by alejoe91** [comment]
@h-mayorquin could you take care of this? :)
