### ISSUE TITLE
Postprocessing Tutorial compute spike waveforms not as expected.

### ISSUE THREAD

**Issue by mandarmp** [SpikeInterface/spikeinterface#1406]
I am new to spike sorting and was exploring the post processing tutorial in the read the docs. [https://spikeinterface.readthedocs.io/en/0.92.0/modules/toolkit/plot_2_postprocessing.html](url)

The data is a HD-MEA recording of the network activity of neurons.(1024 electrodes with high firing rate from Maxwel)

When I try to plot the waveforms on the particular electrode. The spikes are not aligned as seen in the picture.
![alignmentofdata](https://user-images.githubusercontent.com/33731455/223858998-e2ac4434-6bd1-413c-958c-7465e5dfef2d.png)

Should I follow some alignment procedure to get better templates? Thank you in advance for helping out.

**Comment by mandarmp** [comment]
Also it there a slack group/ discord group for spike sorting related stuff. Thank you.

**Comment by mandarmp** [comment]
Nvm resolved the issue.

**Comment by alejoe91** [comment]
Great to hear. What was the issue in the end?

**Comment by mandarmp** [comment]
It was a rather silly misunderstanding from my side. I didn't know that get_waveforms ..returned the electrical footprint on all the electrodes and I was printing the wrong electrode. I used the get_template_extremum_channels to find out the right electrode. Is there any forums where I can ask such questions rather than creating a GitHub issue. New to spike sorting please help. Thank you so much.
