### ISSUE TITLE
a small bug in generate_erroneous_sorting

### ISSUE THREAD

**Issue by ZoeChen96** [SpikeInterface/spikeinterface#1426]
[generate_erroneous_sorting](https://github.com/SpikeInterface/spikeinterface/blob/4bdf86eb86a399989a2461ebdefa0f1a5624bc62/examples/modules_gallery/comparison/generate_erroneous_sorting.py#L61)

This line should be `units_err[82] = st82` instead of `units_err[81] = st82`

**Comment by h-mayorquin** [comment]
Thanks for pointing this out. We will fix it as soon as possible.

**Comment by ZoeChen96** [comment]
Thanks Heberto!
