### ISSUE TITLE
kilosort3 install check problem

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikeinterface#1427]
Kilosort3 install checks

```
if (Path(kilosort3_path) / 'main_kilosort3.m').is_file():
```

but main_kilosort3.m is not in the current kilosort repo.

**Comment by alejoe91** [comment]
Are you sure your cloned repo is up-to-date?

https://github.com/MouseLand/Kilosort/blob/main/main_kilosort3.m

**Comment by magland** [comment]
Sorry, you are right! Closing.
