### ISSUE TITLE
traces_chunk should be traces in whiten.py

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikeinterface#1436]
See:
https://github.com/SpikeInterface/spikeinterface/blob/0247c57f5e510e630e1fbc59060c2e75fde3b3b6/spikeinterface/preprocessing/whiten.py#L83-L84

**Comment by samuelgarcia** [comment]
Done in #1437

**Comment by magland** [comment]
Thanks @samuelgarcia , you beat me to it!
