### ISSUE TITLE
Path type check is too restrictive in `recursive_path_modifier` method

### ISSUE THREAD

**Issue by miketrumpis** [SpikeInterface/spikeinterface#1458]
Sometimes attributes with "path" in the name have a `None` value, but there is no condition for None in this method: `spikeinterface.core.core_tools.recursive_path_modifier`

https://github.com/SpikeInterface/spikeinterface/blob/a5942a1cb540c6abb8876b01136044eca39d4842/spikeinterface/core/core_tools.py#L794-L804

For example, a `NwbRecordingExtractor` has a `stream_cache_path` that defaults to `None`.

Made a quick PR for this

**Comment by alejoe91** [comment]
Fixed by #1459
