### ISSUE TITLE
docs update for Kilosort2_5Sorter

### ISSUE THREAD

**Issue by JoeZiminski** [SpikeInterface/spikeinterface#1472]
Just a quick note the docs [here](https://spikeinterface.readthedocs.io/en/latest/install_sorters.html)

line

`# or using Kilosort2_5Sorter.set_kilosort2_path()`

seems to be outdated and the API now is

`set_kilosort2_5_path`

cheers!

**Comment by JoeZiminski** [comment]
#1479 (sorry just found the docs on gh)

**Comment by JoeZiminski** [comment]
#1479

**Comment by alejoe91** [comment]
Fixed in `main` #1482
