### ISSUE TITLE
Recording extractor for Herdingspikeresults and Ironclust results

### ISSUE THREAD

**Issue by Shivooone** [SpikeInterface/spikeinterface#148]
Hello,

I have a trouble concerning the spikeextractors since I believe that the herdingspikes extractor is HS2SortingExtractor but I get the following error

![image](https://user-images.githubusercontent.com/82379695/118492103-f9568c00-b71f-11eb-84c5-4a5630e3f6ea.png)

![image](https://user-images.githubusercontent.com/82379695/118492227-1d19d200-b720-11eb-8eb4-2122ae868449.png)

Could you please give me a hint on that ?

Moreover It seems that the ironclust results extractor doesn't exist?

Thanks a lot for your help,
Shiva

**Comment by alejoe91** [comment]
Hi Shiva,

The `HS2SortingExtractor` needs the `file_path` (not folder path) to the hdf5 result file.

As for IronClust, did you run it with SpikeInterface? In that case you can load the `firings.mda` with the `MdaSortingExtractor`.

Cheers
Alessio

**Comment by samuelgarcia** [comment]
Hi Shiva,
yes MdaSortingExtractor is not implemented yet. We will do at the end of the weeks.
Sam

**Comment by alejoe91** [comment]
@samuelgarcia it's the current API (the error comes from spikeextractors)

**Comment by samuelgarcia** [comment]
Shiva, you should use the new API !!

**Comment by Shivooone** [comment]
Perfect, thanks for your answers :)
