### ISSUE TITLE
extracting stream_names and stream_ids

### ISSUE THREAD

**Issue by skyetomez** [SpikeInterface/spikeinterface#1586]
Hello,

I need to be able to extract the stream_names and stream_ids from recordings without knowing what they are prior. 
Do you have any utility functions that parse and return these? 
It looks like there is something similar in your `get_neo_io_reader`  command returns an object with the header information through the header attribute. Is there something like this available or some commands I can use?

**Comment by samuelgarcia** [comment]
Hi,
Did you try the `get_neo_streams()`

**Comment by alejoe91** [comment]
@samuelgarcia the `get_neo_streams()` requires to specify the extractor name...

@skyetomez this is a bit ugly, but should work:
```
import spikeinterface.extractors as se
file_path = "..."

for extractor_name in se.recording_extractor_full_dict:
    try:
        stream_names, stream_ids = se.get_neo_streams(extractor_name, file_path)
        print(f"Correct type: {extractor_name}")
    except:
        pass
```
