### ISSUE TITLE
`MEArecSortingExtractor` gives wrong spike timings

### ISSUE THREAD

**Issue by DradeAW** [SpikeInterface/spikeinterface#1623]
Hey,

I have a `recording.h5` made with MEArec, and with the recent versions, here is the output:

```
sorting.get_unit_spike_train('#0')
>>> array([   0,    0,    1, ..., 2699, 2699, 2699])
```

This is clearly not a correct spike train from a ground truth ^^ (the file worked perfectly fine before).

My recording is 45m, which is 2700s. So there might be a multiplication by sampling frequency missing somewhere?

**Comment by samuelgarcia** [comment]
Oups. @h-mayorquin I think we merged the #1611 too quickly no ?

**Comment by h-mayorquin** [comment]
#1611 was supposed to solve that bug. @DradeAW, are you sure you are using main after merging it? I was testing this just some hours ago and it was working. Can you confirm this is the latest main?

**Comment by DradeAW** [comment]
Ah I could have sworn I was on the latest SpikeInterface, but evidently not.
Pulling to the newest main solves the issue (although now loading the sorting takes ~6s, is that normal?)

Closing the issue, sorry for the stupid report ^^

**Comment by h-mayorquin** [comment]
No, it shouldn't affect the loading times. I will take a look at that.

**Comment by h-mayorquin** [comment]
I could not reproduce the slowing loading times, is that still with mearec? I also can't think on something that could have caused that. What branch / commit where you before merging the latest main and caused the slowdown?

**Comment by DradeAW** [comment]
Yes it's a `sorting = se.MEArecSortingExtractor("recording.h5")` that's taking 6s.
This is a big recording (45 minutes for 1,500 cells)

I'm not sure where I was before, but it's probably `1f5a8fc` or `601694d`.

**Comment by h-mayorquin** [comment]
Could you check loading in those two commits to see if loads slower on them when you have a chance?

**Comment by h-mayorquin** [comment]
Mmm, I see,  but this is too long right? f that's true then the only thing would be to try some of the commits in https://github.com/SpikeInterface/spikeinterface/pull/1550 to see if that makes it after (as it should).

If it was a glitch, then let me know if you encounter some slowdown.

**Comment by DradeAW** [comment]
Well this is the sorting, which I'm only loading once (I'm compared ground truth to many sorters, so many waveform extractor with the same recording but all different sorting).

Maybe I'll dive into it next week (I'll have more free time then), but I think the time taken is just to load all the spike trains (a npz sorting would probably take as much time)

**Comment by h-mayorquin** [comment]
Ah, I see, yep, last time it was about recorders. Mearec sorting is still loading into memory so it is bound to be slower to initialize.
