### ISSUE TITLE
Can not (anymore) load data with read_mearec()

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#1629]
Something has been changed recently? Because I just tried to run my scripts (with updated main), and it seems I can not read mearec files anymore... I'll try to dig in and double check everything, but does it ring a bell?

TypeError: __init__() got an unexpected keyword argument 'load_spiketrains'

**Comment by alejoe91** [comment]
@yger you need to update neo master!

**Comment by yger** [comment]
This is what I did.. I'll recheck in the afternoon, but I updated mearec and neo, without any changes
