### ISSUE TITLE
radius_um is not a valid plot argument or backend keyword argument.

### ISSUE THREAD

**Issue by majidkhalili** [SpikeInterface/spikeinterface#1678]
Hello,

I am following "Official_Tutorial_SI_0.96_Oct22", and when I want to plot the unit templates form the extracted waveforms using this command: 

`sw.plot_unit_templates(tstWF, radius_um=50, backend="ipywidgets")`

I get this error:

> Exception: radius_um is not a valid plot argument or backend keyword argument. Possible backend keyword arguments for ipywidgets are: ['width_cm', 'height_cm', 'display']

When I removed the ` radius_um=50` argument, I can get it plotted, but it is very difficult to navigate in the figure when everything is plotted. It would be really helpful to have only waveform with a certain radius plotted (as mentioned in the tutorial). 

any idea what might be the issue? and how I can resolve it?

Thanks in advance.

**Comment by alejoe91** [comment]
Hi,

Recently we changed the API to make the use of _sparsity_ more explicit (see [https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.widgets.plot_unit_templates]).

Here is an example that achieves the old behavior with the new function call:
```
# explicitly define a sparsity object
sparsity = si.compute_sparsity(tstWF, method="radius", radius_um=50)

sw.plot_unit_templates(tstWF, sparsity=sparsity, backend="ipywidgets")
```

**Comment by majidkhalili** [comment]
Perfect, thanks
