### ISSUE TITLE
run_extract_waveforms after cluster split curation with Phy

### ISSUE THREAD

**Issue by Antho2422** [SpikeInterface/spikeinterface#1690]
Hi everyone, 

I'm trying to make a curation using Phy. My current process is the following : 

- Run sorter spykingcircus2
- export waveforms to then export results to phy. My waveforms are saved in a new 'waveforms' folder.
- Do manual curation using Phy. I don't have any issues when I assign groups to clusters ('good', 'mua', 'noise) but I think the issue is coming from Merge/split of clusters. 
- Reading phy and creating a PhySortingExtractor (correctly updated because I have the right number of units after curation)
- I then try to remove my old 'waveforms' folder to create a new one with the updated waveforms from the new clusters. I'm trying to extract_waveforms.

I get an error on this last step when running extract waveforms. I tried to :
- don't remove original 'waveforms' folder but trying to extract curated waveforms from the curated sorting in a new folder.
- Running on my recording and updated sorting the function 'extract_waveforms() (with mode='memory' and mode='memmap')
- Create a WaveformExtractor object, then setting the params and the error is occuring when I run  we.run_extract_waveforms()

Nothing worked unfortunately. Sometimes the merge of units worked but it's not consitent. The split of cluster never worked tho...

This is my error : OSError: [Errno 22] Invalid argument: 'path_to_my_data\\waveforms\\waveforms_1.npy'

Please see attached a SC of my error.

Thank you, 
Anthony

![image](https://github.com/SpikeInterface/spikeinterface/assets/98460480/043f662f-d791-40b5-b149-04a1f2e0c76a)

**Comment by alejoe91** [comment]
Hi Anthony,

The `run_extract_waveforms` is failing because it points to the "old" sorting object (the uncurated one) and you deleted the old waveforms folder.

Instead, you should re-extract waveforms using the recording and the new sorting object:
```
sorting_curated = se.read_phy("path-to-phy-folder")

we_curated = si.extract_waveforms(recording, sorting_curated, "new_folder")
```

**Comment by Antho2422** [comment]
Hi Alessio, 

Thank you for your answer. I tried to review my process and if I'm not mistaken I don't think I'm pointing to the 'old' sorting object. I'm giving the sorting curated to extract_waveforms() and I try to not delete the old waveforms folder and I still get the error. The file waveforms_1.npy exists but I cannot open it in "wb"

**Comment by Antho2422** [comment]
![image](https://github.com/SpikeInterface/spikeinterface/assets/98460480/e1de3a94-ca73-4b33-865d-efc6d0c17abd)

My "old" sorting had 3 units and when se.read_phy() I get the "curated sorting" with 4 units.

**Comment by alejoe91** [comment]
Can you paste the full error?

**Comment by Antho2422** [comment]
Sure : 

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[19], line 1
----> 1 we_curated = si.extract_waveforms(recording, curated_sorting, "new_folder")
      2 we_curated

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_extractor.py:1450](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_extractor.py:1450), in extract_waveforms(recording, sorting, folder, mode, precompute_template, ms_before, ms_after, max_spikes_per_unit, overwrite, return_scaled, dtype, sparse, sparsity, num_spikes_for_sparsity, allow_unfiltered, use_relative_path, seed, load_if_exists, **kwargs)
   1446 we = WaveformExtractor.create(recording, sorting, folder, mode=mode, use_relative_path=use_relative_path,
   1447                               allow_unfiltered=allow_unfiltered, sparsity=sparsity)
   1448 we.set_params(ms_before=ms_before, ms_after=ms_after, max_spikes_per_unit=max_spikes_per_unit, dtype=dtype,
   1449               return_scaled=return_scaled)
-> 1450 we.run_extract_waveforms(seed=seed, **job_kwargs)
   1452 if precompute_template is not None:
   1453     we.precompute_templates(modes=precompute_template)

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_extractor.py:1255](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_extractor.py:1255), in WaveformExtractor.run_extract_waveforms(self, seed, **job_kwargs)
   1252 else:
   1253     sparsity_mask = self.sparsity.mask
-> 1255 wfs_arrays = extract_waveforms_to_buffers(self.recording, spikes, unit_ids, nbefore, nafter,
   1256                                           mode=mode, return_scaled=return_scaled, folder=wf_folder,
   1257                                           dtype=p['dtype'], sparsity_mask=sparsity_mask, copy=copy,
   1258                                           **job_kwargs)
   1259 if self.folder is None:
   1260     self._memory_objects["wfs_arrays"] = wfs_arrays

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_tools.py:82](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_tools.py:82), in extract_waveforms_to_buffers(recording, spikes, unit_ids, nbefore, nafter, mode, return_scaled, folder, dtype, sparsity_mask, copy, **job_kwargs)
     78         dtype = 'float32'
     79 dtype = np.dtype(dtype)
---> 82 wfs_arrays, wfs_arrays_info = allocate_waveforms_buffers(recording, spikes, unit_ids, nbefore, nafter, mode=mode,
     83                                                          folder=folder, dtype=dtype, sparsity_mask=sparsity_mask)
     85 distribute_waveforms_to_buffers(recording, spikes, unit_ids, wfs_arrays_info, nbefore, nafter, return_scaled,
     86                                 mode=mode, sparsity_mask=sparsity_mask, **job_kwargs)
     88 if mode == 'memmap':

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_tools.py:162](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_tools.py:162), in allocate_waveforms_buffers(recording, spikes, unit_ids, nbefore, nafter, mode, folder, dtype, sparsity_mask)
    160 if mode == 'memmap':
    161     filename = str(folder / f'waveforms_{unit_id}.npy')
--> 162     arr = np.lib.format.open_memmap(
    163         filename, mode='w+', dtype=dtype, shape=shape)
    164     wfs_arrays[unit_id] = arr
    165     wfs_arrays_info[unit_id] = filename

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\numpy\lib\format.py:900](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/numpy/lib/format.py:900), in open_memmap(filename, mode, dtype, shape, fortran_order, version, max_header_size)
    894 d = dict(
    895     descr=dtype_to_descr(dtype),
...
--> 900 with open(os_fspath(filename), mode+'b') as fp:
    901     _write_array_header(fp, d, version)
    902     offset = fp.tell()

OSError: [Errno 22] Invalid argument: 'new_folder\\waveforms\\waveforms_1.npy'

**Comment by Antho2422** [comment]
```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[19], line 1
----> 1 we_curated = si.extract_waveforms(recording, curated_sorting, "new_folder")
      2 we_curated

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_extractor.py:1450](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_extractor.py:1450), in extract_waveforms(recording, sorting, folder, mode, precompute_template, ms_before, ms_after, max_spikes_per_unit, overwrite, return_scaled, dtype, sparse, sparsity, num_spikes_for_sparsity, allow_unfiltered, use_relative_path, seed, load_if_exists, **kwargs)
   1446 we = WaveformExtractor.create(recording, sorting, folder, mode=mode, use_relative_path=use_relative_path,
   1447                               allow_unfiltered=allow_unfiltered, sparsity=sparsity)
   1448 we.set_params(ms_before=ms_before, ms_after=ms_after, max_spikes_per_unit=max_spikes_per_unit, dtype=dtype,
   1449               return_scaled=return_scaled)
-> 1450 we.run_extract_waveforms(seed=seed, **job_kwargs)
   1452 if precompute_template is not None:
   1453     we.precompute_templates(modes=precompute_template)

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_extractor.py:1255](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_extractor.py:1255), in WaveformExtractor.run_extract_waveforms(self, seed, **job_kwargs)
   1252 else:
   1253     sparsity_mask = self.sparsity.mask
-> 1255 wfs_arrays = extract_waveforms_to_buffers(self.recording, spikes, unit_ids, nbefore, nafter,
   1256                                           mode=mode, return_scaled=return_scaled, folder=wf_folder,
   1257                                           dtype=p['dtype'], sparsity_mask=sparsity_mask, copy=copy,
   1258                                           **job_kwargs)
   1259 if self.folder is None:
   1260     self._memory_objects["wfs_arrays"] = wfs_arrays

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_tools.py:82](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_tools.py:82), in extract_waveforms_to_buffers(recording, spikes, unit_ids, nbefore, nafter, mode, return_scaled, folder, dtype, sparsity_mask, copy, **job_kwargs)
     78         dtype = 'float32'
     79 dtype = np.dtype(dtype)
---> 82 wfs_arrays, wfs_arrays_info = allocate_waveforms_buffers(recording, spikes, unit_ids, nbefore, nafter, mode=mode,
     83                                                          folder=folder, dtype=dtype, sparsity_mask=sparsity_mask)
     85 distribute_waveforms_to_buffers(recording, spikes, unit_ids, wfs_arrays_info, nbefore, nafter, return_scaled,
     86                                 mode=mode, sparsity_mask=sparsity_mask, **job_kwargs)
     88 if mode == 'memmap':

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\spikeinterface\core\waveform_tools.py:162](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/spikeinterface/core/waveform_tools.py:162), in allocate_waveforms_buffers(recording, spikes, unit_ids, nbefore, nafter, mode, folder, dtype, sparsity_mask)
    160 if mode == 'memmap':
    161     filename = str(folder / f'waveforms_{unit_id}.npy')
--> 162     arr = np.lib.format.open_memmap(
    163         filename, mode='w+', dtype=dtype, shape=shape)
    164     wfs_arrays[unit_id] = arr
    165     wfs_arrays_info[unit_id] = filename

File [c:\Users\anthony.pinto\AppData\Local\pypoetry\Cache\virtualenvs\priam-5spsvreu-py3.9\lib\site-packages\numpy\lib\format.py:900](file:///C:/Users/anthony.pinto/AppData/Local/pypoetry/Cache/virtualenvs/priam-5spsvreu-py3.9/lib/site-packages/numpy/lib/format.py:900), in open_memmap(filename, mode, dtype, shape, fortran_order, version, max_header_size)
    894 d = dict(
    895     descr=dtype_to_descr(dtype),
...
--> 900 with open(os_fspath(filename), mode+'b') as fp:
    901     _write_array_header(fp, d, version)
    902     offset = fp.tell()

OSError: [Errno 22] Invalid argument: 'new_folder\\waveforms\\waveforms_1.npy'
```

**Comment by alejoe91** [comment]
Can you run:

`print(sorting_curated.unit_ids)`

?

**Comment by Antho2422** [comment]
Yes I think the problem comes from the missmatch between SI units ids and the Phy ones 

Here is the output 

![image](https://github.com/SpikeInterface/spikeinterface/assets/98460480/08f4e876-7f17-4645-b088-b40055b2839a)

**Comment by Antho2422** [comment]
[phy.zip](https://github.com/SpikeInterface/spikeinterface/files/11653484/phy.zip)

Sure thank you ! Here it is

**Comment by zm711** [comment]
@alejoe91 sorry if you're already testing a solution.

I believe the issue is here: 
https://github.com/SpikeInterface/spikeinterface/blob/11a22b7728f0604778659f7536728f155cc433d6/src/spikeinterface/extractors/phykilosortextractors.py#L126-L128

When `Phy` splits a cluster it just copies the whole row into the tsv file preserving all columns except the `cluster_id` column. So that would mean two rows have the same `si_unit_id`.  Since the check only make sure that there isn't a `nan` it loads the old same value for both new clusters.  One solution that I was testing a bit locally could be:

```python

  if np.count_nonzero(cluster_info["si_unit_id"].values==si_id)!=1:

``` 

as a check instead. So if this comes up 0 it indicates a nan. If it comes up two then that means there was a duplicate. In which case you give a brand new SI number. The only question I would have before opening a pull request is that doing this conditional would basically follow Phy logic of always increasing instead of reusing numbers. A more complicated fix could be implemented to reuse a value though.

**Comment by zm711** [comment]
@Antho2422, realized I never tagged you to let you know this has been updated. (You may need to install from source to get this update or wait for the next release). 

Feel free to open a new issue if something else comes up!

**Comment by Antho2422** [comment]
@zm711 thank you ! 

I will update that soon thanks !
