### ISSUE TITLE
Cut or change the value in part of a recording

### ISSUE THREAD

**Issue by farazmoradi** [SpikeInterface/spikeinterface#1699]
Hi,

I have a very bad noise for 2 minutes in my recording. Is it possible to remove or replace all the values with zero in a prt of binaryrecordingextractor object?

**Comment by alejoe91** [comment]
Hi @farazmoradi 

You can use the tools we have for manipulating recordings: https://spikeinterface.readthedocs.io/en/latest/modules/core.html#manipulating-objects-slicing-aggregating

Let's assume you have a 10 min recording and noise between minutes 3-5:
```
rec_original = si.read_binary(...)
fs = rec_original.sampling_frequency

# cutout first part of good recording (0 to 180s)
rec_first = rec_original.frame_slice(start_frame=0, end_frame=int(180 * fs))
# cutout second part (300 to end)
rec_second = rec_original.frame_slice(start_frame=int(180 * fs), end_frame=rec_original.get_num_samples())

# concatenate
rec_concat = si.concatenate_recordings([rec_first, rec_first])
print(rec_concat)
```

Now `rec_concat` should be an 8min recording only with the clean signal. Make sure you take into account this "artificial" cut after spike sorting to properly align the spike trains to other signals (e.g. behavior, etc)

**Comment by farazmoradi** [comment]
Thanks a lot!
