### ISSUE TITLE
Spike sorting with a channel/probe map in 3D instead of 2D?

### ISSUE THREAD

**Issue by Kayv-cmb** [SpikeInterface/spikeinterface#1727]
Hi all,

This is more or less questions and asking for advice, I don't know if this is the right place to ask. Feel free to close it if you have no answer to that.
I am working on a custom probe that got a 3D spatial configuration to record at different place. Which also mean that my probe is not linear, leading me to those question : 

- Is spikeinterface limited to 2D probe map for spikesorting ? 
For now I project the position of the recording site in 2D with MDS to perform spikesorting, but I am afraid that I loose information by doing that. Do you have any idea, if there is a better solution ?

- Compared to linear probe would the fact that the probe is not linear pose a problem in the spikesorting result ? 

If spikeinterface is not limited to 2D: 
- how can I use spikeinterface with a 3D probe/channel map (I think probe interface is able to create a probe in 3D) ? and which sorter can I use with a 3D channel/probe map ?

If spikeinterface is limited to 2D : 
- Is it possible to modify a sorter to enable 3D channel map? and do you have any advice on how I can do that ?

Hoping that you would answer to my questions. Thank you in advance !!

**Comment by samuelgarcia** [comment]
Hi Kayvan,
spikeinterface is based on probeinterface for probe handling.
Probeinterface handle 3d probes. You should find it in the doc https://probeinterface.readthedocs.io/en/main/examples/ex_02_probe_2d_probe_3d.html
The 3D handling is not 100% for intance, we do not at the moment handle the "volume" of the 3D probe even if we handle the 2D shape of 2d probe.

spikeinterface depending on probeinterface also have 3D probe handling so.
The channel location shape will be (n, 3) instead of (n, 2).
The main limitation is that most of soters do not handle 3d probes!
And also, internally to spikeinterface, many plotting and postprocessing that need the channel location will rely on 2D arrays. On spikeinterface side we can enhance this on demand piece by piece. The design was do with 3D array in mind.
But for the sorter this will depend on sorter developer!
Note that we are in a process of having sorters internal to spikeinterface. For thoses one the 3D handling should be more easy.

**Comment by Kayv-cmb** [comment]
Hi @samuelgarcia, 
Thank you, for the explanation. Unfortunately the configuration of the recording site of the probe I am working is in a 'Volume'. From your explanation I think that spikesorting using the 3D volumes coordinates of channel location will not be possible for now, I will be quite happy to test when the process of having internal sorter to spikeinterface is over.
Do you happen to know which sorter that can handle the "volumes" on 3D channel location ? 
If not the issue can be close, I will keep using MDS to project my channel location in 2D.

**Comment by Kayv-cmb** [comment]
Hey, 

This is a question to follow up my previous one.
I tried different sorter to see if they would work with the 3D coordinates (x,y,z) for the channel positions, and I am able to spikesort using Mountainsort4 however when I tried to extract the waveform I got the issue :
`Traceback (most recent call last):
  File "/nemo/lab/schaefera/working/combadk/ScriptKC/CHIME_script/CHIME_sorting3D.py", line 75, in <module>
    we_all = si.extract_waveforms(rec, sorting_MS, folder = this_output_folder,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 1446, in extract_waveforms
    we = WaveformExtractor.create(recording, sorting, folder, mode=mode, use_relative_path=use_relative_path,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 291, in create
    if recording.get_probegroup() is not None:
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py", line 221, in get_probegroup
    probe.set_contacts(positions=positions,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/probeinterface/probe.py", line 177, in set_contacts
    raise ValueError('you need to give plane_axes')
ValueError: you need to give plane_axes`

Is this issue solveable or should I not used spiekinterface to extract waveform and quality metrics?

Thank you so much in advance for helping me !!

**Comment by alejoe91** [comment]
Hi @Kayv-cmb 

How did you set 3D locations? Did you generate a `probeinterface.Probe`? The problem that you are seeing is due to the fact that the contacts are in 3D, but the "direction" that they face is not defined. When instantiating the probe in the first place, you should pass the `plane_axes` info when setting the contacts, see `set_contacts` here: https://probeinterface.readthedocs.io/en/main/api.html#module-probeinterface

**Comment by Kayv-cmb** [comment]
Hi, I just setted the channel position like this 
`' recording.set_channel_locations(positions) '`
So I didn't really set any probe, I tried to set a probe with probeinterface like this
```

probe = Probe(ndim = 3, si_units='um')
probe.set_contacts(positions=positions, shapes='circle', shape_params={'radius': 8}, plane_axes ='xy')
probe.set_device_channel_indices(np.arange(positions.shape[0]))
recording = recording.remove_channels(remove_channel_ids=missing_numbers)
recording.set_probe(probe)
```
But when I tried to set it like this I have this error : 
```

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 9
      7 # removing channel that got higher noise level
      8 recording = recording.remove_channels(remove_channel_ids=missing_numbers)
----> 9 recording.set_probe(probe)

File ~/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py:74, in BaseRecordingSnippets.set_probe(self, probe, group_mode, in_place)
     72 probegroup = ProbeGroup()
     73 probegroup.add_probe(probe)
---> 74 return self.set_probes(probegroup, group_mode=group_mode, in_place=in_place)

File ~/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py:127, in BaseRecordingSnippets.set_probes(self, probe_or_probegroup, group_mode, in_place)
    123 assert all(probe.device_channel_indices is not None for probe in probegroup.probes), \
    124     'Probe must have device_channel_indices'
    126 # this is a vector with complex fileds (dataframe like) that handle all contact attr
--> 127 arr = probegroup.to_numpy(complete=True)
    129 # keep only connected contact ( != -1)
    130 keep = arr['device_channel_indices'] >= 0

File ~/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/probeinterface/probegroup.py:62, in ProbeGroup.to_numpy(self, complete)
     60 fields = []
     61 for probe_index, probe in enumerate(self.probes):
---> 62     arr = probe.to_numpy(complete=complete)
     63     probe_arr.append(arr)
     64     for k in arr.dtype.fields:

File ~/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/probeinterface/probe.py:714, in Probe.to_numpy(self, complete)
    712 for i in range(self.ndim):
    713     dim = ['x', 'y', 'z'][i]
--> 714     arr[f'plane_axis_{dim}_0'] = self.contact_plane_axes[:, 0, i]
    715     arr[f'plane_axis_{dim}_1'] = self.contact_plane_axes[:, 1, i]
    717 if self.device_channel_indices is None:

IndexError: too many indices for array: array is 0-dimensional, but 3 were indexed

```

**Comment by alejoe91** [comment]
I see, `plane_axes` should be an array of dimensions: `(num_elec, 2, ndim)` (in your case `(num_elec, 2, 3)`). (we should improve the docs!)
This is because in case of square or rect electrodes, it also allows you to define their orientation.

Can you try the following?
```
probe = Probe(ndim = 3, si_units='um')
plane_axes_xy = np.zeros((len(positions), 2, 3))
# xy axis will be:
plane_axes_xy[:, 0, 0] = 1
plane_axes_xy[:, 1, 1] = 1

probe.set_contacts(positions=positions, shapes='circle', shape_params={'radius': 8}, plane_axes=plane_axes_xy)
probe.set_device_channel_indices(np.arange(positions.shape[0]))
recording = recording.remove_channels(remove_channel_ids=missing_numbers)
recording.set_probe(probe)
```

**Comment by Kayv-cmb** [comment]
I see, thanks a lot it seems I am able to create the probe now. I misunderstood the documentation I though I had to indicate the plane of contact which in my case would be 'xy'. I will check the extraction of the waveform to see if it work.

Thanks

**Comment by Kayv-cmb** [comment]
Hi @alejoe91 

It doesn't seem to work, I still have the same issue. Here is my script 
```

from chimpy import Experiment, Recording, Ct_wire
from chimpy.utils import find_missing_numbers
from tqdm import trange
import numpy as np
import pandas as pd
from chimpy import extractor
from spikeinterface.preprocessing import common_reference,bandpass_filter
import os
import spikeinterface as si
import spikeinterface.extractors as se 
import spikeinterface.sorters as ss
from spikeinterface.exporters import export_to_phy
import spikeinterface.widgets as sw
import spikeinterface.preprocessing as spre
from probeinterface import Probe
import sys
if __name__ == '__main__':

    directory = "/nemo/lab/schaefera/working/raw_data/raw_CHIME/CHIME_220923_B"
    #exp = Experiment("../../../raw_data/raw_CHIME/CHIME_220923_B")
    dic = ("https://webknossos.crick.ac.uk/annotations/63ef8d32010000aa00415d1c","3yFZzUyniPhbB8rYYotP9A",'log',None)
    exp = Experiment(directory, ct= dic)
    #brain = exp.select_brain_recording(selection=-1)
    recording = extractor.read_chime(exp)
    num_channel = recording.get_num_channels()
    tip_min_um = exp.ct.tip_min*exp.ct.voxel[0]

    positions,bad_channel,df_min_noises = exp.channel_map(exp.wire_map,tip_min_um)
    missing_numbers = find_missing_numbers(df_min_noises['index_pixels'],num_channel)

    #positions,bad_channel = exp.channel_map(exp.wire_map,exp.ct.tip_min)
    # Creation of a custom prob linked to the channel map
    if positions.shape[1]==3:
        probe = Probe(ndim = 3, si_units='um')
        # Setting the position of the probes
        plane_axes_xy = np.zeros((len(positions), 2, 3))
        # xy axis will be:
        plane_axes_xy[:, 0, 0] = 1
        plane_axes_xy[:, 1, 1] = 1
        probe.set_contacts(positions=positions, shapes='circle', shape_params={'radius': 8}, plane_axes =plane_axes_xy)
        #probe.set_global_device_channel_indices(np.arrange(position.shape[0]))
        probe.set_device_channel_indices(np.arange(positions.shape[0]))
    # removing channel that got higher noise level
    recording = recording.remove_channels(remove_channel_ids=missing_numbers)
    recording.set_probe(probe)

    #recording = recording.remove_channels(remove_channel_ids=bad_channel['index_pixels'])
    # setting the channel location
    recording.set_channel_locations(positions)
    #recording_cmr = common_reference(recording)
    ss.Kilosort3Sorter.set_kilosort3_path('/camp/home/combadk/working/combadk/Kilosort/')
    rec = recording
    #rec: si.BaseRecording = spre.whiten(recording, dtype='float32')
    rec.annotate(is_filtered=True)
    ss.installed_sorters()
    #recording = recording.remove_channels(remove_channel_ids=7)
    #w = sw.plot_timeseries(recording, backend="ipywidgets")
    #recording_f = bandpass_filter(recording, freq_min=300, freq_max=8000) #Band pass filtering
    #w = sw.plot_timeseries(recording_f, backend="ipywidgets")
    sorter_name = ['mountainsort4']

    if 'mountainsort4' in sorter_name:
            default_MS = ss.Mountainsort4Sorter.default_params()
            default_MS['num_workers'] = 4
            default_MS['detect_threshold'] = 4
            default_MS['adjacency_radius'] = 150
            default_MS['filter'] = False 

            directory_output= directory+'/Mountainsort4_3D_with_probe/'

            this_output_folder = os.path.join(directory_output, 'results_MS')
            sorting_MS = ss.run_mountainsort4(rec,
                                                output_folder = this_output_folder,
                                                verbose = True, **default_MS,)
            #ED added use of os.path.join
            this_output_folder = os.path.join(directory_output,'wf_MS')
            we_all = si.extract_waveforms(rec, sorting_MS, folder = this_output_folder, 
                                        max_spikes_per_unit = 500, progress_bar = True, chunk_duration = '1s', n_jobs=10)
            #ED added use of os.path.join
            this_output_folder = os.path.join(directory_output,'phy_MS')
            export_to_phy(we_all, output_folder = this_output_folder,
                                progress_bar = True, chunk_duration = '1s', n_jobs=10, copy_binary=False)

            #distance = quality_metrics.distance_matrix(exp, dim= 3, probe_map = positions)
            metrics = quality_metrics.compute_metrics(we_all)
            metrics = quality_metrics.compute_metrics(we_all)
            filepath = Path(directory_output+f'metrics_MS4_3D.csv')  
            filepath.parent.mkdir(parents=True, exist_ok=True)  
            metrics.to_csv(filepath)
```

From I understand even I set the probe it's still create a dummy one (see below) : 
```

Preparing output...
Done with ms4alg.
/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py:217: UserWarning: There is no Probe attached to this recording. Creating a dummy one with contact positions
  warn(
Cleaning tempdir::::: /tmp/tmpi4g0kv9x
mountainsort4 run time 1326.95s
Traceback (most recent call last):
  File "/nemo/lab/schaefera/working/combadk/ScriptKC/CHIME_script/CHIME_sorting3D.py", line 79, in <module>
    we_all = si.extract_waveforms(rec, sorting_MS, folder = this_output_folder,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 1446, in extract_waveforms
    we = WaveformExtractor.create(recording, sorting, folder, mode=mode, use_relative_path=use_relative_path,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/waveform_extractor.py", line 291, in create
    if recording.get_probegroup() is not None:
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/baserecordingsnippets.py", line 221, in get_probegroup
    probe.set_contacts(positions=positions,
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/probeinterface/probe.py", line 177, in set_contacts
    raise ValueError('you need to give plane_axes')
ValueError: you need to give plane_axes
```

Also if I don't specify    ' recording.set_channel_locations(positions)' the spikesorting with mountainsort has an issue which is : 

``` 
Traceback (most recent call last):
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 226, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/sorters/external/mountainsort4.py", line 133, in _run_from_folder
    old_api_sorting = mountainsort4.mountainsort4(**ms4_params)
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/mountainsort4/mountainsort4.py", line 22, in mountainsort4
    geom = _get_geom_from_recording(recording)
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/mountainsort4/mountainsort4.py", line 62, in _get_geom_from_recording
    location0 = recording.get_channel_property(channel_ids[0], 'location')
  File "/camp/home/combadk/.conda/envs/CHIME_kayvan/lib/python3.9/site-packages/spikeinterface/core/old_api_utils.py", line 46, in get_channel_property
    v = values[ind[0]]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by alejoe91** [comment]
Oups! You have to do:
`recording = recording.set_probe(probe)`

**Comment by Kayv-cmb** [comment]
Oups!! It is solved, currently extracting the waveform, thanks a lot for the help
