### ISSUE TITLE
Support for serializing recordings with relative paths during sorting run

### ISSUE THREAD

**Issue by miketrumpis** [SpikeInterface/spikeinterface#1739]
I've noticed that the underlying support for relative paths in the JSON dump & load operators is never exposed at the level of `spikeinterface.sorters.basesorter.BaseSorter`.

Made a PR to address this #1737. I wasn't able to do a simple `python -m pytest ./src/spikeinterface` (lots of `ImportError`s). This is informally tested, and everything was round-tripped correctly.

The kwarg exposure is limited to propagating the changes up to `run_sorter_local`, but I didn't touch the container logic stuff (yet).

**Comment by h-mayorquin** [comment]
Curios, why are you running pytest like that? and what kind of import errors are you getting?

This work just fine for me:
```
python -m pytest ./src/spikeinterface
```
At first glance.

This PR might be a good idea but I am not sure about this use case. Can you elaborate a bit more on why this is a good idea?

We have had a lot of changes concerning relative paths recently. @alejoe91 Is it necessary to expose this in  the general API?

That is, could relative paths just be the default behavior. It should work in the most common case when used for caching (as the path does not mater) as well as work when people move the folder / directory where the sorter was located.

**Comment by miketrumpis** [comment]
Dunno about the pytest. I was able to do `python -m pytest --pyargs spikeinterface` after an install, but had some git annex version problem.

Yeah a good use case would be running things in a container and then using the SpikeInterface products outside the container (or in a different one). Without a relative path option, you would have to bind your host volume to the container volume with the exact same absolute path.

**Comment by h-mayorquin** [comment]
Thanks for explaining, it is good to have this things described on the issues. We don't have exhaustive testing for many of our uses cases so it is important that we at least leave a written trail of why the decisions were made in the way that they were for future users and mantainers. That said, I don't have the necessary expertise to judge if there is a simpler way of achieving this. @alejoe91 has recently been working on some similar ssues regarding containers so he probably can tell better:

https://github.com/SpikeInterface/spikeinterface/pull/1698

Concerning the import problems, I still don't understand. Do you run things in an environment? Usually tests should run fine if in a dedicated environment by just running pytest in the root folder of the project. I am interested here in the package angle, maybe the imports are related to something else that we could improve. How do you install spikeinterface?

**Comment by miketrumpis** [comment]
If I set up a bare venv and do this

```bash
$ git clone https://github.com/SpikeInterface/spikeinterface.git
$ pip install ./spikeinterface[test]
$ python -m pytest spikeinterface/src/spikeinterface
```

I get a series of import errors like this

```
========================================================== test session starts ==========================================================
platform linux -- Python 3.9.13, pytest-7.3.2, pluggy-1.2.0
rootdir: /home/mtrumpis/spikeinterface
configfile: pyproject.toml
plugins: cov-4.1.0
collected 419 items / 38 errors                                                                                                         

================================================================ ERRORS =================================================================
___________________________ ERROR collecting src/spikeinterface/extractors/tests/test_cbin_ibl_extractors.py ____________________________
ImportError while importing test module '/home/mtrumpis/spikeinterface/src/spikeinterface/extractors/tests/test_cbin_ibl_extractors.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
spikeinterface/src/spikeinterface/extractors/tests/test_cbin_ibl_extractors.py:8: in <module>
    from spikeinterface.extractors.tests.common_tests import RecordingCommonTestSuite, SortingCommonTestSuite
E   ModuleNotFoundError: No module named 'spikeinterface.extractors.tests'
```

**Comment by h-mayorquin** [comment]
Ok, sow hat is hapening there is the following:

You are installing spikeinterface to site-packages (`pip install ./spikeinterface[test]`) and then you are trying to test the version on the directory that you just downloaded ( `python -m pytest spikeinterface/src/spikeinterface`, However, we exclude all the test files from the distribution:

https://github.com/SpikeInterface/spikeinterface/blob/6c9ca96e1916b031927fc301303040e32d565bbd/pyproject.toml#L41-L45

That means, that the package `spikeinterface.extractors.tests.common_tests` is not available in site-packages and hence you import error.

If this is for local dev you should be using an editable install, the following should work:

```
$ git clone https://github.com/SpikeInterface/spikeinterface.git
$ pip install -e ./spikeinterface[test]
$ python -m pytest spikeinterface/src/spikeinterface
```

But maybe this is not for local dev, what is your use case?

As a side comment and out of curiosity: I find it odd that you are calling pytest from the parent of the folder with spikeinterface source. It is my experience that most people just run pytest from the root directory and this is what we advice on the documentation:

https://spikeinterface.readthedocs.io/en/latest/development/development.html#how-to-run-tests-locally

Is there a reason you prefer to work like this? 
Trying to learn something here.

**Comment by miketrumpis** [comment]
I assure you I do not understand the guts of pytest. But in my experience running it like `python -m pytest root/of/tests` will discover tests under that path. *I believe* that is regardless of whether the package is **also** in `site-packages`. I did the pip install step just to cover spikeinterface dependencies in the bare venv.

**Comment by alejoe91** [comment]
Correct, but the import assumes you have a local install since it attempts to load a testing function from the `tests` folder. But these folders are not copied over to the site-packages.

So you need to install with `-e` to run tests! ;)
