### ISSUE TITLE
Widgets Examples Are Mis-spaced

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#1817]
After merging #1807 it looks like the examples are all still running fine, but there is one overall issue that I keep meaning to bring up. Some of the example figures aren't spaced correctly (ie looks like a plt.tight_layout() should be included somewhere or manual spacing should be added). I'll try to look into this if I get the bandwidth, but I just want to keep this on your radar (since I don't know yet if this an a pure documentation issue or a change that should actually be fixed in the `Widgets` module.

https://spikeinterface.readthedocs.io/en/latest/modules_gallery/widgets/plot_3_waveforms_gallery.html

**Comment by alejoe91** [comment]
Thanks @zm711 

@samuelgarcia and I are planning a refactoring of the widgets module next week. We'll keep this in mind and try to adjust the layout as much as possible from default params! :)

**Comment by h-mayorquin** [comment]
Was this addressed by https://github.com/SpikeInterface/spikeinterface/pull/1859?

**Comment by alejoe91** [comment]
Unfortunately not. That was just a pure refactor ;)

**Comment by samuelgarcia** [comment]
Now the refactoring is done we can start to improve the widgets module!

**Comment by zm711** [comment]
I think the widgets will go to the back burner while working on `SortingResult`, so is there any reason why I shouldn't just add `figsize` to each widget example (I don't think it would hurt RTD, but maybe RTD will display it weird--I would just have to try and see). For example, the current examples looks like:

```python
sw.plot_unit_waveforms(we, unit_ids=unit_ids,)
```

![image](https://github.com/SpikeInterface/spikeinterface/assets/92116279/fc9f437a-18e9-4101-b555-0d96e36d5aa1)

but if I add in the `figsize` argument:
```python
sw.plot_unit_waveforms(we, unit_ids=unit_ids, figsize=(12,4))
```
![image](https://github.com/SpikeInterface/spikeinterface/assets/92116279/677d4c11-8229-48f4-b8c2-3bd3d743ddee)

Not quite perfect, but I think that will make the examples look better in the mean time, no?

**Comment by alejoe91** [comment]
That sounds like the perfect solution given the expected SortingResult revolution :)

**Comment by zm711** [comment]
Done in #2407 :)
