### ISSUE TITLE
Merge results of two or more spike sorters on the same data

### ISSUE THREAD

**Issue by rat-h** [SpikeInterface/spikeinterface#1822]
I have a recording and I ran multiple sorters on the same data. After running validation and curation, I wonder whether it possible to merge results of several sorters to get a better sorting result. 

For a single sorting result it is possible to run [`get_potential_auto_merge`](https://spikeinterface.readthedocs.io/en/latest/api.html?highlight=merge#spikeinterface.curation.get_potential_auto_merge) and then [`MergeUnitsSorting`](https://spikeinterface.readthedocs.io/en/latest/api.html?highlight=merge#spikeinterface.curation.MergeUnitsSorting) as shown [Automatic curation tools](https://spikeinterface.readthedocs.io/en/latest/modules/curation.html?highlight=get_potential_auto_merge#automatic-curation-tools). However, cited [`Lussac`](https://www.biorxiv.org/content/10.1101/2022.02.08.479192v1) was developed to merge results of different sorters or the same sorter but with different parameter to detect simple and complex spikes in Purkinje cells. So it shouldn't be already implemented, I guess, but I couldn't find any instructions on how to do so in the latest documentation.

Is it possible to do something like that?
```python
recording = si.load_extractor("preprocessed")
sr1 = si.load_extractor(sorting1")
we1 = si.WaveformExtractor.load_from_folder(waveforms1')
sr2 = si.load_extractor(sorting2")
we2 = si.WaveformExtractor.load_from_folder(waveforms2')

new_sr = Merge(sr1,sr2)
new_we = Merge(we1,we2) 
```

**Comment by samuelgarcia** [comment]
@DradeAW the lussac author is your friend!

spikeinterface do not have sofisticated internal machinery to merge sorting from differents sorters. lussac do.
We a agreement sorting which select units detected by multiple sorters but this is not what you want I think lussac will do a better job.

**Comment by DradeAW** [comment]
Hi @rat-h,

As @samuelgarcia pointed, this is exactly what I've been working on for the last 2 years!
The result of this work is my algorithm lussac (https://github.com/BarbourLab/lussac), with the v2 going live early next week if everything is going according to plan!

Merging multiple sortings is not as easy as it first looks like, but we can talk via email or vocal if you want :)

**Comment by rat-h** [comment]
Hi @DradeAW, hi @samuelgarcia,
Thank you for the clarifications! Now it is obvious I have to learn `lussac` :smile: .
Let me look and try it first. @DradeAW, how can I contact you if needed? My contact rth(at)r-a-r.org or rath(at)gwu.edu. Feel free to shut me a message.
