### ISSUE TITLE
Loading sync channel using read_openephys

### ISSUE THREAD

**Issue by neuronzoo** [SpikeInterface/spikeinterface#1826]
Hey guys, appreciate all of your terrific work!
I am using OE to record NPX and also save the sync channel - #385. I am trying to load the sync channel using read_openephys (in spikeinterface.extractors). When I use:
`new_recording = se.read_openephys(path_to_recording_file, stream_name="Record Node 101#Neuropix-PXI-100.ProbeA-AP", load_sync_channel=True)` 
I get the following error: "set_probe(inplace=True) must have all channel indices"

**Comment by samuelgarcia** [comment]
Hi @neuronzoo.
thank you for reporting this.
Indeed this is a bug when we have the sync channel it is not possible to load the probe because the channel count is N+1.
@alejoe91 can you fix this like we do in spikeglx ?

**Comment by alejoe91** [comment]
Yep, I can tackle this today
