### ISSUE TITLE
Warning with numba 0.57.1

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#1833]
/home/pierre/github/spikeinterface/src/spikeinterface/sortingcomponents/clustering/sliding_nn.py:370: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(fastmath=True, cache=True)

**Comment by DradeAW** [comment]
#1836 should have solved this. Can you check @yger please ?
