### ISSUE TITLE
Faster sorting using parallel computation with Mountainsort5

### ISSUE THREAD

**Issue by Zeinab-Mohammadi** [SpikeInterface/spikeinterface#1846]
Hi

I am sorting Neuropixels data using Mountainsort5 with the below code. 

`sorting_ms5 = ss.run_sorter("mountainsort5", sub_recording, output_folder="mountainsort5_output", detect_threshold=10, remove_existing_folder=True, raise_error=True)`

But the code runs slow. I am working with a cluster, so it would be great if we could have parallel jobs. I tried adding `n_jobs=4`, but I got an error showing it is not the true way.
`sorting_ms5 = ss.run_sorter("mountainsort5", sub_recording, output_folder="mountainsort5_output", detect_threshold=10, remove_existing_folder=True, raise_error=True, **dict(n_jobs=4))
`

**Comment by alejoe91** [comment]
Hi,

Please read the README of `mountainsort5` here: https://github.com/flatironinstitute/mountainsort5

By default, MS5 already uses scheme 2 which should be faster. I don't think you can make it faster than that.
