### ISSUE TITLE
Handling long recordings for spike sorting with limited memory

### ISSUE THREAD

**Issue by Elvisambition** [SpikeInterface/spikeinterface#1868]
I am working on spike sorting for long extracellular recordings (e.g. 300 sec at 20kHz sampling rate). When I try to process the whole recording at once, my system runs out of memory even with 64GB RAM.

Could you please advise on the best practices for handling long recordings with limited memory for spike sorting? Specifically:

- Is it feasible to split the long recording into smaller chunks (e.g. 10 chunks of 30 sec each), run spike sorting on each chunk separately, and then combine the results?
- If so, how small can each chunk be without compromising the spike sorting performance? Are there any minimum requirements on the spike count per chunk?

**Comment by h-mayorquin** [comment]
Hi, @Elvisambition. Good to get you question, to help you better some information would be useful.

1) Which recording are you suing, can you print(recorder)?
2) Which processing are you doing that makes you run out of memory? Can you share your script with us?
3) Also, which OS are you using and how much ram memory you have?

Forst most cmoputational heavy processing we have a way of dealing with chunking and the the defaults should run fine without causing memory issues. But maybe there is a bug or you are doing some processing where we don't support chunkg (yet) so we need more details.

**Comment by samuelgarcia** [comment]
@Elvisambition 
In spikeiterface Recording are not loaded in memory!!

Normally spikeinterface handle itself the chunking. There is no need to force it a the file level.

Depending the algo you use (kilosort, mountainsort5, ...) you can have diffrent RAM usage.
Some sorters accumulate waveforms in memory for instance and this can be be quite big.

In short you should not chunk your files. 300 sec is not so long. So user have > 24 hours recordings!

**Comment by Elvisambition** [comment]
@samuelgarcia @h-mayorquin 
Thank you for the helpful response. I realized my original question didn't provide enough details. The memory overflow actually happens during the spike sorting stage rather than data loading.

The data I'm using is collected from ```Intan RHX``` software. I manually set the channel locations as ```[[i] for i in range(num_channels)]```. For spike sorting, I'm using the ```MountainSort5``` algorithm.

I found that running sorting on the full recording causes errors, but it works when I divide the data into smaller chunks and process them separately.

I apologize if these are naive questions, as I'm quite new to this field.

My main question is - how can I configure things to avoid memory overflow when using MountainSort5 for spike sorting? Are there any settings or approaches you'd recommend so that it can handle the full dataset?

**Comment by alejoe91** [comment]
Can you paste the full script and the full error you're getting?

Maybe the error is in MS5, not spikeinterface!

**Comment by Elvisambition** [comment]
```
import spikeinterface as si
import spikeinterface.extractors as se
from spikeinterface.extractors.neoextractors import IntanRecordingExtractor

import matplotlib.pyplot as plt

extractor = IntanRecordingExtractor('./test_230721_165157.rhd')

import mountainsort5 as ms5
import spikeinterface.preprocessing as spre


# %%
recording = extractor.set_channel_locations([[i,i] for i in range(218)])

# %%
recording_filtered = spre.bandpass_filter(extractor, freq_min=300, freq_max=6000)

# %%
recording_preprocessed: si.BaseRecording = spre.whiten(recording_filtered, dtype='float32')

# %%
recording_preprocessed._main_ids

# %%
ms5.Scheme1SortingParameters()

# %%
sorting = ms5.sorting_scheme1(recording_preprocessed,sorting_parameters=ms5.Scheme1SortingParameters())
```

**Comment by Elvisambition** [comment]
An error will occur due to insufficient memory when it runs to the last line.

**Comment by alejoe91** [comment]
Ok, then I would open an issue in the Mountainsort5 repo

**Comment by Elvisambition** [comment]
@samuelgarcia @h-mayorquin @alejoe91 
Thank you for your answers, I have upgraded the server's memory to 192GB, and the issue is now resolved.

**Comment by alejoe91** [comment]
Brute force approach ;) Closing the issue then!

**Comment by h-mayorquin** [comment]
DAMN!
