### ISSUE TITLE
Typo in quality metrics.pca_metrics.py

### ISSUE THREAD

**Issue by maxjuv** [SpikeInterface/spikeinterface#1894]
Hi,
There is a typo in the term 'score':
quality metrics.pca_metrics.py, line 970  `pc_metrics["silhouette_full"] = unit_silhouette_socre` 
should be  `pc_metrics["silhouette_full"] = unit_silhouette_score`

Best
Maxime

**Comment by zm711** [comment]
Thanks Maxime (@maxjuv )! That was absolutely my typo when I plugged the function into the metrics. I put in a PR to fix. Thanks for catching that.
