### ISSUE TITLE
Estimate on new version?

### ISSUE THREAD

**Issue by aboharbf** [SpikeInterface/spikeinterface#190]
I'm considering setting up spikeInterface but I'd rather not set it up right as the new version is coming out. the estimate for the new update is 'summer 2021' - is there any more granular estimate available? Thanks for all the work you guys do.

**Comment by samuelgarcia** [comment]
Consider a release in 2 weeks.
The source are very near the future release, we will work mainly on doc + bug fix now.

**Comment by aboharbf** [comment]
Excellent, thank you for the information
