### ISSUE TITLE
Kilosort3 container issue

### ISSUE THREAD

**Issue by ghost** [SpikeInterface/spikeinterface#1900]
Hi,

I'm trying to get kilosort3 to run inside a singularity container. I'm running it on a cluster gpu node with a rtx2080ti gpu. I can get pykilosort to work in a container just fine, but would like to run kilosort3 as this is the latest version. I've tried installing a number of different versions of spikeinterface locally and inside the container, from 0.97.1 up to the latest version, but all of them give the following index error:

`
"Warning: X does not support locale C.UTF-8",
        "Time   0s. Computing whitening matrix..",
        "Getting channel whitening matrix...",
        "Channel-whitening matrix computed.",
        "Time   6s. Loading raw data and applying filters...",
        "Time   8s. Finished preprocessing 220 batches.",
        "Drift correction ENABLED",
        "vertical pitch size is 1.000000e+01",
        "horizontal pitch size is 5",
        "Columns 1 through 7",
        "",
        "-10.0000   -7.5000   -5.0000   -2.5000         0    2.5000    5.0000",
        "",
        "Columns 8 through 9",
        "",
        "7.5000   10.0000",
        "",
        "6",
        "",
        "----------------------------------------Index in position 1 exceeds array bounds. Index must not exceed 4."
`

Does anyone have any idea why this is happening and what I could do to fix it?

Thanks!

**Comment by alejoe91** [comment]
HI @rbedfordwork 

Unfortunately it seems to be related to KS3 specifically. 
Can you try to upgrade SpikeInterface to 0.98.2? 
Also, are you abel to run KS2.5?

Cheers
Alessio

**Comment by rbedfordwork** [comment]
Yes I've tried both KS3 and KS2.5 with SpikeInterface 0.98.2, and both return the exact same index error.

**Comment by samuelgarcia** [comment]
Hi. The error is a matlab error and not a spikeinterface error. SO it will be hard to fix this in our side.
As Alessio mention this error is data driven for a situtaion not handled so other dataset should be OK.

**Comment by zm711** [comment]
@samuelgarcia, seems like the user deleted their account. You want this issue to be open for others or okay to close?

**Comment by alejoe91** [comment]
I would say OK to close! Thanks for checking @zm711
