### ISSUE TITLE
Unexpected keyword 'radius_um' in Neuropixel Guide

### ISSUE THREAD

**Issue by nmtimme** [SpikeInterface/spikeinterface#1907]
Hello

I'm trying to go through the guide to using spike interface to spike sort neuropixel data (https://spikeinterface.readthedocs.io/en/latest/how_to/analyse_neuropixels.html), but I'm running into an error with detect_peaks. Thank you for quickly addressing my issue with plot_traces  #1899 !

I'm running version 0.98.2 on a Linux cluster with a GPU. I'm running on a virtual desktop, so I can view plots and interact with GUIs. I installed spikeinterface using miniconda 4.12.0 using this .yml file:

```
name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - mamba
  # numpy 1.22 break numba which break tridesclous
  - numpy<1.22
  # joblib 1.2 is breaking hdbscan
  - joblib=1.1
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - mpi4py
  - cxx-compiler
  - libxcb
  - pyqt=5
  - pyqtgraph
  - htop
  - ipywidgets
  - ipympl
  - pip:
    - ephyviewer
    - neo>=0.11
    - elephant>=0.10.0
    - probeinterface>=0.2.11
    - MEArec>=1.8
    - spikeinterface[full, widgets]
    - spikeinterface-gui
    - tridesclous>=1.6.6.1
    - spyking-circus>=1.1.0
    # - phy==2.0b5
```

I am running the following script when I encounter the error:

```
import spikeinterface.full as si
import spikeinterface.widgets as siw
print(si.__version__)

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Define the path to the data
base_folder = Path('/N/project/lapishLabWorkspace/NickPilotNeuropixelEphysData')
openephys_folder = base_folder / '2023-03-15_15-18-59'

# Figure out the data streams in this data set
stream_names, stream_ids = si.get_neo_streams('openephys', openephys_folder)
print('stream_names',stream_names)

# Read the data LFP data from probe A (this automatically loads the probe map)
raw_rec = si.read_openephys(openephys_folder, stream_name='Record Node 101#Neuropix-PXI-100.ProbeA-AP')
print('raw_rec',raw_rec)

# Plot the bottom part of the channel map
fig, ax = plt.subplots(figsize=(15, 10))
si.plot_probe_map(raw_rec, ax=ax, with_channel_ids=True)
ax.set_ylim(-100, 100)
# plt.show() # Uncomment to show plot

# High-pass filter the data
rec1 = si.highpass_filter(raw_rec, freq_min=300.)

# Identify bad channels and remove them
bad_channel_ids, channel_labels = si.detect_bad_channels(rec1)
rec2 = rec1.remove_channels(bad_channel_ids)
print('bad_channel_ids', bad_channel_ids)

# Phase shift the data to account for neuropixel sampling offset
rec3 = si.phase_shift(rec2)

# Common median reference the data
rec4 = si.common_reference(rec3, operator="median", reference="global")
rec = rec4
print('rec',rec)

# Look at the data across multiple steps of pre-processing (this doesn't seem to work)
# %matplotlib widget
# si.plot_timeseries({'filter':rec1, 'cmr': rec4}, backend='ipywidgets')

# Look at the rasters at various stages of preprocessing
fig, axs = plt.subplots(ncols=3, figsize=(20, 10))
si.plot_timeseries(rec1, backend='matplotlib',  clim=(-50, 50), ax=axs[0])
si.plot_timeseries(rec4, backend='matplotlib',  clim=(-50, 50), ax=axs[1])
si.plot_timeseries(rec, backend='matplotlib',  clim=(-50, 50), ax=axs[2])
for i, label in enumerate(('filter', 'cmr', 'final')):
    axs[i].set_title(label)
# plt.show() # Uncomment to show plot

# Look at some example traces
fig, ax = plt.subplots(figsize=(20, 10))
some_chans = rec.channel_ids[[100, 150, 200, ]]
si.plot_timeseries({'filter':rec1, 'cmr': rec4}, backend='matplotlib', mode='line', ax=ax, channel_ids=some_chans)
# plt.show() # Uncomment to show plot

# Save the preprocessed file
# job_kwargs = dict(n_jobs=40, chunk_duration='1s', progress_bar=True)
# rec = rec.save(folder=base_folder / 'preprocess', format='binary', **job_kwargs)

# Estimate the noise on the scaled traces (microV) or on the raw one (which is in our case int16).
noise_levels_microV = si.get_noise_levels(rec, return_scaled=True)
noise_levels_int16 = si.get_noise_levels(rec, return_scaled=False)
fig, ax = plt.subplots()
_ = ax.hist(noise_levels_microV, bins=np.arange(5, 30, 2.5))
ax.set_xlabel('noise  [microV]')
# Text(0.5, 0, 'noise  [microV]')
plt.show()

# Detect and localize peaks
from spikeinterface.sortingcomponents.peak_detection import detect_peaks
job_kwargs = dict(n_jobs=40, chunk_duration='1s', progress_bar=True)
peaks = detect_peaks(rec,  method='locally_exclusive', noise_levels=noise_levels_int16, detect_threshold=5, radius_um=50., **job_kwargs)
```

This is the output:

```
0.98.2
stream_names ['Record Node 101#Neuropix-PXI-100.ProbeA-AP', 'Record Node 101#Neuropix-PXI-100.ProbeA-LFP', 'Record Node 101#Neuropix-PXI-100.ProbeB-AP', 'Record Node 101#Neuropix-PXI-100.ProbeB-LFP']
raw_rec OpenEphysBinaryRecordingExtractor: 384 channels - 30.0kHz - 1 segments - 56,827,380 samples 
                                   1,894.25s (31.57 minutes) - int16 dtype - 40.65 GiB
bad_channel_ids ['AP192']
rec CommonReferenceRecording: 383 channels - 30.0kHz - 1 segments - 56,827,380 samples 
                          1,894.25s (31.57 minutes) - int16 dtype - 40.54 GiB
Traceback (most recent call last):
  File "/spikeInterfaceVer1/openEphysTest1.py", line 81, in <module>
    peaks = detect_peaks(rec,  method='locally_exclusive', noise_levels=noise_levels_int16, detect_threshold=5, radius_um=50., **job_kwargs)
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spikeinterface/sortingcomponents/peak_detection.py", line 91, in detect_peaks
    node0 = method_class(recording, **method_kwargs)
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spikeinterface/sortingcomponents/peak_detection.py", line 331, in __init__
    self.args = self.check_params(recording, **params)
TypeError: check_params() got an unexpected keyword argument 'radius_um'
```

I'd appreciate any advice you can provide on resolving this error. Thank you!

~Nick

**Comment by alejoe91** [comment]
Hi! That is strange because the `radius_um` is among the available params for the locally_ezclusive method! https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/sortingcomponents/peak_detection.py#L513

We'll take a look!

Fyi, we'll be off for a couple of weeks :)

**Comment by zm711** [comment]
@nmtimme (@alejoe91-enjoy the vacation), this terminology was updated in #1865. It use to be `local_radius_um`, but to harmonize all functions it was changed to `radius_um`. If you have a version of `SI` before this change that could explain the key word error. You could either install from source or try putting `local_radius_um` into the script until the next PyPI release.

**Comment by nmtimme** [comment]
Thank you @zm711 ! That worked! I'm running version 0.98.2, which was the most recent version, I thought. In any case, that resolved the problem.

**Comment by zm711** [comment]
@nmtimme, yep you have the most recent official version. The example, however, is based on the current development version `0.99.0.dev0` (ie you would need to install from source rather than use a pip install to be synced with the example file). Happy it worked, though!

**Comment by nmtimme** [comment]
Out of curiosity, why is the documentation based on the current development version and not the most recent official version? It seems like most people who are in need of the documentation would download the most recent official version, not the development version. Thanks!

**Comment by zm711** [comment]
That's a question for the core team, but I would say (and really just from my perspective not an official statement) that as a non-1.0 project there are so many possible changes (and no guarantees of backward compatibility (https://semver.org)) that it is better to keep the documentation up to date with the current version, so that compatibility changes going forward are not missed. I would say in general `SpikeInterface` does a great job of trying to keep backward compatibility (>90.0), but as a growing, constantly developing project some changes occur. The options would be to release a 98.2.1 or just wait (and package more changes) as either a 98.3 or a 99.0 release. You could get more clarification from the core devs on why they choose their particular strategy, but each package release requires effort and time away from writing and reviewing code.

As a bit more info I'm including the link the official installation instructions as well just for easy reach: https://spikeinterface.readthedocs.io/en/latest/installation.html. 

The official installation instructions discuss the process of installing from source during this heavy development phase to keep all docs and code in sync. I can say on the developer side doing code and documentation updates at the same time is easier (because no one likes going back to work on the docs if it isn't part of the code writing process). That being said, Alessio and Sam put in a lot of effort to make amazing docs in addition to all the other work for the project, so if you see anything unclear in the docs definitely raise an issue (or do a PR)!

Hopefully that helps a bit :)

**Comment by nmtimme** [comment]
Thank you for adding that context, @zm711 ! That all makes sense and I agree that the code is awesome!

**Comment by samuelgarcia** [comment]
Thank you @zm711 for helping issue during our super long vaccation.


(I prefer to not tell publically how long french vaccation can be...).
