### ISSUE TITLE
How to make json file in reading mda files

### ISSUE THREAD

**Issue by YinJiapeng** [SpikeInterface/spikeinterface#1913]
I am using **_**_spikeinterface.extractors.read_mda_recording_**_** to read *.mda files.

![20230809011438](https://github.com/SpikeInterface/spikeinterface/assets/32188312/8f48579c-c49e-4d4a-8ec1-05692989708f)

Now I have 2 questions:
1. I don't know how to get the params.json file. How to produce a params.json file for mda file processing?
​
2. Is there any example geom.csv file? So I can produce one geom file following the example.

Many thanks.

**Comment by alejoe91** [comment]
Hi @YinJiapeng 

Where did you get the `.mda` files? The `params.json` should be part of the folder. 

The only piece of information needed on the SpikeInterface side is the sampling frequency.

Here is a sample `params.json` that should work:

```
{"samplerate": 30000}
```

The `geom.csv` is is a comma separated text file with x, y position for each electrode, e.g.:
```
0, 0
0, 100
0, 200
0, 300
...
```

**Comment by li1901** [comment]
> Hi  你好@YinJiapeng
> 
> Where did you get the `.mda` files? The `params.json` should be part of the folder.您从哪里获取 `.mda` 文件？ `params.json` 应该是文件夹的一部分。
> 
> The only piece of information needed on the SpikeInterface side is the sampling frequency.SpikeInterface 端所需的唯一信息是采样频率。
> 
> Here is a sample `params.json` that should work:这是一个应该可以工作的示例 `params.json` ：
> 
> ```
> {"samplerate": 30000}
> ```
> 
> The `geom.csv` is is a comma separated text file with x, y position for each electrode, e.g.: `geom.csv` 是一个逗号分隔的文本文件，每个电极都有 x、y 位置，例如：
> 
> ```
> 0, 0
> 0, 100
> 0, 200
> 0, 300
> ...
> ```
That's awesome! But I have a question about more specific details. Electrodes typically have physical dimensions. How do you define the XY position between them? Do you use the center point of their geometric dimensions?What should be the distance unit in the document? Meters or micrometers?thanku so much

**Comment by alejoe91** [comment]
Generally, you would use the center of the electrode and express dimensions as um. Note that we use a separate package, [probeinterface](https://probeinterface.readthedocs.io/en/main/), to handle the probe. It has a much richer representation of the probe, so feel free to take a look and use it in your processing
