### ISSUE TITLE
Issue using plot_timeseries function with sortingview backend

### ISSUE THREAD

**Issue by josephchengyx** [SpikeInterface/spikeinterface#1918]
Hi, I'm trying to plot my own data using the 'plot_timeseries' function in the widgets module, and have it displayed in the web GUI generated by sortingview. However, when I try to call the function as such:

timeseries = sw.plot_timeseries(recording, backend='sortingview', mode='map')
(I get an assertion error if I call the function without the 'mode="map"' argument)

An empty plot is generated as shown: 
![Screenshot 2023-08-11 at 5 22 16 PM](https://github.com/SpikeInterface/spikeinterface/assets/59868375/7e26ab81-c52a-4d53-979a-15de8ce06833)

On the other hand, the data plots perfectly normally using the ipywidgets backend:

timeseries = sw.plot_timeseries(recording, backend='ipywidgets')
![Screenshot 2023-08-11 at 5 24 56 PM](https://github.com/SpikeInterface/spikeinterface/assets/59868375/01e321b4-8390-4497-bad0-d604496ba535)

Additionally, is there any function for plotting principal components that can also be displayed in the sortingview GUI?

Thanks for  the help!

**Comment by alejoe91** [comment]
Hi @josephchengyx 

The `map` mode is only available with multi-channel recordings. It seems that you only have a single channel, right? In that case, we should throw an error!
