### ISSUE TITLE
regarding isolation distance calculations

### ISSUE THREAD

**Issue by kshtjkumar** [SpikeInterface/spikeinterface#1927]
Hi I am trying to calculate isolation score for the tetrode recording but i am not sure if I am using this command correctly or not, can someone please help :

<img width="1056" alt="Screenshot 2023-08-21 at 4 00 25 AM" src="https://github.com/SpikeInterface/spikeinterface/assets/68465910/7a820d4d-a163-4c6c-9834-385129fb8a18">

**Comment by kshtjkumar** [comment]
I am trying to achieve this : "Isolation Score of the average waveform of identified clusters in the recording. A low Isolation Score indicates the cluster of interest is close to other clusters. A high Isolation Score indicates that the cluster of interest is farther, and better separated, from other clusters."

**Comment by alejoe91** [comment]
Hi @kshtjkumar 

The `mahalanobis_metrics` is a low-level function mainly used internally. I recommend using the [`compute_quality_metrics`](https://spikeinterface.readthedocs.io/en/latest/api.html#module-spikeinterface.qualitymetrics) function instead:

```
import spikeinterface.postprocessing as spost
import spikeinterface,qualitymetrics as sqm

# we is your WaveformExtractor object

pc  = spost.compute_principal_components(we) # isolation distance needs PCA

isolation = sqm.compute_quality_metrics(we, metric_names=["isolation_distance"])
```

`isolation` will be a `pandas.DataFrame` with `unit_id` as indices and an `isolation_distance` column. Let us know if this is clear!

**Comment by kshtjkumar** [comment]
hi i got this:
<img width="907" alt="Screenshot 2023-08-22 at 12 45 08 PM" src="https://github.com/SpikeInterface/spikeinterface/assets/68465910/306463d9-467e-4368-a61c-8b78348ca325">

**Comment by alejoe91** [comment]
Looks good! Can I close this? Feel free to open other issues for other questions
