### ISSUE TITLE
Problems when using export_report 

### ISSUE THREAD

**Issue by claudio1212** [SpikeInterface/spikeinterface#1930]
I have faced a problem  when using the cited function: it is the same exact problem of spikeinterface #1821, which I encountered when trying to use the "export_report" function after a sorting done using a recording that had a 3D probe attached. Is there any solution to this other than using a simpler 2D probe representation?

**Comment by alejoe91** [comment]
Hi @claudio1212 

You can instantiate a recording with a 3d probe, but some functions will need a 2d representation. You can do this inplace with the [`planarize`](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/baserecordingsnippets.py#L383-L404) function. Note that this function will make a 2d probe and set it in place!

**Comment by claudio1212** [comment]
Thank you, I solved it using this!
