### ISSUE TITLE
Refactor postprocessing functions to use `sortingcomponents.run_node_pipeline`

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#1933]
Currently several postprocessing functions need to traverse the traces (e.g. amplitudes, amplitude_scalings, spike locations).

In the following code, for example, the traes will need to be extracted 3 times:
```
_ = spost.compute_amplitudes(we)
_ = spost.compute_amplitude_scalings(we)
_ = spost.compute_spike_locations(we)
```

As previously discussed, we could avoid this overhead by implementing posptprocessing functions as pipeline nodes. Another benefit of this refactor would be to centralize the way we store processed files with a spike-level resolution using the `gather_mode` mechanism.

We would also need to implement a function similar to the `compute_quality_metrics` (e.g., `compute_postprocessing`) that will build the pipeline depending on the `postprocessing_names`. 

For example, in this case:
```
amps, template_metrics, spike_locations = spost.compute_postprocessing(
    we, 
    postprocessing_names=["spike_amplitudes",  "template_metrics", "spike_locations"]
)
```
the `compute_postprocessing` function will take care of creating the pipeline for spike amplitudes and locations (not for template metrics since it doesn't need traces) and routing the outputs correctly.

@samuelgarcia @h-mayorquin what do you guys think?

**Comment by zm711** [comment]
This is also done now, right?
