### ISSUE TITLE
Error with 'device_channel_indices' that do not match channel count in baserecordingsnippets.py

### ISSUE THREAD

**Issue by Serge-Vargo** [SpikeInterface/spikeinterface#1937]
Hello, 

I'm running into an issue when I create my own probe object using the probeinterface package with `device_channel_indices` that exceeds the number of recording channels. For my ephys experiments, a Ripple recording system was used to record 64 uECoG electrodes using two head stages, so the .ns5 (blackrock) recording file has channel ids going from 1-32 and 129-160.     
![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/6099cdb1-689a-4f5c-b3e2-a6bf2585c7d9)

When I manually create a probe object of my uECoG with probeinterface, I remap the physical electrodes to the actual Ripple recording channels and set the 'device_channel_indices' accordingly. 

![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/bbe7e97a-32b8-4668-b610-5b31eecfae2f)

This triggers the following error in SpikeInterface when I try to set the probe I manually created to the recording object 
![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/a7af7317-c4d0-4d74-9065-d2f7067bb1aa)
![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/b0ba311a-1219-4512-bddc-d5545c12f74e)
![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/f7a9d437-ff63-41dc-a838-5f5e9c621e48)

 When looking at the source code where this error gets flagged, I can see there's a TODO comment, so perhaps this is something you are currently looking at. I just wanted to bring it up here as well. Hopefully this is an easy fix?

![image](https://github.com/SpikeInterface/spikeinterface/assets/54637576/895180cc-0208-451d-b1eb-826e0b5e29b8)

My intuition tells me that line 146 of baserecordingsnippets.py could be replaced with the len() function instead of the np.max() function, but I'm not sure how that would affect the edge case of loading a probe with no channel list. 

I'm able to work around this issue when I set the `device_channel_indices` using probeinterface with `list(range(0,64))`, so I'm able to run the rest of the pipeline. It'll be nice to have a one-to-one map of physical electrodes to recording channel number tho. 

Thanks,
Sergio

**Comment by samuelgarcia** [comment]
Hi @Serge-Vargo
you have to handle `el_num_scheme` as indices. In short a int number zero based in 0-63(included) range.
In your code `el_num_scheme` is the ID (transformed as an integer) which is wrong.

**Comment by Serge-Vargo** [comment]
Hi @samuelgarcia,
Thanks for looking into this. Understood. I can handle `el_num_scheme` as indices, not a problem.
