### ISSUE TITLE
Read the docs structure  shows core tutorials nested inside widget tutorials

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1964]
If I clik on the module examples gallery, then core tutorials and finally append and concatenate segments the side menu makes it appears as if this embedded in the widgets tutorials.

![image](https://github.com/SpikeInterface/spikeinterface/assets/6429509/60413631-06cd-4a4d-b80d-0c7734aa8040)

Not sure why this is the case or if this indicates a deeper error in the structure of our documentation.

**Comment by zm711** [comment]
@h-mayorquin,
I think it's been like that for ages, someone on an issue recently shared the docs for .96. It was not nested on version 0.13 though, so between 13-96 api change created the nested structure in the docs. I'll look around a bit too.
https://spikeinterface.readthedocs.io/en/0.96.0/modules/index.html

**Comment by zm711** [comment]
I wonder if we change the order of the `modules_gallery` so that widgets isn't last, but lets say core is last if the mistake is the same. I looked at the raw build log and nothing looks weird. It must be accidentally creating the nested structure in the `index.rst` of widgets, but I don't have a clue why. The `conf.py` looks fine.

**Comment by zm711** [comment]
Since I wasn't able to get this fixed locally (soon-ish) I might open a do not merge pull request where I try a bunch of rearranging things to see if I can isolate the issue in the rtd building process.

**Comment by zm711** [comment]
Fixed in #2036 
https://spikeinterface.readthedocs.io/en/latest/modules_gallery/index.html

**Comment by h-mayorquin** [comment]
This is great, thanks a bunch.
