### ISSUE TITLE
typo in docs of spikeinterface 0.98.1

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikeinterface#1966]
Hi, I think there is a typo in the docs https://spikeinterface.readthedocs.io/en/0.98.1/install_sorters.html 
for setting the kilosort 2.5 path. 
That should be : set_kilosort2_5_path, the doc says `or using Kilosort2_5Sorter.set_kilosort2_path()`. See attachment 
<img width="1220" alt="Screen Shot 2023-09-06 at 11 06 48 AM" src="https://github.com/SpikeInterface/spikeinterface/assets/11243913/09eaf377-96b0-4e7c-b13b-9dd83f7b1cc9">

**Comment by alejoe91** [comment]
Thanks! Wil fix it!
