### ISSUE TITLE
Create `Templates` dataclass

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#1978]
Simple `dataclass` for templates, including:
- ms_before/after
- nbefore/after
- channel_ids/unit_ids
- channel_locations
- sparsity

Needs to be picklable and JSON-serializable

**Comment by CodyCBakerPhD** [comment]
> Needs to be picklable and JSON-serializable

Going with a Pydantic Model would go a long way beyond a traditional `dataclass` towards helping with these, as well as auto-generation of the accompanying JSON schema (not to mention native type checking / input validation)

**Comment by alejoe91** [comment]
Yeah for the first round this will be mainly used internally, so I think that pydantic might bean overkill. Let's keep this in mind for future developments.

**Comment by h-mayorquin** [comment]
#1982
