### ISSUE TITLE
Move some doc from spiketoolkit to spikeinterface.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeinterface#2]

**Comment by alejoe91** [comment]
implement full documentation here.

@samuelgarcia suggests sphinx-gallery

I think we should also have a read the docs and point to the spiketutorials for interactive widgets.

@magland I liked to google colab tutorial because it's very easy to run. We can update that too

**Comment by samuelgarcia** [comment]
Hi all all.
i will start this week the new doc.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/10

only spiketoolkit missing!

**Comment by samuelgarcia** [comment]
I am on it.
