### ISSUE TITLE
channel map discrepancy, spikeinterface 0.98.1, probeinterface 0.2.18, read_openephys

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikeinterface#2034]
Hi,

We are using spikeinterface 0.98.1 and probeinterface 0.2.18 (just updated via pip install git+https://github.com/SpikeInterface/probeinterface.git). 

A user has found a discrepancy between the channel map (.prb file) that is given as an input to read_prb at probeinterface.  She uses cambridge neurotech probe. The .prb file is attached as .txt
[CambridgeNT_H5_CB.txt](https://github.com/SpikeInterface/spikeinterface/files/12685134/CambridgeNT_H5_CB.txt)

we ran the following function for the extractor part:

<img width="1394" alt="Screen Shot 2023-09-21 at 2 23 31 PM" src="https://github.com/SpikeInterface/spikeinterface/assets/11243913/146c516e-15fe-4eca-abff-8421cf77b37c">

Then the user runs kilosort2

The output generated (here visualized with phy2): 
![MicrosoftTeams-image (10)](https://github.com/SpikeInterface/spikeinterface/assets/11243913/405d9224-6070-4bf4-a0c2-17d3c52bf9d6)

Many channels seem to be missing. I expect 64 channels with this geometry:  

![MicrosoftTeams-image (11)](https://github.com/SpikeInterface/spikeinterface/assets/11243913/94e3cec9-423b-40d7-979e-27209134d917)
 
Any help would be much appreciated.

**Comment by alejoe91** [comment]
Hi @gmaggi 

The probe is loaded correctly on my side:

```
import probeinterface as pi
from probeinterface.plotting import plot_probegroup

probegroup = pi.read_prb("/home/alessio/Downloads/CambridgeNT_H5_CB.txt")
plot_probegroup(probegroup)
```

![image](https://github.com/SpikeInterface/spikeinterface/assets/17097257/3cc29dd0-1a04-40cb-b32d-365420cfd40a)

Even after loading it into a "fake" spikeinterface recording, the probe appears correct:
```
import spikeinterface as si
import spikeinterface.widgets as sw

rec = si.generate_recording(num_channels=72)
rec_prb = rec.set_probes(probegroup)

sw.plot_probemap(rec_prb)
```

![image](https://github.com/SpikeInterface/spikeinterface/assets/17097257/b1702773-f4bf-4f4b-ae3b-2fbd29caa0cd)

```

Note that KS removes channels with low activity. So that might be the reason. You can try to `export_to_phy` from SpikeInterface!

**Comment by gmaggi** [comment]
@alejoe91 Thank you very much for your help and great support.
