### ISSUE TITLE
get_unit_amplitudes should return all labels 

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#204]
The `get_unit_amplitudes` function by default outputs `concatenated` amplitudes in a long array. However, we don't know which labels the amplitudes correspond to.

*Proposed solution*: return a `labels` array alongside amplitudes

**Comment by samuelgarcia** [comment]
There is a `outputs='by_units'` that help for that.
And if you do a `sorting.sorting.get_all_spike_trains()` you already have this label.
I think we don't need so.

**Comment by samuelgarcia** [comment]
By the way maybe this function should rename to "get_spike_samplitudes".
It would be more correct
