### ISSUE TITLE
Add `ignore_timestamps_errors` argument to `OpenEphysLegacyRecordingExtractor`

### ISSUE THREAD

**Issue by weiglszonja** [SpikeInterface/spikeinterface#2040]
Add `ignore_timestamps_errors` argument to `OpenEphysLegacyRecordingExtractor`
This argument was added to `OpenEphysRawIO` in https://github.com/NeuralEnsemble/python-neo/pull/1213 but in order to utilise the fix we need this argument for the extractor as well. 

I can open a PR for this.

**Comment by alejoe91** [comment]
@weiglszonja it would be great if you can make a PR for this!
