### ISSUE TITLE
run_sorter_jobs() function not found

### ISSUE THREAD

**Issue by bengrannan** [SpikeInterface/spikeinterface#2042]
I am attempting to use run_sorter_jobs() for batch sorting per https://spikeinterface.readthedocs.io/en/latest/modules/sorters.html?highlight=run_sorter_jobs#running-several-sorters-in-parallel . I am not able to import the function, however. The documentation instructs to use run_sorter_jobs() over run_sorters() (deprecated).  Is run_sorter_jobs() in current version? I am using version 0.98.2. 

![image](https://github.com/SpikeInterface/spikeinterface/assets/7316586/714e3b23-1728-44a7-a768-b62d700772cc)

**Comment by zm711** [comment]
@bengrannan 

It is not in 0.98.2. To use the new function you would have to install from source. [Instructions for install](https://spikeinterface.readthedocs.io/en/latest/installation.html). The documentation is updated as new features are added to prevent them from getting out of sync, but that means it often recommend users install from source following the instructions (I linked above) to get all the latest features. Eventually this will not be the case, but in this pre-1.0 stage, SpikeInterface is still making a lot of optimizations and thus some API changes. Does that make sense?

**Comment by samuelgarcia** [comment]
Hi Ben and Zach.
Alternatively you check the doc of the latest relase with this kind of url : https://spikeinterface.readthedocs.io/en/0.98.2/
In the latest release you need to use `run_sorters()` but I recommand to switch to the new run_sorter_jobs and so go for sources as Zach mentioned.

**Comment by alejoe91** [comment]
Maybe in the README we should have both the a link to the released docs and the latest one?

**Comment by zm711** [comment]
That's probably a good idea. This is the 2nd or 3rd time that I've seen this issue.

**Comment by zm711** [comment]
@alejoe91 @samuelgarcia 

Added a link to the pypi docs on the main page and linked to install from source. Did you want to still leave this open or are we good to close?

@bengrannan you can always feel free to open more issues if things come up!

**Comment by alejoe91** [comment]
I think we can close! Should be clear now :)
