### ISSUE TITLE
Reading in events for legacy open ephys format

### ISSUE THREAD

**Issue by aidapiccato** [SpikeInterface/spikeinterface#2056]
Hi! I'm having some trouble reading in events from an open ephys recording. My recording generates a single 'all_channels.events' files. However, it seems like the following line of code attempts to read in multiple events files, one per segment (64 in my case). Error is the following:

File [/om2/user/apiccato/anaconda/envs/phys_analysis/lib/python3.11/site-packages/neo/rawio/openephysrawio.py:257](https://vscode-remote+ssh-002dremote-002bomnode.vscode-resource.vscode-cdn.net/om2/user/apiccato/anaconda/envs/phys_analysis/lib/python3.11/site-packages/neo/rawio/openephysrawio.py:257), in OpenEphysRawIO._parse_header(self)
    254     event_filename = 'all_channels_{}.events'.format(oe_index + 1)
    256 fullname = os.path.join(self.dirname, event_filename)
--> 257 event_info = read_file_header(fullname)
    258 self._event_sampling_rate = event_info['sampleRate']

File [/om2/user/apiccato/anaconda/envs/phys_analysis/lib/python3.11/site-packages/neo/rawio/openephysrawio.py:550](https://vscode-remote+ssh-002dremote-002bomnode.vscode-resource.vscode-cdn.net/om2/user/apiccato/anaconda/envs/phys_analysis/lib/python3.11/site-packages/neo/rawio/openephysrawio.py:550), in read_file_header(filename)
    546 """Read header information from the first 1024 bytes of an OpenEphys file.
    547 See docs.
    548 """
    549 header = {}
--> 550 with open(filename, mode='rb') as f:
    551     # Read the data as a string
    552     # Remove newlines and redundant "header." prefixes
    553     # The result should be a series of "key = value" strings, separated
    554     # by semicolons.
    555     header_string = f.read(HEADER_SIZE).replace(b'\n', b'').replace(b'header.', b'')
    557 # Parse each key = value string separately

FileNotFoundError: [Errno 2] No such file or directory: '/om2/user/apiccato/phys_preprocessing_open_source/phys_data/elgar/2023-09-27/raw_data/test/all_channels_2.events'

**Comment by alejoe91** [comment]
@aidapiccato did you find a solution for this?
