### ISSUE TITLE
Pre-compute sparsity should have a `tempfolder` mode

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#2077]
The `precompute_sparsity` is used to compute the sparsity of each unit during the waveform extraction. However, this is always done in memory and if there are many units, multiple passes are done in unit blocks (of 100 units). For many units, it would be faster to save the waveforms in a temporary folder, compute sparsity, and then remove the tmp folder.

**Comment by samuelgarcia** [comment]
I think that even for folder mode we should keep the unit block concept to be sure to not have enormous temp folder.
no ?

**Comment by alejoe91** [comment]
No, it's not that enormous and it's a choice also where to place it.
