### ISSUE TITLE
A function to generate `spikeinterface.WaveformExtractor` object from waveforms stored in an NWB file

### ISSUE THREAD

**Issue by khl02007** [SpikeInterface/spikeinterface#2090]
@alejoe91 

Such a function (`read_nwb_waveforms`) would enable users to advantage of many waveform-related features that `spikeinterface` offers from the NWB file. 

Note: the currently recommended way to save waveforms into NWB is as nested lists for each unit (`spikes x frames x channels`) in the `waveforms` column of the [`pynwb.misc.Units`](https://pynwb.readthedocs.io/en/stable/pynwb.misc.html#pynwb.misc.Units) table.

**Comment by zm711** [comment]
With the move to SortingAnalyzer do we want to keep this open to add to it or close? @alejoe91 ?

**Comment by samuelgarcia** [comment]
I think we can close.
The WaveformExtractor was not an object to represent stored data. It was already some kind od analyzer but with the bad name.

The best option would be to use the `Snipet` object but nobody is using it and my guess is that it is pretty unmaintained.

`https://github.com/samuelgarcia/spikeinterface/blob/main/src/spikeinterface/core/basesnippets.py#L12
