### ISSUE TITLE
 'spikeinterface.full' has no attribute 'plot_traces'

### ISSUE THREAD

**Issue by NJamann** [SpikeInterface/spikeinterface#2095]
Hi,

I am running SpikeInterface Version 0.98.2 in a Jupyter Notebook on one of my Neuropixels recordings, according to the newest tutorial (Oct 23).
I am importing spikeinterface.full as si.
However, when I try to run plot.traces I get the following error:

AttributeError                            Traceback (most recent call last)
Cell In[43], line 3
      1 get_ipython().run_line_magic('matplotlib', 'widget')
----> 3 u= si.plot_traces(raw_rec, time_range=[0, 10], backend="ipywidgets", mode='map')

AttributeError: module 'spikeinterface.full' has no attribute 'plot_traces'

Can you help me out?
Thank you!
Nora

**Comment by zm711** [comment]
Hi Nora @NJamann ,

This was a change that just occurred right after the 0.98.2 release (in PR #1859) so the change in function name hasn't been incorporated yet into a release. 
The documentation for your version is [here](https://spikeinterface.readthedocs.io/en/0.98.2/ ). 
You can also install from source with these [instructions](https://spikeinterface.readthedocs.io/en/latest/installation.html) in which case the `plot_traces` will work as expected.

Previously `plot_traces` was `plot_timeseries`, but there have been a couple renamings to help make things clearer in the future (it's easier to remember to plot the traces if the function is called `plot_traces`). 

The specifics into the function you would need with the older version is [here](https://spikeinterface.readthedocs.io/en/0.98.2/modules/widgets.html?highlight=plot_timeseries).

Does all of that make sense?

**Comment by NJamann** [comment]
Ok thanks!
I had tried plot_timeseries first and didn't get an error, but it also does not output a plot either. But that might be a different issue alltogether.
I will try to install from source to use plot_traces.

**Comment by NJamann** [comment]
Hi @zm711,
I got plot_traces to run but not to work so Im at the same point as before with plot_timeseries.
For some reason I get an object as an output but not the actual plot:

![image](https://github.com/SpikeInterface/spikeinterface/assets/71709759/08c2c4aa-bd11-435e-84c3-95e96dc73b22)

**Comment by zm711** [comment]
@NJamann  I think I hav the solution.

Instead of 
```python
%matplotlib widget
```
put
```python
%matplotlib inline
```

:)

**Comment by NJamann** [comment]
Hi Zach! Great, for the matplotlib backend, that works! Thanks a lot

**Comment by zm711** [comment]
Great Nora! (@NJamann )

So if you try 

```
%matplotlib inline
%matplotlib widget
```

Does ipywidgets work? I'm just trying to figure out if I need to see if there is a bug.

**Comment by NJamann** [comment]
No that still doesnt do anything
![image](https://github.com/SpikeInterface/spikeinterface/assets/71709759/e285de1d-0421-4675-b2b5-7d32a6905149)

**Comment by zm711** [comment]
And when you installed from source you made sure to do

```
pip install .[widgets]
```

**Comment by NJamann** [comment]
I thought I did but I just redid
pip install spikeinterface[full,widgets]
again.
The only thing that wasnt installed yet was:
![image](https://github.com/SpikeInterface/spikeinterface/assets/71709759/eb82034e-3583-4d12-8110-7fedd9f3eb8f)

However, I still dont get a plot, also after restarting the virtual environment.

**Comment by zm711** [comment]
Okay I’m going to tag @samuelgarcia, since he’s the expert for plotting. He’ll look over things when he gets a moment. (I personally just use the matplotlib backend).

**Comment by NJamann** [comment]
Thanks anyways for your help, Im already happy to visualize my data like this! :)
