### ISSUE TITLE
Curation Tutorial Broken

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#2101]
Curation tutorial was broken by #2061.

I didn't have time to look into it yet, but I wanted this on my radar to remind me.

https://spikeinterface.readthedocs.io/en/latest/modules_gallery/qualitymetrics/plot_4_curation.html#sphx-glr-modules-gallery-qualitymetrics-plot-4-curation-py

**Comment by alejoe91** [comment]
Interesting. I cannot reproduce the issue locally by running the `examples/modules_gallery/quality_metrics/plot_4_curation.py`.

@zm711 curious if it fails locally for you!

**Comment by zm711** [comment]
It failed locally for me too!

```
    self._main_ids.dtype.kind in "uiSU"
AssertionError: Main IDs can only be integers (signed/unsigned) or strings, not object
```

**Comment by zm711** [comment]
@alejoe91 so the issue is

```
>>> keep_mask.index.values
Index(['#0', '#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9'], dtype='object')
```

It is being stored as an np object array because np does haven't string arrays. Do you want to fix this as a bug to allow numpy object arrays initialize ids or do you want me to fix the tutorial and pop out the strings into a list which I just tested and worked fine.

```
test =[idx for idx in keep_mask[keep_mask].index.values]
>>> curated_sorting = sorting.select_units(test)
```

**Comment by samuelgarcia** [comment]
Why did we removed objetc in main_ids ?

**Comment by alejoe91** [comment]
Because we always assume main IDs should be int or str. In my opinion, it is time to always use strings

**Comment by samuelgarcia** [comment]
No lets keep int. It is super convinient in many places.

**Comment by alejoe91** [comment]
Where? I think it's just annoying
