### ISSUE TITLE
help with understanding Spike waveforms (basic)

### ISSUE THREAD

**Issue by kshtjkumar** [SpikeInterface/spikeinterface#2151]
I used the following code to generate waveforms:
<img width="837" alt="Screenshot 2023-11-01 at 12 04 39 PM" src="https://github.com/SpikeInterface/spikeinterface/assets/68465910/fc9588cc-4222-44d8-b670-aa37d4311903">

The results i got:
<img width="522" alt="Screenshot 2023-11-01 at 12 04 28 PM" src="https://github.com/SpikeInterface/spikeinterface/assets/68465910/f4699351-0933-4770-b84f-3ba1c2b1067b">

I want some help with the x axis of the graph here! is the time in milliseconds ? 

We got a review on the graph saying:
the single unit spike snippets are showing tens of ms which is abnormal. It is curious if the authors actually captured unit spikes or other signals such as EMGs.
the exact image the review was on is this:
<img width="513" alt="Screenshot 2023-11-01 at 2 12 44 PM" src="https://github.com/SpikeInterface/spikeinterface/assets/68465910/2d22ea15-76a9-456e-9094-a5f9daf59de5">

Can someone explain how to interpret these?

**Comment by alejoe91** [comment]
The x axis are is sample index. To plot timestamps in ms, you can compute the values as this:
```
import numpy as np

num_samples = we.nbefore + we.nafter
timestamps_ms = np.arange(num_samples) / we.sampling_frequency * 1000
```

**Comment by alejoe91** [comment]
If you plot without an `x` (like in your case, you are only providing the `y`, i.e. the waveforms), the x axis is always going to be from 0 to num_samples - 1.

**Comment by kshtjkumar** [comment]
i got this output:
![Uploading Screenshot 2023-11-01 at 2.38.24 PM.png…]()

**Comment by kshtjkumar** [comment]
i got this as output:
![Uploading Screenshot 2023-11-01 at 2.38.24 PM.png…]()

**Comment by alejoe91** [comment]
Which output? The link is broken on my side

**Comment by kshtjkumar** [comment]
![Uploading Screenshot 2023-11-01 at 2.38.24 PM.png…]()

**Comment by kshtjkumar** [comment]
![Uploading Screenshot 2023-11-01 at 2.38.24 PM.png…]()

**Comment by kshtjkumar** [comment]
i am not able to upload the image ! it keeps saying like above!

**Comment by alejoe91** [comment]
Anyways, you should be getting from 0 to 7ms if your sampling frequency is 30kHz

**Comment by kshtjkumar** [comment]
yep the x axis is from 0 to 7 !
So now,  i can use this for all waveform sorting ?

**Comment by alejoe91** [comment]
Yes, that is the same for all waveforms. It is set when you extract waveforms with the `ms_before`\`ms_after`. See docs here: https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.core.extract_waveforms

**Comment by kshtjkumar** [comment]
thank you so much! As always You have been of great help!
