### ISSUE TITLE
Auto- and cross-correlation

### ISSUE THREAD

**Issue by BenATemple** [SpikeInterface/spikeinterface#221]
I am trying to plot auto and crosscorrelograms.
I notice that the tutorial for these plots (as well as ISI distribution) is not complete.
I try this: sw.plot_autocorrelograms(sorting_IC, unit_ids=[3], window_ms=100.0, bin_ms=1.0, symmetrize=False)
But I get an error : [AssertionError: 'axes' can be a 1-d array or list or a 2d array of axis]
Seems like an easy fix but not sure exactly what to do!
AC, CC, and ISI are nice quality-metric visualizations so would be helpful to flesh this out if anyone has tips :)
Thank you,
Ben

PS I am also curious whether you will have any tutorial sessions at SfN this year, whether in-person or virtual?

**Comment by alejoe91** [comment]
Hi @BenATemple 

Seems like a small bug on our side. I'll look into it next week :) 
No sfn for us this year, but I'm giving a SI tutorial next Friday for the nwb user days workshop: https://www.incf.org/neurodata-without-borders-nwb-user-training-workshop

**Comment by BenATemple** [comment]
Thanks a lot, @alejoe91 ! And I'll send the link to the tutorial to some others who might be interested :)

**Comment by samuelgarcia** [comment]
Is this fixed ?
Can you copy/paste a short example that trigger the bug ?

**Comment by BenATemple** [comment]
Thanks, Samuel!
To my knowledge, it its not yet fixed. I just attempted again.
I try this: sw.plot_autocorrelograms(sorting_IC, unit_ids=[3], window_ms=100.0, bin_ms=1.0, symmetrize=False)
But I get an error : [AssertionError: 'axes' can be a 1-d array or list or a 2d array of axis]

**Comment by samuelgarcia** [comment]
See #230 
I have updated examples for auto and cross correlogram.
Example are working on my side.

**Comment by samuelgarcia** [comment]
@BenATemple :  can you check that examples are working for you ?

**Comment by BenATemple** [comment]
@samuelgarcia Sorry, just got back to this. Yes, it works now, thank you!
