### ISSUE TITLE
WaveClus sorting frozen in Matlab initializing

### ISSUE THREAD

**Issue by Hobart10** [SpikeInterface/spikeinterface#2212]
Hi, in running Wave_Clus in local, the sorter just froze in initilizing Matlab, any idea how to fix? Thank you so much!

```
si.WaveClusSorter.set_waveclus_path(WC_path)
sorter_params = {'enable_sort_filter': False, 'enable_detect_filter': False}
sorting_wc = si.run_sorter(sorter_name='waveclus', recording=recording_saved, remove_existing_folder=True, output_folder=Path(bin_folder) / 'results_wc', verbose=True, **sorter_params)
```

**Comment by alejoe91** [comment]
Hi! For sorter specific problems, I would open an issue on the sorter main page. Maybe @ferchaure can help!

**Comment by ferchaure** [comment]
Hi, all. Sorry, but the WaveClus's repository is archived. Probably new forks (and developers) will take its place in the future.
Can you show me the .log file inside the folder?

Just a remainder: WaveClus isn't design for more than ~4 channels. It doesn't handle collisions, I wouldn't recommend using it for 64 channels, at least all proceed together.

**Comment by ferchaure** [comment]
It looks normal, maybe give it more time? 

Another test is to run the script Y:\EphysData\441EphysData\Wireless\231024\SItest\results_wc_demo\sorter_output\waveclus_master.m on matlab to check if its crashing. But it looks like a limited RAM issue
