### ISSUE TITLE
Template waveform not on the same same channel as the mean waveform?

### ISSUE THREAD

**Issue by Kayv-cmb** [SpikeInterface/spikeinterface#2302]
Hi all,

Something weird is happening and I don't know if this is truly an issue?
I have neuropixel 2.0 recording sorted with kilosort3.  

```
    recording_concat = si.concatenate_recordings(clean_recordings)
    rec2 = bandpass_filter(recording_concat, freq_min=300, freq_max=6000) #Band pass filtering    
    rec3 = si.phase_shift(rec2)
    rec4 = si.common_reference(rec3, operator="median", reference="global")
    rec = rec4
```

 I am looking at 3 different units that are not the same( cross-correlation and PCA indicate that I should not merge) but located on the same channel as told by kilosort3. However the mean waveform is not located on the same channel as the template waveform(see screenshot), is it a phy issue, a sorting issue or a spikineterface issue (I use the phase shift function ).  

If I can get some help to figure out why this is happening that would be awesome. Thanks

![Screenshot 2023-12-06 at 13 18 49](https://github.com/SpikeInterface/spikeinterface/assets/93250401/3820a6ae-07de-4266-a961-f41cd7d3e05d)
![Screenshot 2023-12-06 at 13 19 02](https://github.com/SpikeInterface/spikeinterface/assets/93250401/d304897d-c681-4230-879f-d8c24264640c)

**Comment by alejoe91** [comment]
Are you exporting with SI or loading the KS output folder directly? 
I think this should be a phy or kilosort issue. Maybe related to whitening/unwhitening

**Comment by alejoe91** [comment]
Actually the main channel is the same!

**Comment by Kayv-cmb** [comment]
```
rec2 = bandpass_filter(recording_concat, freq_min=300, freq_max=6000) #Band pass filtering    
    rec3 = si.phase_shift(rec2)
    rec4 = si.common_reference(rec3, operator="median", reference="global")
    rec = rec4
    # Add kilosort to sorter_name to launch the spikesorting
    sorter_name = ['kilosort']
    # Path to save (Scratch folder recommended)
    rec = rec.save(folder=directory_output+'preprocessing', format='binary', **job_kwargs)
    np.savetxt(directory_output+"clean_frame_threshold1500uV.csv", clean_frame, delimiter=",")

    if 'kilosort' in sorter_name:
        default_KS = ss.Kilosort3Sorter.default_params()
        rec = si.load_extractor(directory_output+'preprocessing')
        # Directory output can be directory+'sorting_kilosort'
        sorting_KS = ss.run_kilosort3(rec, output_folder= directory_output + '/results_Kilosort_3',
                                    verbose=True,**default_KS)
```

This is how I am doing the sorting and after that I directly read from the sorter ouput with phy

**Comment by alejoe91** [comment]
Yeah then definitely it's something related to Phy/Kilosort ;)

**Comment by Kayv-cmb** [comment]
Thank you, I will ask over there
