### ISSUE TITLE
`highpass_spatial_filter` returns as `float32`

### ISSUE THREAD

**Issue by JoeZiminski** [SpikeInterface/spikeinterface#2311]
I just realised `highpass_spatial_filter` is returning as `float32`. [here](https://github.com/SpikeInterface/spikeinterface/blob/8e32955e0616b9e399c253aaf0602f3aa646dae4/src/spikeinterface/preprocessing/highpass_spatial_filter.py#L235). (cast during scipy filtering I think). Should this be cast to `self.dtype` similar to [filter.py](https://github.com/SpikeInterface/spikeinterface/blob/8e32955e0616b9e399c253aaf0602f3aa646dae4/src/spikeinterface/preprocessing/filter.py#L160)?

I also see the `uint` is forced to float32 in filtering [here](https://github.com/SpikeInterface/spikeinterface/blob/8e32955e0616b9e399c253aaf0602f3aa646dae4/src/spikeinterface/preprocessing/filter.py#L140). Should this also be a consideration for `highpass_spatial_filter`?

**Comment by h-mayorquin** [comment]
Did you ever make your mind about this? Any suggestion on what would be better?

**Comment by alejoe91** [comment]
@h-mayorquin @JoeZiminski this is fixed in main! Getting an `int16` out of an `int16` input :)

**Comment by alejoe91** [comment]
> @h-mayorquin @JoeZiminski this is fixed in main! Getting an `int16` out of an `int16` input :)

Forget about it! the traces are indeed in float. Will make a PR with a fix!

**Comment by JoeZiminski** [comment]
That's great thanks @alejoe91 and thanks for reviving this @h-mayorquin!

**Comment by alejoe91** [comment]
I'll make a PR today to fix it
