### ISSUE TITLE
Missing "lam" and "momentum" Kilosort parameters

### ISSUE THREAD

**Issue by ikharitonov** [SpikeInterface/spikeinterface#2352]
Hi,

Spotted that "lam" and "momentum" parameters for Kilosort are hardcoded rather than accessible from default_params dictionary. Would it be possible to add them?
e.g. in spikeinterface/src/spikeinterface/sorters/external/kilosort2.py

**Comment by zm711** [comment]
I don't see why that shouldn't be exposed. I can open a PR unless you have a specific reason not to allow this @alejoe91?
