### ISSUE TITLE
Bad channel detect

### ISSUE THREAD

**Issue by nadirbt** [SpikeInterface/spikeinterface#2367]
It seems like the detect_bad_channels.py has a bug in line 172 where random_chunk[order_f] should be changed to random_chunk[: , order_f]. I am assuming that the get_traces method always returns arrays in this format (frames, channels). Please let me know if I am missing something.

Thank you!

**Comment by alejoe91** [comment]
Hi @nadirbt 

This has been fixed in the 0.99.1 release:
https://github.com/SpikeInterface/spikeinterface/blob/0.99.1/src/spikeinterface/preprocessing/detect_bad_channels.py#L182

Cheers
Alessio
