### ISSUE TITLE
SilencePeriodsRecording throws an error 

### ISSUE THREAD

**Issue by nadirbt** [SpikeInterface/spikeinterface#2373]
Everytime I run a recording that was processed by the silence period function, it throws this error: 

get_random_data_chunks() got an unexpected keyword argument 'noise_levels'

I think this is because the definition of the class initializer is different from the definition of the self._kwargs argument.

**Comment by yger** [comment]
Can you share a minimal example to reproduce the error? I'll have a look asap

**Comment by nadirbt** [comment]
I was able to replicate the bug using this code:

import spikeinterface.full as si
from pathlib import Path

global_job_kwargs = dict(n_jobs=4, chunk_duration="1s")
si.set_global_job_kwargs(**global_job_kwargs)

local_path = Path(__file__).parent / './mearec_test_10s.h5'
recording, _ = si.read_mearec(local_path)

rec_preprocessed = si.silence_periods(recording, list_periods = [(0, 10)], mode='noise')

sorting_MS5 = si.run_sorter(sorter_name='mountainsort5', recording = rec_preprocessed, remove_existing_folder=True)

**Comment by yger** [comment]
This should be fix with #2375. Indeed, noise levels were not saved as internal attributes, sorry for that

**Comment by nadirbt** [comment]
Thank you for fixing this. Has the change been released yet?

**Comment by yger** [comment]
No, this is only in the main branch (that you can install via git), not yet in a release
