### ISSUE TITLE
Issue Regarding the get_waveforms Method about version 0.99

### ISSUE THREAD

**Issue by sunjie454** [SpikeInterface/spikeinterface#2409]
I use mountain_sort5 for data sorting, and then try to call the get_waveforms method to obtain waveforms for each unit. The following is a portion of my code along with usage instructions (indicating "The returned waveform (num_spikes, num_samples, num_channels)"). 
<img width="456" alt="微信图片_20240117142721" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/5c687afc-bfe3-4943-b412-f4d1611fd6da">
<img width="793" alt="微信图片_20240117142729" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/e19ec0db-1dbd-4308-b7d9-7c695d008cfa">
<img width="803" alt="微信图片_20240117142736" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/02997cd2-04e5-4e6d-844c-78eaf6f00781">
<img width="625" alt="微信图片_20240117142741" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/08eda83c-efba-4661-bfa4-bdc7e598234e">
<img width="761" alt="微信图片_20240117142745" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/d2dbc9c6-cb8e-4f69-af38-6d8f5c21583b">
<img width="493" alt="微信图片_20240117142748" src="https://github.com/SpikeInterface/spikeinterface/assets/139612137/42e6c576-8e62-46d1-b688-68434dabf5cb">

    In version 0.98, there isn't any problems, and I can retrieve waveforms from the channels corresponding to the unit. However, in version 0.99, a problem arises where the returned data shape is (num_spikes, num_samples, 3), instead of (num_spikes, num_samples, num_channels). Could someone please explain what the third dimension of the data returned by the get_waveforms method is in version 0.99, and how I can obtain waveforms for the channels corresponding to this unit?

**Comment by samuelgarcia** [comment]
Here in the doc : https://spikeinterface.readthedocs.io/en/latest/modules/core.html?highlight=sparsity#sparsity

**Comment by zm711** [comment]
Let us know if you still have trouble, I'll close this now.
