### ISSUE TITLE
Spike timepoints for individual units?

### ISSUE THREAD

**Issue by taningh86** [SpikeInterface/spikeinterface#2422]
Is there a built-in function to extract spike timepoints for each unit? I am looking to get spike timepoints to find units that fire at the same timepoints or have correlated firing of some sort.

**Comment by alejoe91** [comment]
Yes of course! `sorting.get_unit_spike_train(unit_id)`

You can read more about the `Sorting` object here: https://spikeinterface.readthedocs.io/en/latest/modules/core.html#sorting

**Comment by taningh86** [comment]
Thanks Alessio! This is very helpful!

**Comment by taningh86** [comment]
Is it possible to get it for all units? It looks like 'get_unit_spike_train' specifically gets for one unit at a time and putting a range don't seem to work.

**Comment by alejoe91** [comment]
`sorting.get_all_spike_trains()` (https://spikeinterface.readthedocs.io/en/latest/api.html?highlight=Get_all_spike_trains#spikeinterface.core.BaseSorting.get_all_spike_trains)

**Comment by samuelgarcia** [comment]
Hi,
get_all_spike_trains() is deprecated use insteadto_spike_vector()

**Comment by alejoe91** [comment]
@samuelgarcia 

It's not deprecated and it's the only function to return a dictionary of spike times...

**Comment by samuelgarcia** [comment]
No we decided to depreacte it.

https://spikeinterface.readthedocs.io/en/latest/api.html?highlight=Get_all_spike_trains#spikeinterface.core.BaseSorting.get_all_spike_trains

https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/basesorting.py#L457

**Comment by alejoe91** [comment]
It can be convenient though no?

**Comment by taningh86** [comment]
Thanks guys! Looks like to_spike_vector() is the one togo for version 0.99.1.0

**Comment by zm711** [comment]
I'll close this for now, but we could open a new issue to debate the deprecation if necessary. @taningh86 feel free to reach out if new things come up.
