### ISSUE TITLE
Could we reuse plotting function made for WaveformExtractor for Templates

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#2428]
While the addition of the Templates object is great, the problem is that it can not make use of all the plotting functions that have already been built for templates, but assuming a waveformexctrator as input. Should we modify these plotting functions accordingly, or discuss about a possible mecanism to close the gap between the two objects?

**Comment by yger** [comment]
Actully, I think that to be consistent, the get_all_templates() function of the waveform_extractor should return a Template object, don't you think?

**Comment by samuelgarcia** [comment]
This will be done with the SortingAnalyzer/SortingResult implementation.

**Comment by yger** [comment]
Ok, but what is the plan? Because to move forward with hybrid project, I would need to use functions made for WaveformExtractor (like in template_tools.py for example). Do you plan of extending all signatures with something like waveform_extractor_or_templates as you are doing currently in #2410, or are you planning to make Templates and WaveformExtractor inherit from a common object? Conceptually, they share quite a lot of attributes, so I don't know

**Comment by zm711** [comment]
@yger, did you still want plotting for Templates or is the SortingAnalyzer fine and we can close this now?

**Comment by yger** [comment]
I would like to be able to have the plot_unit_template widget working when only fast_templates is computed....

**Comment by alejoe91** [comment]
This has been implemented in https://github.com/SpikeInterface/spikeinterface/pull/2856
