### ISSUE TITLE
recording.set_probe gives an error

### ISSUE THREAD

**Issue by Ashkees** [SpikeInterface/spikeinterface#2429]
Hello,

I'm new to spike interface, so my apologies if I'm making a silly error, or if this isn't the correct channel for asking questions.

I've loaded my 96-channel intan data using
```
recording = si.load_binary(filepath)
```
and I would like to set the probe.  I've created a ProbeGroup object that consists of 32 channels from a linear probe and 64 channels from a 4-shank probe. I've saved it as a .json and  I've tried 
```
recording.set_probe(probegroup) 
```
but this throws the following error:
```
AssertionError: must give Probe
```
What could I be doing incorrectly?  I've attached the probegroup .json.

Thanks!
Ashley
[SI_4shank_linear.json](https://github.com/SpikeInterface/spikeinterface/files/14025767/SI_4shank_linear.json)

**Comment by alejoe91** [comment]
Hi @Ashkees !

To set a probe group you should use the `set_probegroup(probegroup)` instead :)

**Comment by Ashkees** [comment]
Ah, yes, that was silly.  That worked!  thank you =)

**Comment by Ashkees** [comment]
I didn't think to look for another method because the first argument to set_probe is probe_or_probegroup so I assumed it could take a probegroup

**Comment by alejoe91** [comment]
No worries! It's much less common to use probe groups instead of probes, so that's probably why it was a bit harder to find in tutorials/docs ;)
