### ISSUE TITLE
localize_peaks takes forever to complete

### ISSUE THREAD

**Issue by kingsEffy** [SpikeInterface/spikeinterface#2439]
Hi 
I'm wondering wether anyone also encountered this issue, when I'm trying to test code @ https://spikeinterface.github.io/blog/  --- using my own data, the localize_peaks  will just take ages and seems like stuck in a dead loop. I bascially just copy, paste things except recording data is preprocessed using 'from spikeinterface.preprocessing import bandpass_filter, common_reference', fairly straight forward and simple. I have no idea what is going on, hope anyone could help me here!

![Screenshot 2024-01-25 150438](https://github.com/SpikeInterface/spikeinterface/assets/100651591/d6175b76-b5be-4d6e-8fec-7790b4c06515)

**Comment by alejoe91** [comment]
Hi @alejoe91 

What `**job_kwargs` are you using? We are aware that the monopolar trianculation is slow..we're working on it. To speed it up you should:

- increase the number of jobs
- use the default optimizer (I think it should be faster, bu @cwindolf can confirm)

**Comment by alejoe91** [comment]
You can also add `progress_bar=True` in the `job_kwargs` to monitor progress (and see if and where it actually gets stuck!)

**Comment by kingsEffy** [comment]
> You can also add `progress_bar=True` in the `job_kwargs` to monitor progress (and see if and where it actually gets stuck!)

Hey Alessio, this is my job_kwargs setting:
# global kwargs for parallel computing
job_kwargs = dict(
    n_jobs= 40,
    chunk_duration='1s',
    progress_bar=True,
)


actually, the commands like 'import spikeinterface.widgets as sw
sw.plot_timeseries(recording_filtered, time_range=(100, 110), channel_ids=list(range(5, 16)))' are also taking forever ...

I switched to different methods for peak localizations however it did not help...

**Comment by kingsEffy** [comment]
well I tried in jupyternotebook instaed of vs code, the dead loop issue resolved. however, new issue came up:
![image](https://github.com/SpikeInterface/spikeinterface/assets/100651591/919deebd-697a-4de0-9443-72e3f647b3dc)

???

**Comment by zm711** [comment]
I think there must be some changes from that tutorial. It is from April 2022, so well over a year old. The current way to run this (but correct me if I'm wrong @alejoe91) would be

```python
some_peak_locations = localize_peaks(recording_w_probe, some_peaks, method='center_of_mass', radius_um=20, **job_kwargs)
```
notice that you no longer wrap the `method_kwargs` inside of a dict called `method_kwargs` you just put them into the function call. 



Or if you want to try with `monopolar_triangulation` you should use the appropriate method_kwargs as keywords:

```python
some_peak_locations = localize_peaks(recording_w_probe, some_peaks, method='monopolar_triangulation', radius_um=20, max_distance_um = 100, **job_kwargs) # whatever you want
```

Could you tell us what which version of spikeinterface you are using. Since that tutorial is over a year old you would need to be using an old version of spikeinterface for things to work as they did there.
```python
import spikeinterface as si
print(si.__version__)
```

Also for my records since you're on Windows could you do a conda list and let me know what version of threadpoolctl you have? 



For @alejoe91:

I was able to recreate the problem locally and it is because in the `split_job_kwargs` it returns the method_kwargs as a dict like this:
```
{'method_kwargs': {nested info here}}
```
 Is that a bug and you want to go back to the old way of doing it or is this just the  new way of doing this? I checked our tests and they don't specifically test this old format used in this tutorial which is probably why it escaped our notice.

**Comment by alejoe91** [comment]
We should have @samuelgarcia and @yger chime in here :)

**Comment by kingsEffy** [comment]
Hi zm711,
really apricate your detailed responses, related to your questions:
![image](https://github.com/SpikeInterface/spikeinterface/assets/100651591/33a3a079-483c-427c-b22b-e5389fb55c76)


I'm back to si again. Since last time i posted i switched to kilosort3 and things went ok (some issues with using Phy to do curations), so I feel like i need a mind change. so im back to this topic again!!!!

**Comment by zm711** [comment]
I just want to see threadpoolctl and it looks like it got cutoff by the ... Could we see that? It looks like you can click the link to get the scrollable and then you can paste the whole output. :) 

 And did you want to try to run the code the way I wrote it. You definitely have a newer version so you'll need to try the newer version. Notice for example it is no longer `local_radius_um` but `radius_um` and the arguments you want should go straight into the function. 

But more than happy to help and hopefully @samuelgarcia and @yger way in too!

**Comment by kingsEffy** [comment]
> I just want to see threadpoolctl and it looks like it got cutoff by the ... Could we see that? It looks like you can click the link to get the scrollable and then you can paste the whole output. :)
> 
> And did you want to try to run the code the way I wrote it. You definitely have a newer version so you'll need to try the newer version. Notice for example it is no longer `local_radius_um` but `radius_um` and the arguments you want should go straight into the function.
> 
> But more than happy to help and hopefully @samuelgarcia and @yger weigh in too!

yes, seems it worked
![image](https://github.com/SpikeInterface/spikeinterface/assets/100651591/4972407f-41f8-415e-981c-dc753ca285b4)

**Comment by kingsEffy** [comment]
> I just want to see threadpoolctl and it looks like it got cutoff by the ... Could we see that? It looks like you can click the link to get the scrollable and then you can paste the whole output. :)
> 
> And did you want to try to run the code the way I wrote it. You definitely have a newer version so you'll need to try the newer version. Notice for example it is no longer `local_radius_um` but `radius_um` and the arguments you want should go straight into the function.
> 
> But more than happy to help and hopefully @samuelgarcia and @yger weigh in too!

at least the deed loop did not show up and size isn't empty!

**Comment by kingsEffy** [comment]
> I just want to see threadpoolctl and it looks like it got cutoff by the ... Could we see that? It looks like you can click the link to get the scrollable and then you can paste the whole output. :)
> 
> And did you want to try to run the code the way I wrote it. You definitely have a newer version so you'll need to try the newer version. Notice for example it is no longer `local_radius_um` but `radius_um` and the arguments you want should go straight into the function.
> 
> But more than happy to help and hopefully @samuelgarcia and @yger weigh in too!

![image](https://github.com/SpikeInterface/spikeinterface/assets/100651591/23da0d1b-cfe7-4118-b251-acc599aba3d3)
This one?

**Comment by kingsEffy** [comment]
@zm711 @alejoe91,  you guys have been very helpful and responsive! I'm moving forward to next step! Thank you for you guys!

**Comment by alejoe91** [comment]
You're welcome! I also recommend upgrading to version 0.100.0 (`pip install -U spikeinterface`). It includes some optimization in the motion estimation:

- better RAM management
- a new faster preset: `nonrigid_fast_and_accurate`

Closing the issue then! Feel free to open another one

**Comment by kingsEffy** [comment]
> You're welcome! I also recommend upgrading to version 0.100.0 (`pip install -U spikeinterface`). It includes some optimization in the motion estimation:
> 
> * better RAM management
> * a new faster preset: `nonrigid_fast_and_accurate`
> 
> Closing the issue then! Feel free to open another one

Will do!

Again, thank you very much for you guys (@zm711 @yarikoptic @jsiegle )! Very useful and impressive sorting/analysis tools!

Hope you guys best in the coming dargon lunar new year!

**Comment by kingsEffy** [comment]
> You're welcome! I also recommend upgrading to version 0.100.0 (`pip install -U spikeinterface`). It includes some optimization in the motion estimation:
> 
> * better RAM management
> * a new faster preset: `nonrigid_fast_and_accurate`
> 
> Closing the issue then! Feel free to open another one

Ok, just a quick feedback and could be just very specific to me, the kernel kinda dead/stucked after I did 'pip install -U spikeinterface' in the environment, I tried many ways to run the script i had yesterday, I can not even load data directory and stuff (very beginning of everything)...  
could be my computer's reason, I restarted the computer but still taking forever to start the begining of my code this time...

**Comment by kingsEffy** [comment]
I found the resaon, related to this https://github.com/SpikeInterface/spikeinterface/issues/2164

**Comment by zm711** [comment]
@kingsEffy, If you are triggering a WinError32 during the running of localize_peaks could you post the actual error you're getting in #2164. It'll help keep track of Windows errors. If it is not a WinError32 feel free to open a new issue with the current problem so we can try to troubleshoot.
