### ISSUE TITLE
Timestamps associated with recordings

### ISSUE THREAD

**Issue by khl02007** [SpikeInterface/spikeinterface#245]
We have a timestamp for each sample in the recording (as opposed to inferring the time of each sample based on the sampling rate) in absolute time. This is useful because we do long recordings and sometimes have dropped samples; knowing the absolute time helps us identify these and makes alignment with other data streams easy. Is there a way to associate such explicit timestamps with a recording extractor? And have the recording use the timestamps for various things (like inferring the length of the recording in seconds etc)? I think this was addressed before in the previous version of spikeextractors but not sure what happened in the new version.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/297

**Comment by khl02007** [comment]
@alejoe91 I'm getting this behavior with the changes to handle timestamps:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/9277197/140879688-c62634df-c1ba-4646-aa21-b60c41530b6f.png">
How do I access a closed HDF5 dataset?

**Comment by alejoe91** [comment]
Ah sorry about that @khl02007 

You just need to copy the time vector here: https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/extractors/nwbextractors.py#L76 

Will make a PR soon

**Comment by samuelgarcia** [comment]
Alessio. I think we need to change the implementation and remove the `with NWBHDF5IO...` because it slow down the read by chunk.

**Comment by alejoe91** [comment]
> Alessio. I think we need to change the implementation and remove the `with NWBHDF5IO...` because it slow down the read by chunk.

I agree. I'll fix both this afternoon
