### ISSUE TITLE
Saving and sorting issue - and device channels reset when set_probe

### ISSUE THREAD

**Issue by Alexis-Melot** [SpikeInterface/spikeinterface#246]
I am having the same issue when saving and sorting my recording to which I combined a 60 channel probe that I designed to look like a MEA 60 which was used for the recording I am studying. 
Here is the error I get when trying to save my preprocessed recording (after setting the probe), which is pretty much the same than when I try to sort with ironclust
[error.txt](https://github.com/SpikeInterface/spikeinterface/files/7065150/error.txt)
I noticed that the sampling frequency of my recording is float and that only the files 'properties','provenance.json' and traces_cached_seg0.raw' are present in the saving directory. 
 
I don't know if it's linked to my saving issue but I defined a specific device channels for my probe and when I set_probe to my recording object it doesnt keep my changes, see dataframe picture before and after set_prob :
![before_dataframe_device_channels](https://user-images.githubusercontent.com/87820482/131094295-884355ee-8f6d-4420-9742-7a19df678366.png)
![after_dataframe_device_channels](https://user-images.githubusercontent.com/87820482/131094299-633088c4-db95-4c8b-b08a-930e99c0b0e3.png)

hope me explanation was clear
thanks for your time and help

**Comment by Alexis-Melot** [comment]
Sorry if I'm being insistent but do you have any leads on my type error ?

**Comment by alejoe91** [comment]
@samuelgarcia any idea on the issue here? @Alexis-Melot how do you create the probeinterface object? Can you share it with us?

**Comment by samuelgarcia** [comment]
@Alexis-Melot : sorry I totaklly forgot about your error.
From the log file I guess we have a bug from a float variable that should be a int.
I will make a patch.

**Comment by samuelgarcia** [comment]
You can fix it now by forcing `num_channels` to be an int with `num_channels = int(num_channels)`

**Comment by samuelgarcia** [comment]
@alejoe91 : the bug is in spikeinterface and not probeinterface look at the the error.txt file.

**Comment by samuelgarcia** [comment]
Oups. Myabe it is the byteoffest that cause problem.
@Alexis-Melot : can you share the full code ?

**Comment by alejoe91** [comment]
@Alexis-Melot any update on this?

**Comment by Alexis-Melot** [comment]
sorry I forgot to respond, I reinstalled my work environment on ubuntu and it worked smoothly somehow 
thank you for your help !
