### ISSUE TITLE
Bug in template.py since zarr handling

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#2469]
Line 210 and 277 in template.py are triggering errors on my machine, since the last push of zarr handling for Templates. The error is:

TypeError: unsupported operand type(s) for |: 'type' and 'type'

It can be removed if I remove the typing in the signatures of the function, since this is the str | Path that is problematic

**Comment by h-mayorquin** [comment]
This is most likely python 3.8 and 3.9 related. This should be solved after:
https://github.com/SpikeInterface/spikeinterface/pull/2468

**Comment by zm711** [comment]
I'll close this since with #2468 there is `from __future__ import annotations` everywhere now which should prevent any typing issues. Reopen if the issue wasn't solved.
