### ISSUE TITLE
Dev-branch: Bug in `load_waveforms` for `waveforms_extractor_backwards_compatibility.py`

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#2505]
https://github.com/SpikeInterface/spikeinterface/blob/69d1f9a3db9ada72812204ca25012efec5c1ff40/src/spikeinterface/core/waveforms_extractor_backwards_compatibility.py#L334-L342

This fails because it returns the function which evaluates as truth-y

It should be

```python
(folder / "spikeinterface_info.json").exists():
```

This evaluated as true and then failed in one of my datasets.

cc: @alejoe91 @samuelgarcia

**Comment by alejoe91** [comment]
Good catch!

**Comment by samuelgarcia** [comment]
Thanks.
I fix it in #2502
