### ISSUE TITLE
Bug with PhyKilosortExtractors

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#252]
The object assumes that .tsv files are there with data on the clusters. This is not the case, at least for KS1.  

/media/cure/Secondary/pierre/softwares/spikeinterface/spikeinterface/extractors/phykilosortextractors.py in __init__(self, folder_path, exclude_cluster_groups, keep_good_only)
     72                     cluster_info = pd.merge(cluster_info, new_property, on='cluster_id')
     73 
---> 74             cluster_info["id"] = cluster_info["cluster_id"]
     75             del cluster_info["cluster_id"]
     76 

TypeError: 'NoneType' object is not subscriptable

**Comment by alejoe91** [comment]
Waiting for your PR :)

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/250
