### ISSUE TITLE
extension `spike_amplitudes` is really slow with few spikes

### ISSUE THREAD

**Issue by DradeAW** [SpikeInterface/spikeinterface#2554]
`analyzer.compute("spike_amplitudes")` is really slow (90s in my case) even when the sorting contains a single unit with two spikes.

Chunks of recording with no spikes should be skipped.

**Comment by yger** [comment]
Indeed, there is a draft of such a refactoring. Currently, the node pipeline is loading all the chunks, even if there are no peaks in it. This should and will be modified soon, but as @samuelgarcia mentionned, the big refactoring of the SortingAnalyzer perturbed everything. We will keep yo updated

**Comment by zm711** [comment]
@samuelgarcia @yger are we good here? I was following you guys trying to skip stuff, but I forget if that ever got merged?
