### ISSUE TITLE
motion correction error with probegroup recording

### ISSUE THREAD

**Issue by AOONIH** [SpikeInterface/spikeinterface#2568]
Hi, 
I'm using stacked cambridge neurotech probes so have been using a probegroup to set the probe for the recording. In general I've had to hack my way around a bunch of issues but the latest one is related to using the non-rigid motion correction on recordings with multiple probes

running:
    `recording_corrected, motion_info = si.correct_motion(recording, preset=preset,output_motion_info=True, **job_kwargs)`
gives the error:
assert len(probes) == 1, "there are several probe use .get_probes() or get_probegroup()"
AssertionError: there are several probe use .get_probes() or get_probegroup()

question is how should I go about drift correction with probe groups

**Comment by samuelgarcia** [comment]
Hi,
You will need to split you recording by probe and handle the motion per sub recording with a unique probe.
The issue around each probe could have different motion!! So this is not a limitation by the software it is by design.
