### ISSUE TITLE
Cannot set batch size in Kilosort 4

### ISSUE THREAD

**Issue by KamranHussain05** [SpikeInterface/spikeinterface#2591]
Hello. I'm trying to run the SpikeInterface pipeline with Kilosort 4 for spike sporting and I'm unable to pass through the [batch size ](https://github.com/MouseLand/Kilosort/blob/4fcae998f6dc39e68cee62c52e47cf018325da17/kilosort/parameters.py#L42) parameter even though it exists in Kilosort. In the SpikeInterface version of [KS4](https://github.com/SpikeInterface/spikeinterface/blob/a85f8acfac91c9fc4917cb0de0d3be16ab96e0b7/src/spikeinterface/sorters/external/kilosort4.py#L20), there is no batch_size parameter at the moment and no way to pass that parameter to the algorithm.

**Comment by alejoe91** [comment]
Hi @KamranHussain05 

We'll add it, it probably got lost during the porting.

Cheers
Alessio

**Comment by KamranHussain05** [comment]
Thank you!
