### ISSUE TITLE
Questions about the sorting analyzer

### ISSUE THREAD

**Issue by Antho2422** [SpikeInterface/spikeinterface#2629]
Hi all, 

I am performing the switch on my pipeline to the **SortingAnalyzer object** instead of WaveformsExtractor and I have some questions on it.

1. Does all the methods related to the waveforms/templates disapeared ? In other terms there is no way to retrieve a template from a specific unit by doing `waveforms.get_unit_template(unit_id=x)` ? 
2. Same question for the mode of the template ("std", "mean"...)
3. I also encountered a bug when computing isi_histograms (I can of course provide more context if needed but I am trying here just in case if it is something known). I get this numba error : `TypeError: No matching definition for argument type(s) array(int64, 2d, C), array(int64, 1d, C), array(int32, 1d, C), array(int32, 1d, C)` on line 149 of `isi.py` file. 
4. I also have questions on the fast_templates and it's difference with the "classic" templates

Sorry for all the questions, 

Hope it is clear enough
Cheers, 
Anthony

**Comment by samuelgarcia** [comment]
Salut Anthony,
1. and 2.
```python
ext = analyzer.get_extension("templates")
templates_average = ext.get_templates(unit_ids=..., operator="average")
templates_std = ext.get_templates(unit_ids=..., operator="std")
```

3. oups @DradeAW @chrishalcrow : could you have a look ?

4. The fast template do not extract waveforms but directly compute the average (and soon the std) on the fly which is a bit faster and use less memory. But this prevent to make percentile and median estimation.

**Comment by h-mayorquin** [comment]
@Antho2422 
For number 3, this seems like a bug. Can you open another issue with your setup (the code that you run) and the full trace?

**Comment by alejoe91** [comment]
> 4. The fast template do not extract waveforms but directly compute the average (and soon the std) on the fly which is a bit faster and use less memory. But this prevent to make percentile and median estimation.

https://github.com/SpikeInterface/spikeinterface/pull/2623

**Comment by chrishalcrow** [comment]
> 3\. I also encountered a bug when computing isi_histograms (I can of course provide more context if needed but I am trying here just in case if it is something known). I get this numba error : `TypeError: No matching definition for argument type(s) array(int64, 2d, C), array(int64, 1d, C), array(int32, 1d, C), array(int32, 1d, C)` on line 149 of `isi.py` file.

There was a similar bug for the correlogram computation, so I think I know what's up. I'll look into it properly tomorrow morning.

**Comment by samuelgarcia** [comment]
merci à tous.

**Comment by h-mayorquin** [comment]
I think this should add evidence that "templates" and "fast-templates" are not great names  Do we have the former for back compatibility or is mean to remain there to stand for "compute the templates through the storage of the waveforms"?

**Comment by zm711** [comment]
Maybe this can be a debate for a different issue, but `template` really has two meanings (in my experience)
1) An idealized extracellular potential pulled from a pool of possibilities (ie we already know how a type of neurons fires from old single cell recordings so we label that as like a cortical pyramidal cell so now apply that to new data)
2) Some sort of statistical measure (typically an average) of a bunch of waveforms

So I agree with @h-mayorquin that template and fast-template aren't super clear in that sense. What does it mean to do fast template (ie it's faster because of how it is calculated but that doesn't tell the end user what the actual difference is between the calculations). Probably just something we need to clearly put in the docs/docstrings.

My reading (if I were naive) would be slow, but accurate vs fast but less accurate.

**Comment by alejoe91** [comment]
Good point. Here's a proposal:

we keep only one `ComputeTemplates` extension which:
- if `waveforms` are available, computes templates from them (and has the option to do `median` and `percentile`)
- if `waveforms` are not available, it computes fast templates

**Comment by samuelgarcia** [comment]
I undersyand that it is not super about the naming but with this kind of solutions we will loose the ability to compute median and/or percentile on demand for plotting.
Lets maturate this.

**Comment by zm711** [comment]
With the merge of #2680, the `template` has been unified. I think all other issues have been addressed. Feel free to open more issues in the future if needed.
