### ISSUE TITLE
Key error when loading extension "amplitude_scalings"

### ISSUE THREAD

**Issue by Antho2422** [SpikeInterface/spikeinterface#2634]
Hi, 

I get this key error on "amplitude_scaling" when trying to load a saved SortingAnalyzer with extensions. 
```
--> sortinganalyzer.py:139: return SortingAnalyzer.load(folder, load_extensions=load_extensions, format=format)

--> sortinganalyzer.py:257: sorting_analyzer.load_all_saved_extension()

--> sortinganalyzer.py:993: self.load_extension(extension_name)

--> sortinganalyzer.py:978: extension_class = get_extension_class(extension_name)

-> sortinganalyzer.py:1112: ext_class = extensions_dict[extension_name]

KeyError: 'amplitude_scalings'
``` 

I cannot figure out what is the issue... It is probably happening too with all the other extensions I guess

If somebody knows I would be grateful !

Thanks, 
Anthony

**Comment by alejoe91** [comment]
Hi @Antho2422 

You previously computed the `amplitude_scalings` extension, right?

**Comment by Antho2422** [comment]
Yes, I also have the corresponding folder 

![image](https://github.com/SpikeInterface/spikeinterface/assets/98460480/59d45f9f-10c9-481b-9db1-0761aaed9d6d)

**Comment by zm711** [comment]
This happened to me once when I updated the code mid analysis. Restarting my kernel and then doing the loading worked for me. The dictionary is made at first import and isn't updated so I think that causes this issue.

**Comment by Antho2422** [comment]
@zm711 It worked, thank you for the suggestion. I did not think this could be the issue

**Comment by zm711** [comment]
Not sure how to fix this issue or if it is fixable with the current codebase, but yeah if you get errors like that I would recommend just restarting the kernel while we keep trying to polish the analyzer code.

**Comment by alejoe91** [comment]
Yeah I don't think this can be fixed, since it's a problem (?) of the registration of extensions.

Thansk Zach for figuring this out!
