### ISSUE TITLE
[SpikeGLX] Support for NP Ultra variant

### ISSUE THREAD

**Issue by CodyCBakerPhD** [SpikeInterface/spikeinterface#2653]
Upstream: https://github.com/NeuralEnsemble/python-neo/issues/1451

Downstream: https://github.com/NeurodataWithoutBorders/nwb-guide/issues/713

**Comment by zm711** [comment]
We merged 1451 from Neo so I'll close this one. Feel free to reopen if there is an issue we are missing.
