### ISSUE TITLE
curation and neurons' index

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [SpikeInterface/spikeinterface#2657]
Hi,
I followed the curation tutorial, and used analyzer.select_units(analyzer.unit_ids[keep_mask], format="binary_folder", folder=path_curated). This worked well, and I obtained a new path_curated folder including all the extensions, as well as a spikes.npy file inside the path_curated/sorting folder. However, I noticed that the concatenated spikes in path_curated/sorting/spikes.npy are indexed from 0 to total_neurons_after_curation-1, while in the extensions (such as metrics.csv inside path_curated/extensions/template_metrics), the neurons retained their original indexes.

Is there a straight forward way to match the neurons_index of path_curated/sorting/spikes.npy with the indexes of neurons in the path_curated/extensions/? For instance, would it be correct to jusr reassign indexes from 0:total_neurons_after_curation-1 to the indexes in the extensions files?
Thanks for your help!

**Comment by alejoe91** [comment]
Hi @sofiapuvogelvittini 

Yes! The `spikes.npy` has `unit_index`, which is the index of a unit ID among all unit IDs.

To go from unit index to unit ID (in the csv table), you can simply do:
```
sorting.unit_ids[unit_index]
```
The other way around (from ID to index):
```
sorting.id_to_index(unit_id)
```

**Comment by sofiapuvogelvittini** [comment]
thanks!
