### ISSUE TITLE
Problem reading legacy OpenEphys format file 

### ISSUE THREAD

**Issue by ToGauvrit** [SpikeInterface/spikeinterface#266]
Hi,
I think the problem come from here:

```
def read_openephys(folder_path, **kwargs):
    """
    Read 'legacy' or 'binary' Open Ephys formats

    Parameters
    ----------
    folder_path: str or Path
        Path to openephys folder

    Returns
    -------
    recording: OpenEphysLegacyRecordingExtractor or OpenEphysBinaryExtractor
    """
    # auto guess format
    files = [str(f) for f in Path(folder_path).iterdir()]
    if np.any([f.startswith('Continuous') for f in files]):
        #  format = 'legacy'
        recording = OpenEphysLegacyRecordingExtractor(folder_path, **kwargs)
    else:
        # format = 'binary'
        recording = OpenEphysBinaryRecordingExtractor(folder_path, **kwargs)
    return recording

```
The var files is a list of path and not just name of files. So the startswith cannot find any file beginning by 'Continuous' and it's always new binary format that is triggered. 
I find a way to solve this like this:
`if np.any([f.startswith('Continuous',len(folder_path)+1) for f in files]):`

Thank you,

Théo

**Comment by samuelgarcia** [comment]
I think the bug `startswith()` should be `endswith()` no ?
could you try it ?

**Comment by ToGauvrit** [comment]
It's working too with endswith and 'continuous' with a 'c' in a lower case. I couldn't test with the new binary format but I think there is no files ending with continuous, no?
`if np.any([f.endswith('continuous') for f in files]):`

**Comment by samuelgarcia** [comment]
Yes the new binary don't have this "*.continuous" files.
Could try a PR ?

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/269
