### ISSUE TITLE
question about spikeinterface.curation.remove_redundant_units

### ISSUE THREAD

**Issue by JuanPimientoCaicedo** [SpikeInterface/spikeinterface#2660]
Hello,

I am wondering how the process of removing redundant units is. do you consider all the matching spikes of every unit and or template similarity?

I am asking this because I am worried that if somehow two units that appear in different channels share similar spike times (because of common input or something like that), one of those would be eliminated just taking into consideration spike times.

Thank you for your time!

**Comment by zm711** [comment]
As far as I can see it seems to be based on time only so that could lead to one of those being dropped, but let me bring back in @alejoe91 and @samuelgarcia for this question. Does remove_redundant_unit use sparsity or channel_position? Or just times. It's pretty nested code that I haven't dug into as much so I couldn't find that it used the location of the unit to help with the calculation.

**Comment by samuelgarcia** [comment]
`remove_redundant_units()` is based on `find_redundant_units()` which is based on `compare_two_sorters()` which is the spike time comparison with the agreement matrix machinery.
So **time only**.

**Comment by chiyu1203** [comment]
Hi @alejoe91, just for confirmation, so what is the most accurate way to use this function (my project is about decoding single units activity for certain sensory or motor events)? Similar to @JuanPimientoCaicedo's concern, if those units are from different depth then I would probably treat them as two different units. In my case, Kilosort4 sorted out units from the same channel and depth and similar time. For example, these three units were considered to be redundant of each others by `find_redundant_units()`. However, two of them (red and green) shared the same time but the blue only has similar temporal profile. Did these redundant units come from repeated detection or over-splitting of the unit?
![Image](https://github.com/user-attachments/assets/b58f72a0-00c4-4f1e-89e8-492ce455c73c)
My intuition is to merge them manually but  
on the hands-on [tutorial](https://youtu.be/pHze_8s4Qak?si=DXYDGwLmgpVpWp3a&t=6082), it seems that we should remove one of them?! 

> `remove_redundant_units()` is based on `find_redundant_units()` which is based on `compare_two_sorters()` which is the spike time comparison with the agreement matrix machinery. So **time only**.
