### ISSUE TITLE
singularity_image is not working in windows due to 'pwd' package

### ISSUE THREAD

**Issue by alirza67** [SpikeInterface/spikeinterface#2678]
Hi there,
I was trying to use singularity_image as follows:
sorting = si.run_sorter('kilosort3', rec, output_folder=base_folder +'/KS3out',
                        docker_image=False, verbose=True,singularity_image=True)

I noticed the code uses the 'pwd' Python module, which is unavailable on Windows (below is the error).
I appreciate any help on this.

Thanks in advance.

______________________
installation_mode='auto' switching to installation_mode: 'dev'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[56], line 1
----> 1 sorting = si.run_sorter('kilosort3', rec, output_folder=base_folder +'/KS3out',
      2                         docker_image=False, verbose=True,singularity_image=True)

File \\srv9021\saeedi\spikeinterface\src\spikeinterface\sorters\runsorter.py:169, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, delete_container_files, with_output, **sorter_params)
    167         else:
    168             container_image = singularity_image
--> 169     return run_sorter_container(
    170         container_image=container_image,
    171         mode=mode,
    172         **common_kwargs,
    173     )
    175 return run_sorter_local(**common_kwargs)

File \\srv9021\saeedi\spikeinterface\src\spikeinterface\sorters\runsorter.py:457, in run_sorter_container(sorter_name, recording, mode, container_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, delete_container_files, extra_requirements, installation_mode, spikeinterface_version, spikeinterface_folder_source, **sorter_params)
    454     py_user_base_folder.mkdir(parents=True, exist_ok=True)
    455     py_user_base_unix = path_to_unix(py_user_base_folder)
--> 457 container_client = ContainerClient(mode, container_image, volumes, py_user_base_unix, extra_kwargs)
    458 if verbose:
    459     print("Starting container")

File \\srv9021\saeedi\spikeinterface\src\spikeinterface\sorters\container_tools.py:101, in ContainerClient.__init__(self, mode, container_image, volumes, py_user_base, extra_kwargs)
     99 elif mode == "singularity":
    100     assert self.py_user_base, "py_user_base folder must be set in singularity mode"
--> 101     from spython.main import Client
    103     # load local image file if it exists, otherwise search dockerhub
    104     sif_file = Client._get_filename(container_image)

File ~\AppData\Local\anaconda3\Lib\site-packages\spython\main\__init__.py:77
     72     cli.instance.version = cli.version
     74     return cli
---> 77 Client = get_client()

File ~\AppData\Local\anaconda3\Lib\site-packages\spython\main\__init__.py:19, in get_client(quiet, debug)
      8 def get_client(quiet=False, debug=False):
      9     """
     10     get the client and perform imports not on init, in case there are any
     11     initialization or import errors.
   (...)
     17 
     18     """
---> 19     from .base import Client as client
     21     client.quiet = quiet
     22     client.debug = debug

File ~\AppData\Local\anaconda3\Lib\site-packages\spython\main\base\__init__.py:9
      1 # Copyright (C) 2017-2022 Vanessa Sochat.
      2 
      3 # This Source Code Form is subject to the terms of the
      4 # Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
      5 # with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
      8 from spython.logger import bot
----> 9 from spython.utils import check_install, get_singularity_version
     11 from .command import generate_bind_list, init_command, run_command
     12 from .flags import parse_verbosity

File ~\AppData\Local\anaconda3\Lib\site-packages\spython\utils\__init__.py:3
      1 from .fileio import mkdir_p, read_file, read_json, write_file, write_json
      2 from .misc import ScopedEnvVar
----> 3 from .terminal import (
      4     check_install,
      5     format_container_name,
      6     get_installdir,
      7     get_singularity_version,
      8     get_userhome,
      9     get_username,
     10     remove_uri,
     11     run_command,
     12     split_uri,
     13     stream_command,
     14 )

File ~\AppData\Local\anaconda3\Lib\site-packages\spython\utils\terminal.py:12
      1 """
      2 
      3 # Copyright (C) 2017-2022 Vanessa Sochat.
   (...)
      8 
      9 """
     11 import os
---> 12 import pwd
     13 import re
     14 import shlex

ModuleNotFoundError: No module named 'pwd'

**Comment by alejoe91** [comment]
Singularity is only supported on Linux machines. For Windows, you have to use Docker :)
