### ISSUE TITLE
Visualizing Kilosort Preprocessed Waveforms in Phy

### ISSUE THREAD

**Issue by asadian98** [SpikeInterface/spikeinterface#2686]
Hello, 

I've been working with Kilosort2 through SpikeInterface, using raw signals as my input. 
I'm looking to extract waveforms for visualization in Phy, but I'm wondering if there's a way to directly observe the waveforms as they are after Kilosort's preprocessing. 
Currently, I preprocess the signal on my own and then run waveform extraction based on the spike times identified by Kilosort. My aim is to view the waveforms in the exact manner they are produced by Kilosort.

Thank you in advance

**Comment by alejoe91** [comment]
Hi @asadian98 

We recently discussed about this topic: #2650

**Comment by asadian98** [comment]
Thanks!
