### ISSUE TITLE
Unsupported operand type(s) after upgrading from Kilosort 4.0 to 4.0.3

### ISSUE THREAD

**Issue by gkBCCN** [SpikeInterface/spikeinterface#2688]
I'm using SpikeInterface to sort with Kilosort 4.0 and had success running the preprocessing, sorting, and analysis steps, but when I tried to open the results in Phy I got the dreaded QtWidgets error.  This error was fixed by the Kilosort team in version 4.0.3.  After reinstalling, if I run Kilosort from the GUI, everything works fine.  However, if I run it from the SpikeInterface pipeline, I get this error:

> File "/home/user/miniconda3/envs/spikeinterface/lib/python3.9/site-packages/kilosort/spikedetect.py", line 98, in template_centers
>     nx = np.round((xmax - xmin) / (dminx/2)) + 1
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

I've encountered this error on multiple systems (Windows, Ubuntu) and with multiple datasets.

**Comment by alejoe91** [comment]
Are there release notes somewhere for KS4?

**Comment by gkBCCN** [comment]
Not that I know of.  I opened an issue in the KS GitHub.

**Comment by gkBCCN** [comment]
Jacob added the release notes a couple hours ago: https://github.com/MouseLand/Kilosort/releases/tag/v4.0.3

**Comment by zm711** [comment]
I know what the problem is (I think)!

They changed the default for dminx to be 32. Our default is None. @gkBCCN could you try running specifying for the dminx as 32 in spikeinterface.
