### ISSUE TITLE
`ProcessPoolExecutor` hanging in `compute_principal_components` and `compute_quality_metrics`

### ISSUE THREAD

**Issue by louiskang** [SpikeInterface/spikeinterface#2689]
Starting from version 0.100.0, execution of `compute_principal_components` sometimes and `compute_quality_metrics` always (when requesting PCA metrics) hang at 0% when I use `n_jobs > 1`. To work around this, I have reverted portions of these functions involving  `ProcessPoolExecutor` to their 0.99.1 versions that instead use `joblib` with appropriate changes to upstream functions. This allows me to use parallel processing with version 0.100.5.

Is anyone else experiencing a similar issue? I'm using Ubuntu 20.04.5 LTS and python 3.10.14.

**Comment by samuelgarcia** [comment]
Hi thank you for the feedback.
This is annoying.
@alejoe91 refactored it for version 0.100 but now I have refactored even more for the SortingAnalyzer.

Does this works for the main branch ? Note that using the main branch involce the analyze change...
https://spikeinterface.readthedocs.io/en/latest/how_to/waveform_extractor_to_sorting_analyzer.html

**Comment by louiskang** [comment]
Thanks for the suggestion, unfortunately the main branch (v0.101.0) gives me errors for `create_sorting_analyzer` so I can't test the PCA parallelization.

With the keyword argument `sparse=True`, I see
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <timed exec>:18

File /data/louis/Neuropixels/SpikeInterface/spikeinterface-0.101.0/src/spikeinterface/core/sortinganalyzer.py:117, in create_sorting_analyzer(sorting, recording, format, folder, sparse, sparsity, overwrite, **sparsity_kwargs)
    113     assert np.array_equal(
    114         recording.channel_ids, sparsity.channel_ids
    115     ), "create_sorting_analyzer(): if external sparsity is given unit_ids must correspond"
    116 elif sparse:
--> 117     sparsity = estimate_sparsity(recording, sorting, **sparsity_kwargs)
    118 else:
    119     sparsity = None

File /data/louis/Neuropixels/SpikeInterface/spikeinterface-0.101.0/src/spikeinterface/core/sparsity.py:593, in estimate_sparsity(recording, sorting, num_spikes_for_sparsity, ms_before, ms_after, method, peak_sign, radius_um, num_channels, **job_kwargs)
    589 from .template import Templates
    591 assert method in ("radius", "best_channels"), "estimate_sparsity() handle only method='radius' or 'best_channel'"
--> 593 if recording.get_probes() == 1:
    594     # standard case
    595     probe = recording.get_probe()
    596 else:
    597     # if many probe or no probe then we use channel location and create a dummy probe with all channels
    598     # note that get_channel_locations() is checking that channel are not spatialy overlapping so the radius method is OK.

AttributeError: 'KiloSortSortingExtractor' object has no attribute 'get_probes'
```

I then tried `sparse=False`, which produces
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File <timed exec>:18

File /data/louis/Neuropixels/SpikeInterface/spikeinterface-0.101.0/src/spikeinterface/core/sortinganalyzer.py:121, in create_sorting_analyzer(sorting, recording, format, folder, sparse, sparsity, overwrite, **sparsity_kwargs)
    118 else:
    119     sparsity = None
--> 121 sorting_analyzer = SortingAnalyzer.create(sorting, recording, format=format, folder=folder, sparsity=sparsity)
    123 return sorting_analyzer

File /data/louis/Neuropixels/SpikeInterface/spikeinterface-0.101.0/src/spikeinterface/core/sortinganalyzer.py:219, in SortingAnalyzer.create(cls, sorting, recording, format, folder, sparsity)
    205 @classmethod
    206 def create(
    207     cls,
   (...)
    217 ):
    218     # some checks
--> 219     assert sorting.sampling_frequency == recording.sampling_frequency
    220     # check that multiple probes are non-overlapping
    221     all_probes = recording.get_probegroup().probes

AssertionError: 
```

I get these errors for both Kilosort 4 and the Kilosort 2.5 singularity container.

**Comment by alejoe91** [comment]
How are you creating the sorting analyzer?

**Comment by louiskang** [comment]
Ah thanks for pointing that out! I swapped my recording and sorting because I didn't use keyword arguments for them.

Now `create_sorting_analyzer()` seems to work; I call it as follows:
```
analyzer = sf.create_sorting_analyzer(sorting=sorting, recording=filtered,
                                      format='binary_folder', folder=analyzer_path,
                                      sparse=True, n_jobs=8)
```

I now have narrowed down the problem a bit further. It seems that the hang only occurs during or after the second time a parallelized `analyzer.compute()` is called, and somehow it's worse for ipynb notebooks (I'm using VSCode) and for more jobs.

For example, the following works for `.ipynb` notebooks and `.py` scripts:
```
analyzer.compute('random_spikes')
analyzer.compute('waveforms')
analyzer.compute('templates')
analyzer.compute('principal_components', n_jobs=8)
```
The following also works for `.ipynb` notebooks and `.py` scripts:
```
analyzer.compute('random_spikes')
analyzer.compute('waveforms', n_jobs=2)
analyzer.compute('templates')
analyzer.compute('principal_components', n_jobs=2)
```

The following hangs on computing principal components for `.ipynb` notebooks, but it works for `.py` scripts
```
analyzer.compute('random_spikes')
analyzer.compute('waveforms', n_jobs=8)
analyzer.compute('templates')
analyzer.compute('principal_components', n_jobs=8)
```
And the following hangs on computing quality metrics even for `.py` scripts:
```
analyzer.compute('random_spikes')
analyzer.compute('waveforms', n_jobs=2)
analyzer.compute('templates')
analyzer.compute('principal_components', n_jobs=2)
analyzer.compute('noise_levels')
analyzer.compute('correlograms')
analyzer.compute('quality_metrics', n_jobs=2)
```
So it appears that notebooks hang on the second parallelized `analyzer.compute()` and scripts hang on the third. To be clear, "hang" for me means that the progress bar doesn't change for a long time and the CPUs show no usage. I've also tried using `format='memory'` for `create_sorting_analyzer()` with the same outcome. Interestingly, `analyzer.compute()` doesn't mind that I run other functions beforehand in parallel, like `create_sorting_analyzer()`,  and `recording.save()`

**Comment by alejoe91** [comment]
I think it could be due to running the notebook in VS code. Can you try to run the notebook directly in jupyter?

**Comment by louiskang** [comment]
Cool, I tried a `.ipynb` notebook in Jupyter, and it reproduces the behavior of `.py` scripts. So it finally fails when computing quality metrics in parallel.

**Comment by zm711** [comment]
I'm just going to add myself to this. One of my labmates' computers (and only one) seems to hang as well for parallelization. (She runs an ipython kernel only) and as you guys know its Windows (but she has Windows 11, python 3.11.x). I installed from source and tried to doublecheck the packages. I've tried reinstalling multiple times. But just on her computer it's not working. So if you figure anything out I would love to know so I can help her troubleshoot more. (in particular she fails when trying to write a binary file, but seems to fail even if I set jobs to n_jobs = 1 so it might not be the parallelization per se that is the problem).

**Comment by louiskang** [comment]
Thank you all for your help. If anyone has a Linux installation in which parallelization seems to work fine, could you post the environment `.yml` file, for example, via `conda env export`? This way I can try the same installation to see if it works for me.

**Comment by zm711** [comment]
Trying to bring this back could we also just see all the packages you have in your env? 

`conda list` or whatever you use. And how are you actually calling python? Only through jupyter or are you trying an IDE. People in my lab like using Spyder, but I found out for the Windows 11, python 3.11 person above that Spyder was the problem. If she runs the code from an ipython session directly then the parallelization works fine. So maybe there is a problem with how your IDE is calling python?

**Comment by louiskang** [comment]
Thank you all for your help--I believe it's solved! This last comment made me reconsider my installation. I was experiencing the error even when running scripts from the command line with `python SCRIPT.py`. The source of the error is that I'm using the Intel Math Kernel Library (MKL) version of BLAS, which can greatly speed up linear algebra computation for Intel CPUs. However there are some conflicts with parallel processing. I followed the tips at [https://github.com/numpy/numpy/issues/11734](url), and running
```
MKL_THREADING_LAYER=TBB python SCRIPT.py
```
worked for me. Somehow it changes how MKL creates threads for parallel processing...

I could add this environmental variable to my conda environment with `conda env config vars set MKL_THREADING_LAYER=TBB`, so I don't need to set it every time while running a script. That way parallel processing works even in VS Code with ipynb notebooks.

I would recommend trying MKL if you have an Intel CPU with many cores--it reduces my PCA computation time 100x from 9 minutes to 5 seconds (on a Linux server). I do this with `conda create -n NAME python=3.XX numpy "libblas=*=*mkl"` and then installing spikeinterface, kilosort, and pandas with pip as instructed. I use the conda-forge channel.

I'm quite satisfied with the result, so I'll boldly close this issue. Thank you all again for your time!

**Comment by louiskang** [comment]
Oops here we go

**Comment by zm711** [comment]
@alejoe91, do you think we should have some sort of docs or notes about this. Seems like a rare, deep problem that is going to be really hard for us to diagnose if other people have this issue so we could always just say try this solution if multiprocessing doesn't work. This doesn't seem to be the problem for my lab, but it is valuable for people overall.

**Comment by alejoe91** [comment]
Maybe a dedicated "Troubleshooting" page in the docs?
