### ISSUE TITLE
kilosort4: skip_kilosort_preprocessing

### ISSUE THREAD

**Issue by sachuriga283** [SpikeInterface/spikeinterface#2697]
Dear,

I have trying to run some test on kilosort4, and since I'm not using neuropixel so I would like to skip the preprocess of kilosort. 
But I'm wondering, does `skip_kilosort_preprocessing` skip the high-pass filtering, CAR, and whitening steps?

best,

**Comment by zm711** [comment]
Hey @sachuriga283,

Here are all the params:
https://github.com/SpikeInterface/spikeinterface/blob/bbe871993954fde757034bbab98f7c4c788ead7d/src/spikeinterface/sorters/external/kilosort4.py#L57-L91

to skip CAR you would need to do: `do_CAR=False`

To skip highpass filtering and whitening you would do `skip_kilosort_preprocesing`.

**Comment by sachuriga283** [comment]
OK, thanks

**Comment by zm711** [comment]
Feel free to open new issues if you run into any problems :)
