### ISSUE TITLE
Examples are no longer notebooks

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeinterface#27]
So we deleted all the examples that were originally notebooks. Are we ok with not having any notebook examples? Do you think it would make sense to have those as well?

**Comment by samuelgarcia** [comment]
I think in spiketutorial, we can have notebook.
git history with notebook can be quite heavy so it is better to not include then in our code pacakge

The very best is to add example in spikeinterface/example/*.py with scripts that generate notebook, have a look it is very straigthforward.





.
