### ISSUE TITLE
Drift correction of broadband stream

### ISSUE THREAD

**Issue by JuanPimientoCaicedo** [SpikeInterface/spikeinterface#2749]
Hello, 

I am currently working with broadband data recorded with Neuropixel probes and I am wondering if interpolating the motion in a broadband stream is wrong.

To give you some perspective, I follow the instructions to estimate the motion in a recording:

1. Demux the data
2. apply bandpass filter
3. Use common median reference (CMR)

Then, I use the motion estimation to interpolate motion in the broadband stream. 

Here you have the general code that I use:

```
recording = si.read_spikeglx(folder_path=base_folder,stream_id='imec0.ap') # Recording object
recording.annotate(is_filtered=False) # Really important step because this data is broadband
recording = si.phase_shift(recording = recording) # demux the data

bad_channel_ids, channel_labels = si.detect_bad_channels(recording=recording)
rec_clean = recording.remove_channels(remove_channel_ids=bad_channel_ids)

# preprocessing: bandpass + cmr


drift_recording_raw = rec_clean
drift_recording_filt = si.filter(recording = drift_recording_raw,band = [300, 6000], btype ='bandpass',
                                 filter_order = 2,ftype = 'butter')  # forward-backward filtering
                                                                     # 0 lag filtering
drift_recording_cmr = si.common_reference(recording = drift_recording_filt, 
                                          reference = 'global', operator ='median')

motion_folder =  Path(base_folder) / 'motion_correction'  
job_kwargs = dict(n_jobs=-1, chunk_duration='1s', progress_bar=True)
rec_corrected = si.correct_motion(recording= drift_recording_cmr, preset="nonrigid_accurate", folder=motion_folder,
                                  **job_kwargs)

# interpolation in the broadband

preprocessed_trace = interpolate_motion(
                  recording=rec_clean,
                  motion=motion_info['motion'],
                  temporal_bins=motion_info['temporal_bins'],
                  spatial_bins=motion_info['spatial_bins'],
                  **motion_info['parameters']['interpolate_motion_kwargs'])

```

I have spike sorted with this data and I have done some waveform analysis and generally speaking it seems to work. I am submitting this issue because to me, the approach I am using is correct. However, I might be doing something fundamentally wrong, because if I am correct, in Windolf2023, the motion estimation from LFP is then corrected in the LFP stream while the motion estimation from the AP stream is used to interpolate AP in the same AP stream.

Thank you for your time and let me know if you need more information regarding this question.

**Comment by cwindolf** [comment]
Hi @JuanPimientoCaicedo, thanks for the question! I don't think there's anything wrong with using the AP-based motion estimate to correct the broadband stream. I think the main reason we didn't do that in the work you reference is because those were NP1 recordings where the AP and LFP band were already separated. And, in that work, we also looked at some applications of using the LFP motion estimate to correct the AP stream.
