### ISSUE TITLE
`setting.json` file not written before `return_scaled` was global for a sortinganalyzer and is now a required file for reloading

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#2788]
Basically now that we set the global state of `return_scaled` for `SortingAnalyzer` an extra file is being written at the root of the analyzer folder called `setting.json`. It contains:

```json
{
    "return_scaled": true
}
```

But this means that if I try to call
```python
analyzer = load_sorting_analyzer(....)
```
I get a file not found because it is looking for this setting file. The easy solution is that I'm just copying the `setting.json` from a more recent analyzer, but do we want to make a full solution or just let people know that they need to do this?

**Comment by samuelgarcia** [comment]
Hi Zach.
For early adopter of SortingAnalyzer, maybe we could add for a while some code like `if settings.json do not exists then create it with a warning`
