### ISSUE TITLE
Should aggregate channels preserve the channel_ids?

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#2789]
The following code fails:

```python
from spikeinterface.core import aggregate_channels

recording1 = generate_recording(num_channels=3, durations=[10], set_probe=False)  # To avoid location check
recording1 = recording1.rename_channels(new_channel_ids=["a", "b", "c"])
recording2 = generate_recording(num_channels=2, durations=[10], set_probe=False)  
recording2 = recording2.rename_channels(new_channel_ids=["d", "e"])

aggregated_recording = aggregate_channels([recording1, recording2])  
assert aggregated_recording.get_num_channels() == 5
assert list(aggregated_recording.get_channel_ids()) == ['a', 'b', 'c', 'd', 'e']

```

The `channel_ids` of the aggregated recording are:

```
[0, 1, 2, 3, 4]
```

I think that the `channel_ids` should be preserved? Thoughts? Unforseen complexities?

**Comment by zm711** [comment]
Could there ever be a case where the channel_ids are ['a', 'b', 'c'] and ['a', 'b'] such that by keeping them you would mess up  the indexing post-aggregating? I'm not sure why this would happen (combining two recordings that shouldn't be combined...?) but that is the only thing I could think of.

**Comment by alejoe91** [comment]
Yes, in that case we should rename channels. IMO, if the channel ids are unique, then we can preserve them

**Comment by samuelgarcia** [comment]
And also the same dtype.
