### ISSUE TITLE
Is there a way to read/convert a .sev file? 

### ISSUE THREAD

**Issue by victornovakov** [SpikeInterface/spikeinterface#2825]
Hi, I apologize if this is an ignorant question, or has a quick solution. I have not been able to find it. 

I have raw electrode channel data in multiple .sev files which I would like to read into kilosort. Is there anyway to read .sev files or is it unsupported. I do not see it listed under supported file types and followed the direction to raise an issue. 

I also have the .sev files converted into a single .mat matlab file if this helps. 

Thank you

**Comment by h-mayorquin** [comment]
For this type of question you should look into the extractors that we support. Check if the following solves supports your files:
 
 https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.extractors.read_tdt

**Comment by h-mayorquin** [comment]
User has mentioned that the current solution in extractors is good enough. Closing this.
