### ISSUE TITLE
Add `is_scaled` to `Templates` object (and zarr representatio)

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#2831]
@h-mayorquin I think we should add a property to the `Templates` object to tell whether the `templates_array` is scaled to uV or not. 

This will be extremely important for hybrid generation. Currently, we are "assuming" that templates in the database are scaled, so my suggestion is to be explicit about it.

Any thoughts?

**Comment by h-mayorquin** [comment]
I think this makes sense.  Is there a situation where we can to deal with raw templates? I am having a hard time imaging this. 

But I think it makes sense. Either that or we add a units property (.e.g "uV", "V" or "raw").

**Comment by samuelgarcia** [comment]
Units is a good idea but if you go there this should be everywhere.
Now scaled = uV in all places.
So lets keep this for now and lets add units everywhere but later.

**Comment by h-mayorquin** [comment]
This makes sense, Sam. I will do it like this.

**Comment by zm711** [comment]
Closed by #2842.
