### ISSUE TITLE
Question about SNR definition

### ISSUE THREAD

**Issue by ZoeChen96** [SpikeInterface/spikeinterface#2832]
Hello,

I am reading your papers of SpikeInterface and SpikeForest and have a question about SNR definition. I have a MEArec dataset , where the noise is 10uVrms and the spike amplitude from 40uV to 300uV. How can I calculate the SNR range for the dataset?

I see there is a definition in SpikeForest paper: 
![image](https://github.com/SpikeInterface/spikeinterface/assets/116095055/99f4bb0c-5866-4e14-b39c-e64e77fc2a9f)

where it mentions that a filter should applied and then the average amplitude divided by the estimated std, which is calculated as (MAD/0.6745). 

Can I just use the amplitude divided by noise std value (as I already know from MEArec) to calculate the SNR range? For example in the aforementioned MEArec dataset, the SNR range would be (4-30), which is (0.60dB-1,48dB)
Why is the weird filter needed?

**Comment by samuelgarcia** [comment]
Hi.
For spikeforest I do not remember @magland could answer this.

For spikeinterface, you can use the `compute_quality_metrics(analyzer, metrics_names=["snr"])`

Internally,it devides the peak amplitude on the max channel by the noise with the formula you mention (MAD/0.6745).

**Comment by magland** [comment]
That is just one example of a filter one could use. We just wanted to be detailed in reporting what was actually done. SNR doesn't need to be estimated in that way. You could use your own filter.

**Comment by ZoeChen96** [comment]
Hi Magland and Samuel, thanks for the reply! I have two more follow-up questions:
1) Can I calculate SNR without filtering? I think we do the filtering, the SNR will increase, as noise is filtered more than signal. 
2) What is the 'peak amplitude'? Is it a peak to peak value, or just single-end (for example the waveform is from -100 to 10, then the signal amplitude is 100 or 110?
Thanks a lot!

**Comment by samuelgarcia** [comment]
> 1. Can I calculate SNR without filtering? I think we do the filtering, the SNR will increase, as noise is filtered more than signal.

On a full band signal the noise level has really a different interpretation! But the amplitude of the peak should be similar.
So the final result should change.

> 2. What is the 'peak amplitude'? Is it a peak to peak value, or just single-end (for example the waveform is from -100 to 10, then the signal amplitude is 100 or 110?

In spikeinterface this is single end. So 100.
Alessio was planning to add an option to have both cases but never did it.

**Comment by ZoeChen96** [comment]
> On a full band signal the noise level has really a different interpretation! But the amplitude of the peak should be similar. So the final result should change.

Yes. this is also what I think. That means the filters chosen will influence the SNR calculation. 
So can we do SNR calculation without filtering, to ensure the noise is not suppressed?

**Comment by magland** [comment]
@ZoeChen96 You need to at least do a high-pass filter (to remove low frequencies)... otherwise the signal maximum (peak amplitude) will be meaningless and the std dev calculation will also not be correct. Whatever you decide for a filter, you should report it.

**Comment by ZoeChen96** [comment]
Hi Magland, thanks for the reply! That's clear now. Thank you very much!
