### ISSUE TITLE
Verbose clashing in `recording.save_to_folder` and `job_kwargs`

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#2847]
As in the title, 

https://github.com/SpikeInterface/spikeinterface/blob/3864afde8aad572041b4218ebb1d50b2e7a58d6b/src/spikeinterface/core/base.py#L849-L850

There is a verbose in `save_to_folder` but it also clashes with the `save_kwargs` which should contain `job_kwargs`. 

Suggestion: drop the verbose in `save_to_folder` or rename it to `print_used_folder` if someone wants that functionality.

I swear I read about a similar issue but could not find it.
[Edit] Yes, it was a PR not an issue:
https://github.com/SpikeInterface/spikeinterface/pull/2602

Also, minimal example:

```python
from spikeinterface.core import generate_recording 

recording = generate_recording(num_channels=3, durations=[10])

from pathlib import Path

folder_path = Path("./test_recording")

job_kwargs={'progress_bar': True, "verbose":True, "n_jobs":2}
recording.save_to_folder(folder=folder_path, verbose=False, overwrite=True, **job_kwargs)   
```

**Comment by zm711** [comment]
Also related #2728, no?

**Comment by samuelgarcia** [comment]
I want to remove verbose from job_kwargs!

**Comment by h-mayorquin** [comment]
> I want to remove verbose from job_kwargs!

What does that mean? Removing the argument from the `ChunkRecordingExecutor`, removing it from global?

**Comment by samuelgarcia** [comment]
from the global because verbose is used randomly at many other place with is not necessarly form parallel stuff.

**Comment by h-mayorquin** [comment]
> from the global because verbose is used randomly at many other place with is not necessarly form parallel stuff.

Got you

**Comment by h-mayorquin** [comment]
But thinking about it, how would that solve the problem in this issue? How would you propagate the verbose all the way down to the initialization of the `ChunkRecordingExecutor` if not in the `job_kwargs`? And as long as that is the way of passing the verbose in the job_kwargs it will clash with the verbose of other signatures.

That seems independent of whether it is set globally or not. Am I missing something? Just thinking aloud here.

**Comment by h-mayorquin** [comment]
I think that to avoid clashing we should just create another variable that is called `parallel_verbose` ...
