### ISSUE TITLE
AttributeError : 'str' object has no attribute 'str'

### ISSUE THREAD

**Issue by ClaraBesserer** [SpikeInterface/spikeinterface#291]
Hello,

I used to run this function to extract waveforms, but since yesterday I'm getting an error.

   waveforms = si.extract_waveforms(rec, sorting, folder=wf_folder,
                load_if_exists=False, ms_before=1., ms_after=2.,
                max_spikes_per_unit=200, dtype=None,
                chunk_size=30000, n_jobs=1, progress_bar=True)

Error message : 

File "/X.py", line 318, in post_processing
 waveforms = si.extract_waveforms(rec, sorting, folder=wf_folder,

File "/Y/spikeinterface/core/waveform_extractor.py", line 524, in extract_waveforms
 we.set_params(ms_before=ms_before, ms_after=ms_after, max_spikes_per_unit=max_spikes_per_unit, dtype=dtype, 

File "Y/spikeinterface/core/waveform_extractor.py", line 161, in set_params
 dtype=dtype_str)

AttributeError: 'str' object has no attribute 'str'

The only change before the appearance of this error was installing the spikeinterface-gui module.
Another thing that changed at the same time were some param names for the BinaryRecordingExtractor function:

BinaryRecordingExtractor(data, num_chan=num_channels, sampling_frequency=sampling_frequency,
                                        dtype=dtype, gain_to_uV=gain, offset_to_uV=channel_offset, time_axis=time_axis)

Where I had to change 'gain' to 'gain_to_uV' and 'channel_offset' to 'offset_to_uV'.
My spikeinterface install dates from july.
My data type is dtype=np.dtype(np.int16)

Thanks in advance,
Clara

**Comment by samuelgarcia** [comment]
Hi Clara. Did you test also with the current master branch to check that bug is still here ?

**Comment by samuelgarcia** [comment]
@alejoe91 : can you handle it befor eth release ?
