### ISSUE TITLE
Add "how to" for how to load your own data as a sorting object

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#2912]
- Minimal requirements (spike_frames, labels, sampling_frequency)
- Describe how to put them on a csv (up to debate) so they can be loaded.

**Comment by zm711** [comment]
Wouldn't it make more sense to just accept a dict or a numpy vector. So we explain how to make the spike dict or the spike vector? And then we could generate a sorting object from that?

**Comment by h-mayorquin** [comment]
Yes, I agree. Good point.
