### ISSUE TITLE
Bug report - incomplete replacing of `output_folder` with `folder` in `run_sorter_container`

### ISSUE THREAD

**Issue by ttngu207** [SpikeInterface/spikeinterface#2965]
Calling `si.sorters.run_sorter()` with either `folder` or `output_folder` input argument resulted in the error below

```
  File "/opt/conda/lib/python3.10/site-packages/element_array_ephys/spike_sorting/si_spike_sorting.py", line 205, in _run_sorter
    si_sorting: si.sorters.BaseSorter = si.sorters.run_sorter(
  File "/opt/conda/lib/python3.10/site-packages/spikeinterface/sorters/runsorter.py", line 179, in run_sorter
    return run_sorter_container(
  File "/opt/conda/lib/python3.10/site-packages/spikeinterface/sorters/runsorter.py", line 383, in run_sorter_container
    in_container_sorting_folder = output_folder / "in_container_sorting"
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

I took a deeper look at the code and it looks like the `output_folder` variable was not fully replaced with the new variable name `folder`

[here ](https://github.com/SpikeInterface/spikeinterface/blob/cac7402cc0fc2351bcb9ecab52e8ce27a0631fa2/src/spikeinterface/sorters/runsorter.py#L383) and [here](https://github.com/SpikeInterface/spikeinterface/blob/cac7402cc0fc2351bcb9ecab52e8ce27a0631fa2/src/spikeinterface/sorters/runsorter.py#L387), and maybe [here](https://github.com/SpikeInterface/spikeinterface/blob/cac7402cc0fc2351bcb9ecab52e8ce27a0631fa2/src/spikeinterface/sorters/runsorter.py#L589)

It may be an easy fix, but I have not forked and tested out the fix

**Comment by alejoe91** [comment]
Thanks for the catch!

**Comment by zm711** [comment]
Could you run from my PR and see if that gets them all?
