### ISSUE TITLE
Error in sorting after SI update: TypeError: unsupported operand type(s) for /: 'NoneType' and 'str' 

### ISSUE THREAD

**Issue by CGonzC** [SpikeInterface/spikeinterface#2967]
Hi @alejoe91 ,

After updating SI from 100.0 to 101.0 I got a problem in the sorting. I am running kilosort3 in Docker . I got the error:

TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

![image](https://github.com/SpikeInterface/spikeinterface/assets/155523434/766608be-07a5-45ad-8306-0da4eee570ce)

Before the update this worked perfectly.

What could be the problem?

Thank you very much in advance

Cristian

**Comment by ttngu207** [comment]
It's likely the same issue as #2965

**Comment by zm711** [comment]
@CGonzC, could you try running from my PR and let me know if that works now with the `folder` argument.

**Comment by CGonzC** [comment]
It works perfectly in Docker!

Thank you very much @zm711 !!!
