### ISSUE TITLE
Spike amplitude data for multi-segments is incorrect

### ISSUE THREAD

**Issue by chrishalcrow** [SpikeInterface/spikeinterface#2975]
When you `get_data` by unit for amplitudes, the sampling is incorrect for multi-segment recordings.

Consider the following code:
```
import spikeinterface.full as si

recording, sorting = si.generate_ground_truth_recording(durations=[10,10], seed=1205)

analyzer = si.create_sorting_analyzer(recording=recording, sorting=sorting)
analyzer.compute(['random_spikes', 'templates', 'spike_amplitudes'])

si.plot_amplitudes(analyzer, segment_index=0)
si.plot_amplitudes(analyzer, segment_index=1)
```
The output for the first plot is
<img width="569" alt="Screenshot 2024-06-05 at 10 29 02" src="https://github.com/SpikeInterface/spikeinterface/assets/57948917/d66c79f8-7ed8-4b62-a6dd-ed4fbd880a05">
This looks good: each unit has amplitudes based around a common mean.

The second plot looks like this
<img width="578" alt="Screenshot 2024-06-05 at 10 29 07" src="https://github.com/SpikeInterface/spikeinterface/assets/57948917/906417c9-caef-4de8-bc87-1b1f137c158f">
This doesn't look good. The amplitudes for each unit are scattered randomly.

Issue is in `_get_data` function for `ComputeSpikeAmplitudes`. I'm working on a fix.

**Comment by samuelgarcia** [comment]
oups. Muts be me during the refactoring.
