### ISSUE TITLE
Is there a widget for plotting the 'peak localisation'?

### ISSUE THREAD

**Issue by JoeZiminski** [SpikeInterface/spikeinterface#2986]
In the handle motion / drift tutorial, [there is a nice peak localisation plot](https://spikeinterface.readthedocs.io/en/stable/how_to/handle_drift.html#plot-peak-localization) that is coded up in the tutorial. I think I also saw this at the workshop. Is this implemented in a widget? If not and people agree it's a good addition, happy to open a PR!

**Comment by zm711** [comment]
This might be it:

https://github.com/SpikeInterface/spikeinterface/blob/a8ed7c8172e11dfd25d716408bc0cd48049dac44/src/spikeinterface/widgets/motion.py#L10

**Comment by alejoe91** [comment]
I think we should split that `plot_motion` widgets. I find it very convenient to plot the rastermaps alone and tweak plotting params

**Comment by JoeZiminski** [comment]
Thanks both! I think that `plot_motion` plots this:
![image](https://github.com/SpikeInterface/spikeinterface/assets/55797454/70c88861-61c5-4ed5-a70c-0adfdc7d95f8)

As far as I know it cannot plot this?

![image](https://github.com/SpikeInterface/spikeinterface/assets/55797454/5c67c16a-0b2d-4280-9937-259b64b01784)

That makes sense to split in some way, maybe it could take an argument to only plot one of the panels if preferred?

**Comment by samuelgarcia** [comment]
I will refator plot_motion along side the Motion obect refactoring.

**Comment by JoeZiminski** [comment]
@samuelgarcia is it correct that there is currently no widget for the peak localisation over the probe plots? If so would it make sense for me to add one?

**Comment by JoeZiminski** [comment]
The tests for this widget will be resurrected after the big `widgets` refactor, can be found [here](https://github.com/SpikeInterface/spikeinterface/pull/3022/commits/7ab068b36bcc55d1efd6966051f54b152c4321e2)
