### ISSUE TITLE
Tests fail with `ModuleNotFoundError: No module named 'spikeextractors'` on 0.10.0

### ISSUE THREAD

**Issue by TheChymera** [SpikeInterface/spikeinterface#299]
This is the full build and test log: https://ppb.chymera.eu/40d6d2.log

Apparently the `spikeextractors` package is deprecated and now the module is distributed via the spikeinterface package. Judging by the log, I would assume this part of the package is not being installed. Any idea how I could do this? Am I using the wrong archive ( https://github.com/SpikeInterface/spikeinterface/archive/refs/tags/0.10.0.tar.gz )? Or should I ammend setup.py to install everything?

**Comment by alejoe91** [comment]
Hi @TheChymera 

How did you install SpikeInterface? In case you want to install version 0.10 you have to specify that: `pip install spikeinterface==0.10.0`

**Comment by TheChymera** [comment]
ok, thank you :)
