### ISSUE TITLE
whiteningRange in external sorter Kilosort2_5

### ISSUE THREAD

**Issue by Djoels** [SpikeInterface/spikeinterface#2995]
For our specific usecases, Kilosort 2.5's whiteningRange parameter - which is currently set fixed to 32.0 - is quite influential in the quality of the spikesort output. 
Having this not fixed to 32 but allowing this to be changed (to for instance 16 or 8) could really help us out.

**Comment by Djoels** [comment]
Adapted the code for this in fork: https://github.com/Djoels/spikeinterface/blob/main/src/spikeinterface/sorters/external/kilosort2_5.py
if this is eligible for a PR, I'll gladly do so.

**Comment by alejoe91** [comment]
Sure! Can you make a PR to add it?
