### ISSUE TITLE
Cannot delete/load spike_locations when templates is missing

### ISSUE THREAD

**Issue by chrishalcrow** [SpikeInterface/spikeinterface#3010]
The extension `spike_locations` relies on template information in its `init`. But spikeinterface initializes extensions when we delete them (when they're saved in a folder). So it's impossible to delete `spike_locations`, meaning it's impossible to do any recomputes on sorting analyzers with `spike_locations`.

Hence the following errors...

```
import spikeinterface.full as si
recording, sorting = si.generate_ground_truth_recording()
sorting_analyzer = si.create_sorting_analyzer(
    recording=recording, 
    sorting=sorting, 
    format="binary_folder", 
    folder="temp_folder",
    overwrite=True
)
sorting_analyzer.compute(["random_spikes", "templates", "spike_locations"])
sorting_analyzer.compute(["random_spikes"])
```

...since the recompute of `random_spikes` first deletes `templates`, then tries to delete `spike_locations`

The problem only occurs for the `spike_locations` extension.

**Comment by zm711** [comment]
I wonder if this has to do with the patch for making sure qc metrics are calculated last? Since this is a child of templates I thought it would've gotten deleted before templates....

**Comment by chrishalcrow** [comment]
> I wonder if this has to do with the patch for making sure qc metrics are calculated last? Since this is a child of templates I thought it would've gotten deleted before templates....

No, it's not about the deletion order. The reason is that currently, we calculate get_template_extremum_channel in the __init__ rather than in the compute (in _get_pipeline_nodes). We shouldn't do this (and don't do it for any other Extension) because we need the __init__ to run, even when we don't have the parents calculated.
