### ISSUE TITLE
spikeinterface_params.json - Mountainsort 5.0 - clarification

### ISSUE THREAD

**Issue by pantelisantonoudiou** [SpikeInterface/spikeinterface#3035]
Hi,

I have a general question regarding the preprocessing steps required before passing data to sorters. It seems like different sorters apply different preprocessing steps to the data. For example, pykilosort does temporal filtering, whitening, and drift correction as far I understand. On the other hand, mountainsort5.0 does no preprocessing and requires the data to be preprocessed (filtering and whitening) before passing them to the sorter according to the their GitHub [repo](https://github.com/flatironinstitute/mountainsort5?tab=readme-ov-file#preprocessing). 

In the spikeinterface_params.json, (created after running mountainsort5.0 in spikeinterface through docker), the `filter` and `whiten` values seem to be always `True` independent of how the data were preprocessed. Therefore, I have the following questions: 

1) Do those parameters indicate how the data have been preprocessed or do they act as flags of the preprocessing steps that need to be applied?

2) If they act as flags how can you tell which variables are used by the sorter and which are there as flags?

Thank you very much for your time,
Pantelis

**Comment by alejoe91** [comment]
Hi @pantelisantonoudiou 

You can check the parameters for MS5 with:
```
ss.get_default_sorter_params("mountainsort5")
```

You can also print the description of each parameter with:
```
ss.get_sorter_params_description("mountainsort5")
```

MS5 can do its own preprocessing. If you have preprocessed the recording already, you can add the arguments `filter=False` and `whiten=False` to the `run_sorter` function.

Note that whitening is highly recommended for MS5!

**Comment by pantelisantonoudiou** [comment]
Thank you for the clarification! It seems like I can pass raw data to both pykilosort and MS5 as they can handle the preprocessing internally.
