### ISSUE TITLE
KS4: initialize_ops() missing 1 required positional argument: 'save_preprocessed_copy'

### ISSUE THREAD

**Issue by JuanPimientoCaicedo** [SpikeInterface/spikeinterface#3050]
Hi, everyone.

I had to update Kilosort4 library in my environment to solve a bug previously  reported in [Kilosort](https://github.com/MouseLand/Kilosort/issues?q=is%3Aissue). Now, it looks like they added a new argument in the [run_kilosort.py](https://github.com/MouseLand/Kilosort/blob/main/kilosort/run_kilosort.py) file. 

![image](https://github.com/SpikeInterface/spikeinterface/assets/148992347/6617b89a-7cbc-4e44-b731-e0aafa23a04e)

Now I am getting this error while using this code:
```
sorting = si.run_sorter(sorter_name = 'kilosort4', recording = recording, 
                        folder = Path('C:/Path/to/Folder/KS4_output'), 
                        do_correction = False, verbose = True, docker_image = False)
```

SpikeSortingError                         Traceback (most recent call last)
Cell In[8], line 3
      1 job_kwargs = dict(n_jobs=-1, chunk_duration='1s', progress_bar=True)
----> 3 sorting = si.run_sorter(sorter_name = 'kilosort4', recording = AP_section, 
      4                         folder = Path('C:/Users/Juan/Downloads/KS4_output'), 
      5                         do_correction = False, verbose = True, docker_image = False)

File ~\spikeinterface\src\spikeinterface\sorters\runsorter.py:185, in run_sorter(sorter_name, recording, folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, delete_container_files, with_output, output_folder, **sorter_params)
    178             container_image = singularity_image
    179     return run_sorter_container(
    180         container_image=container_image,
    181         mode=mode,
    182         **common_kwargs,
    183     )
--> 185 return run_sorter_local(**common_kwargs)

File ~\spikeinterface\src\spikeinterface\sorters\runsorter.py:245, in run_sorter_local(sorter_name, recording, folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, output_folder, **sorter_params)
    243 SorterClass.set_params_to_folder(recording, folder, sorter_params, verbose)
    244 SorterClass.setup_recording(recording, folder, verbose=verbose)
--> 245 SorterClass.run_from_folder(folder, raise_error, verbose)
    246 if with_output:
    247     sorting = SorterClass.get_result_from_folder(folder, register_recording=True, sorting_info=True)

File ~\spikeinterface\src\spikeinterface\sorters\basesorter.py:292, in BaseSorter.run_from_folder(cls, output_folder, raise_error, verbose)
    289         print(f"{sorter_name} run time {run_time:0.2f}s")
    291 if has_error and raise_error:
--> 292     raise SpikeSortingError(
    293         f"Spike sorting error trace:\n{log['error_trace']}\n"
    294         f"Spike sorting failed. You can inspect the runtime trace in {output_folder}/spikeinterface_log.json."
    295     )
    297 return run_time

SpikeSortingError: Spike sorting error trace:
Traceback (most recent call last):
  File "C:\Users\Juan\spikeinterface\src\spikeinterface\sorters\basesorter.py", line 257, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "C:\Users\Juan\spikeinterface\src\spikeinterface\sorters\external\kilosort4.py", line 197, in _run_from_folder
    ops = initialize_ops(settings, probe, recording.get_dtype(), do_CAR, invert_sign, device)
TypeError: initialize_ops() missing 1 required positional argument: 'save_preprocessed_copy'

I suppose it is necessary to add this new argument to your [kilosrt4.py](https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/sorters/external/kilosort4.py) file

Thank you for your help!

**Comment by zm711** [comment]
Hey @JuanPimientoCaicedo, this is on our todo list. There have been a lot of point releases so we are just figuring out the best way to incorporate things. Thanks for the report :)
