### ISSUE TITLE
Bug-fix release 0.100.8

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#3060]
@zm711 @h-mayorquin from various issues we should make a new bug-fix release with:

- Numpy bounds: #3032, #3056
- Kilosort fixes: #3055 (and maybe #3059)

anything else?

**Comment by zm711** [comment]
I think I only have nice, but not crucial PRs
#3037
#2997

Maybe this one is more important because we can't always get multiprocessing working on all OSs all the time. We should allow people to control the `n_jobs` better for sorters? 

#2712

**Comment by alejoe91** [comment]
Done: https://pypi.org/project/spikeinterface/0.100.8/

**Comment by h-mayorquin** [comment]
Yei, thanks man!
