### ISSUE TITLE
Numerous tests fail with `CommandError`? 

### ISSUE THREAD

**Issue by TheChymera** [SpikeInterface/spikeinterface#307]
I am having issues with the spikeinterfaces test suite (part of a larger endeavour to package the spikeinterfaces stack for Gentoo).
Here is the full build and test log: https://ppb.chymera.eu/2967cf.log

While I am not entirely sure regarding the `CommandError`s, this seems to be related to network sandboxing (during build/test/install the project is not allowed to connect to remote hosts in order to avoid code injection). Is there any way to mark all such tests to be skipped?

Another issue I notice is numba, which I believe is a numba issue rather than a spikeinterfaces issue (won't work with current numpy). Since numba looks unlikely to fix this any time soon ( https://github.com/numba/numba/issues/7176 ), and since it is not currently listed as a runtime dependency ( https://github.com/SpikeInterface/spikeinterface/blob/54a864f65c6609606e8640eb3c780cf5c3f049de/requirements.txt ), could its usage for the test suite perhaps be avoided?

**Comment by TheChymera** [comment]
@samuelgarcia I understand, and thank you for helping out with this :)
Is there anything else to be done about the `CommandError`s?

**Comment by samuelgarcia** [comment]
Looking more closely to your log.
Errors come from datalad which is a tool we use on top of git-annex to retrieve public dataset.
I will implement a more simple downloder http based only very soon. Maybe this CommandErrors is from this.

**Comment by alejoe91** [comment]
@TheChymera any luck with this? Can you try the latest release (0.93)?

**Comment by alejoe91** [comment]
Close fo inactivity

**Comment by TheChymera** [comment]
@alejoe91 I tried a number of versions, up to and including the latest `=spikeinterface-0.96.1`.

I keep getting similar errors, which are still coming from datalad, and caused by network sandboxing. Is there any way to auto-disable tests which require network connectivity?
https://ppb.chymera.eu/cc95fe.log

**Comment by TheChymera** [comment]
actually, there might be one test you could help me with, which doesn't look like it's related to network sandboxing (the thing that's actually causing the `datalad` errors). Any idea what this could be about:

```console
================================================================= FAILURES =================================================================
_______________________________________________________ test_collect_sorting_outputs _______________________________________________________

    def test_collect_sorting_outputs():
        working_folder = cache_folder / 'test_run_sorters_dict'
>       results = collect_sorting_outputs(working_folder)

working_folder = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')

spikeinterface/sorters/tests/test_launcher.py:203:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
spikeinterface/sorters/launcher.py:414: in collect_sorting_outputs
    for rec_name, sorter_name, sorting in iter_sorting_output(working_folder):
        results    = {}
        working_folder = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')
spikeinterface/sorters/launcher.py:402: in iter_sorting_output
    for rec_name, sorter_name, output_folder in iter_working_folder(working_folder):
        working_folder = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')
spikeinterface/sorters/launcher.py:380: in iter_working_folder
    for rec_folder in working_folder.iterdir():
        working_folder = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')

    def iterdir(self):
        """Iterate over the files in this directory.  Does not yield any
        result for the special paths '.' and '..'.
        """
>       for name in self._accessor.listdir(self):
E       FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict'

self       = PosixPath('/var/tmp/portage/dev-python/spikeinterface-0.96.1/work/spikeinterface-0.96.1/test_folder/sorters/test_run_sorters_dict')

/usr/lib/python3.10/pathlib.py:1017: FileNotFoundError
```
