### ISSUE TITLE
Expose `unit_params_range` in test file generation

### ISSUE THREAD

**Issue by JoeZiminski** [SpikeInterface/spikeinterface#3077]
There is a cool argument to `generate_ground_truth_recording()` called `unit_params_range` that should sent the bounds of the template shapes. However as far as I can tell it is not actually linked up to anything. A solution would be to take `unit_params_range` as an argument [here](https://github.com/SpikeInterface/spikeinterface/blob/d963aa26e31a9b6bc0bea2a4973f76d4dbafb062/src/spikeinterface/core/generate.py#L1408) and use it as default / update the defaults if it is not empty.

**Comment by samuelgarcia** [comment]
let me check.
I think now unit_params accept all scalar (same for all) or array (one per unit) or tuple (random in a range).
If yes then this unit_params_range became usefull and should be removed.
I am not sure about this
