### ISSUE TITLE
about save_rez_to_mat

### ISSUE THREAD

**Issue by bxy666666** [SpikeInterface/spikeinterface#3107]
I use kilosort2 and set save_rez_to_mat=True,but I can not find any mat:
kilosort2_params['detect_threshold'] = 5  
kilosort2_params['minFR'] = 0.8 
kilosort2_params['minfr_goodchannels'] = 0.8 
kilosort2_params['chunk_duration'] = '1s' 
kilosort2_params[('save_rez_to_mat')] = True
print("Updated Kilosort2 params:", kilosort2_params)

sorting_KS2 = ss.run_sorter(sorter_name="kilosort2", recording=recording_preprocessed, extra_requirements=["numpy==1.26"],
                            docker_image=True, verbose=True, **kilosort2_params)

what should I do?

**Comment by alejoe91** [comment]
Hi, your parameter definition is wrong. Instead of:
`kilosort2_params[('save_rez_to_mat')] = True`

you should use:
`kilosort2_params['save_rez_to_mat'] = True`
(WITHOUT parenthesis!)

**Comment by bxy666666** [comment]
Thanks! I will try it now

> Hi, your parameter definition is wrong. Instead of: `kilosort2_params[('save_rez_to_mat')] = True`
> 
> you should use: `kilosort2_params['save_rez_to_mat'] = True` (WITHOUT parenthesis!)

Thanks! I will try it now

**Comment by bxy666666** [comment]
> Hi, your parameter definition is wrong. Instead of: `kilosort2_params[('save_rez_to_mat')] = True`
> 
> you should use: `kilosort2_params['save_rez_to_mat'] = True` (WITHOUT parenthesis!)

I tried， but still cannot find. This is  my code:
# 获取kilosort2分拣器的默认参数
kilosort2_params = ss.get_default_sorter_params('kilosort2')

# 修改需要的参数
kilosort2_params['detect_threshold'] = 5  # 降低检测阈值
kilosort2_params['minFR'] = 0.8  # 增加最小发放率
kilosort2_params['minfr_goodchannels'] = 0.8  # 增加好的通道的最小发放率
kilosort2_params['chunk_duration'] = '1s'  # 增加数据块时长
kilosort2_params['save_rez_to_mat'] = True
print("Updated Kilosort2 params:", kilosort2_params)


sorting_KS2 = ss.run_sorter(sorter_name="kilosort2", recording=recording_preprocessed, extra_requirements=["numpy==1.26"],
                            docker_image=True, verbose=True, **kilosort2_params)
print(sorting_KS2)




This is my params:
Updated Kilosort2 params: {'detect_threshold': 5, 'projection_threshold': [10, 4], 'preclust_threshold': 8, 'momentum': [20.0, 400.0], 'car': True, 'minFR': 0.8, 'minfr_goodchannels': 0.8, 'freq_min': 150, 'sigmaMask': 30, 'lam': 10.0, 'nPCs': 3, 'ntbuff': 64, 'nfilt_factor': 4, 'NT': None, 'AUCsplit': 0.9, 'wave_length': 61, 'keep_good_only': False, 'skip_kilosort_preprocessing': False, 'scaleproc': None, 'save_rez_to_mat': True, 'delete_tmp_files': ('matlab_files',), 'delete_recording_dat': False, 'n_jobs': 16, 'chunk_duration': '1s', 'progress_bar': True, 'mp_context': None, 'max_threads_per_process': 1}

**Comment by alejoe91** [comment]
also, where are you looking for the `.mat` file? It should be in a folder in your `current director/`kilosort2_outout/sorter_output`

**Comment by bxy666666** [comment]
> what is the error?

I could get other output files，except matlab data. Thanks for your apply
![kilosort](https://github.com/SpikeInterface/spikeinterface/assets/104748303/e1e10f16-7ef6-458c-b1fa-216691696f6a)

**Comment by bxy666666** [comment]
> ahhh! I know what the problem is!
> 
> Can you add this parameter: `kilosort2_params['delete_tmp_files'] = False`

ok, I find that "'delete_tmp_files': ('matlab_files',),", I will change it, Thanks!

**Comment by bxy666666** [comment]
I solved it according to the latest suggestion!
