### ISSUE TITLE
Extracting and saving data for a single unit spike train in a sorting

### ISSUE THREAD

**Issue by AbhiSwamiUConn** [SpikeInterface/spikeinterface#3114]
Is it possible to collect and save to a separate file, every instance of a unit in a recording?  Furthermore, would it be possible to collect the timestamps for each occurrence of that unit?  I notice that there are files that contain these attributes but they appear to store every unit.

**Comment by zm711** [comment]
Not automatically. You could use `to_spike_vector` and from there you could save the equivalent of that if you wanted to.  the spike vector is a numpy array with fields of :

```
Structured numpy array ("sample_index", "unit_index", "segment_index") with all spikes
            Or ("sample_index", "unit_index", "segment_index", "channel_index") if extremum_channel_inds
            is given
```

Then you would just do your own parsing for example:

```python
spike_vector = sorting.to_spike_vector()
times = spike_vector['sample_index']
indices = spike_vector['unit_index']

unit_dict = {}
for index in indices:
    unit_dict[index] = times[indices==index]

# or saving directly
for index in indices:
     np.save(f'spike_times{index}.npy', times[indices==index])
```


or however you prefer to save. I don't think there is a better way, but correct me if someone has something faster.

**Comment by jakeswann1** [comment]
not necessarily faster but:
`
for unit in sorting.get_unit_ids():
    spike_times = sorter.get_unit_spike_train(unit)
    np.save(f'spike_times_{unit}.npy', spike_times)
`
should get you to the same place with a bit less code

**Comment by zm711** [comment]
I even had a typo in mine haha (fixed now).  Agreed with @jakeswann1, I think that is easier to read. I think to_spike_vector should be faster so it depends on whether you want easier to read or speed.

**Comment by h-mayorquin** [comment]
OK, so the answer is yes.
The speed difference probably does not matter here and it won't be in the spike vector favour if the format doesn't have a spike vector already (has the method needs to build it). I recommend that you use `sorting.get_unit_spike_train(unit)` 

If you want the times, you can do `sorting.get_unit_spike_train(unit, return_times=True)`

Can we close this as solved?

**Comment by zm711** [comment]
Just because I believe in profiling let the record show that:

`get_unit_spike_train` is also slightly faster in this case. So it is the better solution for readability and speed. :)
