### ISSUE TITLE
Conda package support

### ISSUE THREAD

**Issue by MarineChap** [SpikeInterface/spikeinterface#312]
Dear, 

Do you have a plan to add spike interface on conda-forge ? 
That would be very practical for the maintenance of conda environment. 

Thanks
Have a good day
Marine 
(fklab-Nerf-Belgium)

**Comment by samuelgarcia** [comment]
Hi Marine.
Honestly, I don't think we will add it soon.
1. It double the package work for devs. Today making a package on pypi is only a tag.
2. pip inside conda is OK for pure python package like spikeinterface, and they can be inside a yml env [file](https://github.com/SpikeInterface/spikeinterface/tree/master/installation_tips).
3. conda can be cool for windows or apple but less usefull on linux. But finally we almost all ends with running sorters on linux.

But if you have motivation to make the conda package and matain it you are welcome.
