### ISSUE TITLE
about unit_colors

### ISSUE THREAD

**Issue by bxy666666** [SpikeInterface/spikeinterface#3137]
Hi, I am now focusing on "w2 = sw.plot_sorting_summary(we_KS2, display=False, curation=True, backend="sortingview")",I want to know which unit uses which color when plotting.  I also add some print sentences in class SortingSummaryWidget(BaseWidget), however nothing print.

**Comment by alejoe91** [comment]
That is controlled by sortingview, so it cannot be changed from SpikeInterface

However, you can RECOLOR units using th "rc" button:
![image](https://github.com/SpikeInterface/spikeinterface/assets/17097257/5de2201d-8885-4a6f-b879-51ea0c35a1ea)

**Comment by bxy666666** [comment]
Oh, I see how it is now. Thanks a lot!
