### ISSUE TITLE
Prepare 0.101.0 release

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#3162]
Check list:

PR: #3163

- [x] version updated in `pyproject.toml`
- [x] `DEV=False` in `__init__.py`
- [x] pip installs from `git` commented out
- [x] full tests passing
- [x] documentation builds
- [x] all documentation tutorials and how tos without errors
- [ ] new functions in API reference
- [x] new features in docs
- [x] README points to new stable documentation
- [x] release notes in `doc/releases`
- [x] summary of release in `doc/whatisnew.rst`
- [ ] All milestone PRs merged

**Comment by zm711** [comment]
I think Joe also mentioned that the `api.rst` is missing some functions. If we are getting the motion stuff into this release then we should probably make sure we get those into `api.rst` See #3083.

**Comment by samuelgarcia** [comment]
oui vraiment.
