### ISSUE TITLE
Bug in `spykingcircus2` sorting processing

### ISSUE THREAD

**Issue by BEGINRX** [SpikeInterface/spikeinterface#3166]
Sorry for the mistake. I'll update the question here. 
When I run sorter "spykingcircus2" with the method "wobble", there is an error.
![image](https://github.com/SpikeInterface/spikeinterface/assets/34244995/498087a7-2ef4-493c-a7c9-2db305b76fad)

The data is my data. There are 2 channels for sorting. Should I do something else to make it sure?

**Comment by yger** [comment]
You can try to switch to the circus-omp-svd method for now, in the merging parameters of spyking-circus2, this should work. I'll try to see what is the bug with wobble

**Comment by BEGINRX** [comment]
Thanks for reply. I have used the circus-omp-svd method to sort. But there also is an error.
![image](https://github.com/SpikeInterface/spikeinterface/assets/34244995/5427d2a8-5657-4d0e-b82c-d8694221fdcf)

Is this because there is something wrong with my data？Would that happen if there were very few spikes in the signal?

**Comment by BEGINRX** [comment]
But there are many spikes detected... 
![image](https://github.com/SpikeInterface/spikeinterface/assets/34244995/0ff07c10-bd90-495a-89e6-37551c61a44b)
