### ISSUE TITLE
What are the units of measurement for the unit_summary widget?

### ISSUE THREAD

**Issue by AbhiSwamiUConn** [SpikeInterface/spikeinterface#3171]
![7](https://github.com/SpikeInterface/spikeinterface/assets/159394395/ce14b799-6448-4843-aee5-00d31f4658df)
I was wondering if I could get some clarification on what units of measurement are being used when creating a unit summary widget through the export_report method.  The axes do not have any labels apart from the numbering system.

**Comment by zm711** [comment]
In general distances will be in um (so your probe map should be um between contacts).

The waveform/amplitude views are either scaled (in uV) or unscaled (in arbitrary units determined by the recording equipment used)

The correlogram view would be in counts x ms (although a y axis might be a nice addition to get rough count numbers :) )

The

**Comment by h-mayorquin** [comment]
Did this answer your question @AbhiSwamiUConn ? I am wondering if we can close this issue as solved.

Also, a somehow unconventional request. Could you star us in github? Like this in the spikeinterface repo

![image](https://github.com/user-attachments/assets/c2ea10f8-c4d2-4d1d-b85c-649b032c9188)


 recently @alejoe91 mentioned that this is useful for us long-term and I hope we have helped you with enough things to earn you good will on this.

**Comment by h-mayorquin** [comment]
Thanks man : )
