### ISSUE TITLE
PhySortingExtractor disagreement between docstring and args

### ISSUE THREAD

**Issue by bendichter** [SpikeInterface/spikeinterface#3201]
The docstring says keep_good_only is default `True` but the args are default is `False`

https://github.com/SpikeInterface/spikeinterface/blob/b3383575feade4bf70d623937d6ea2db9cd05b37/src/spikeinterface/extractors/phykilosortextractors.py#L21-L37

**Comment by zm711** [comment]
Also same for the unit_locations in postprocessing. The docstring says the default is COM when the actual default is monopolar_triangulation. I'll try to patch both of these soon. Unless you wanted to @bendichter?

**Comment by alejoe91** [comment]
I sneaked in a patch in one of the recently merged PRs! 

Fixed on main:
https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/extractors/phykilosortextractors.py#L23

**Comment by zm711** [comment]
I'll close this then. The beauty of the numpydoc string for Chris is it should help us start catching all these mismatches.
