### ISSUE TITLE
How to use given intervals to remove artifacts in Spikeinterface?

### ISSUE THREAD

**Issue by AbhiSwamiUConn** [SpikeInterface/spikeinterface#3207]
I want to utilize the intervals listed in a file's timestamps and remove them from a filtered recording before it gets sorted. The data I am using is in a plexon file. Is it possible to use the events class in spikeinterface to accomplish this? I notice that a structured datatype is required. Where do you find that datatype in the recording?  I would also like to know that if an event is noticed in multiple channels, is it ignored when sorting a recording?  If it is not excluded, can one tell the interface to ignore those periods from the recording entirely so it does not impact the data?  The lab which I am working for utilizes an electric shock, which creates visible artifacts that I have found to affect unit determination.  It would be helpful to have the ability to get rid of those.

**Comment by zm711** [comment]
We are working on finalizing a release so we are a bit slow with issues this week. I'll make sure to ping the team once the release is out to make sure we don't let this fall off our radar :)

**Comment by zm711** [comment]
I see you've changed the title. Alessio included this type of thing in his tutorial during the training. The notebook for removing opto artifacts is here https://github.com/SpikeInterface/SpikeInterface-Training-Edinburgh-May24/blob/main/hands_on/preprocessing/preprocessing.ipynb
and you can also check out the spikeinterface youtube channel where Alessio explains the process.
