### ISSUE TITLE
Set subplot parameters in UnitSummaryWidget

### ISSUE THREAD

**Issue by florian6973** [SpikeInterface/spikeinterface#3222]
Hi!

I am currently using the UnitSummaryWidget that I find very practical, however I noticed that we cannot change the parameters of the subplots like the AmplitudesWidget: in the parameters of the AmplitudeWidget we can change the number of bins but here we do not have access. 
![image](https://github.com/user-attachments/assets/b5c3f195-e0cb-42ed-9213-948b3000ad37)

Could we potentially add to the unit summary widget additional fields to pass parameters to subwidgets please? I can make a small PR if needed. Thanks!

Best,

**Comment by zm711** [comment]
I think this is a great idea. I've been meaning to suggest something like this for a while.  As long as @samuelgarcia or @alejoe91 don't have a reason not to I would say go for the PR. I would definitely use this!

**Comment by alejoe91** [comment]
Yep! Please go ahead with the PR!

**Comment by zm711** [comment]
This is all done so I'll close now :)
