### ISSUE TITLE
Windows Bash execution of MATLAB

### ISSUE THREAD

**Issue by grawoods** [SpikeInterface/spikeinterface#325]
Attempting to use SpikeInterface (and Kilosort3) on a Windows 10 machine and ubuntu. Cannot call instances of matlab from ubuntu since it requires calling matlab.exe.

Was able to get around this issue by editing the source files that execute matlab by changing all instances of 'matlab' to 'matlab.exe'. Any recommendations?

**Comment by samuelgarcia** [comment]
"matlab" is not working in a cmd console ?
