### ISSUE TITLE
WaveformExtractor.run_extract_waveforms has to run on all units

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spikeinterface#330]
Hi,

I want to extract the waveforms of multiple units, my understanding is to use the `WaveformExtractor`, set the parameters, and run `run_extract_waveforms()`.
Except I'm not seeing a parameter to give which unit ids I want to extract, which means I need to extract the waveforms of all the units (which seems like a potential waste of time, and a lot of writing to disk when using `max_spikes_per_unit=None`).

In my use case, it wrote 298.7 GB to the disk (taking a few minutes) when extracting all of the waveforms (96 units) when I actually was only interested in 3 of them ...

Is it made like this on purpose?
Or is it something that needs to be added?

Thanks,
Drade

**Comment by alejoe91** [comment]
@Dradeliomecus after some discussion we think that the best option is to pre-select units. In fact, if we allow to compute users on a subset of units then it would be hard to keep track of which units have been already computed or not. 

Thanks for raising the issue though! Happy to discuss more but closing for now
