### ISSUE TITLE
How can I split sortings

### ISSUE THREAD

**Issue by BEGINRX** [SpikeInterface/spikeinterface#3317]
After used `si.concatenate_recordings` to concatenate recordings and sorting with the concatenated recording, how can I split the sorting results? I have used `si.split_sorting`, and then I get the segmented sorting. But the result is not subscriptable. How can I get the sorting segments?

**Comment by alejoe91** [comment]
If you want to access the spike trains form each segment, you can use:
```
spike_train = sorting.get_unit_spike_train(unit_id, segment=i)
```

You can also get a mono-segment sorting out of a multi segment one with this:
```
sorting_mono = si.select_segment_sorting(sorting_multi, segment_indices=[1])
```
In this example only the second segment will be returned

**Comment by alejoe91** [comment]
@chrishalcrow you can pass a `sorting` and a `concatemated_recording` to the `split_sorting` function!

**Comment by chrishalcrow** [comment]
@alejoe91 ahhh, very nice!

**Comment by BEGINRX** [comment]
@alejoe91 Thank you very much! It worked! 
@chrishalcrow Thank you! But the appended recording used `si.append_recordings` can't do the preprocessing `estiment_motion`. So my order of processing is `si.concatenate_recordings`, `set_probe`, preprocess, `run_sorter`, `si.split_sorting`, `si.select_segment_sorting` for each segment.

**Comment by BEGINRX** [comment]
Now I have new question. After getting each segment, I need to do postprocess using `si.create_sorting_analyzer`. But the input is each sorting and responding preprocessed recording. And the concatenated recording has one segement. How can I continue?
