### ISSUE TITLE
Non default Sparsity kwargs when creating SortingAnalyzer

### ISSUE THREAD

**Issue by jonpedros** [SpikeInterface/spikeinterface#3320]
I'd like to create a `SortingAnalyzer` object with sparsity computed from channel groups rather than the default setting. However, it seems sparsity arguments passed to `spikeinterface.core.create_sorting_analyzer()` are passed to `spikeinterface.core.estimate_sparsity()`, which does not handle such method, instead of to `spikeinterface.core.compute_sparsity()`.

At any rate, even with the relatively in-depth documentation specific to explaining sparsity, the many ways to generate it seem redundant/confusing. It seems `compute_sparsity()` is the most full-fledged function for generating it, but the fact it needs `SortingAnalyzer` to do so means one would have create `SortingAnalyzer` (possibly writing to disk etc) with `sparse=False`, generate sparsity and then create it (and write to disk) again. 

Furthermore, it seems that default behavior is for the group property to be referred as `'group'` for recordings, but when a grouped sorting is created from a grouped recording, this key changes automatically to `'channel_group'`, so `compute_sparsity()` will return an error when trying the routine I described above.

**Comment by alejoe91** [comment]
Hi @jonpedros 

You're absolutely right! We should support also the `by_property` method! I'll make a PR to patch this!

**Comment by alejoe91** [comment]
> Furthermore, it seems that default behavior is for the group property to be referred as `'group'` for recordings, but when a grouped sorting is created from a grouped recording, this key changes automatically to `'channel_group'`, so `compute_sparsity()` will return an error when trying the routine I described above.

Could you pinpoint where this happens?

**Comment by jonpedros** [comment]
> > Furthermore, it seems that default behavior is for the group property to be referred as `'group'` for recordings, but when a grouped sorting is created from a grouped recording, this key changes automatically to `'channel_group'`, so `compute_sparsity()` will return an error when trying the routine I described above.
> 
> Could you pinpoint where this happens?

Sure! You mean for the error when computing sparsity, or the point when the grouping key changes?

**Comment by alejoe91** [comment]
The grouping key! Is it from Phy?

**Comment by jonpedros** [comment]
> The grouping key! Is it from Phy?

Yes, sorting was curated in Phy and imported into SI, while the recording was loaded from the saved preprocessed folder generated before with SI.

**Comment by alejoe91** [comment]
I see. Yeah phy renames the groups as `channel_group`. So you would need something like:
```
sorting.set_property("group", sorting.get_property("channel_group"))
```

**Comment by jonpedros** [comment]
I agree! Should I close this one, though?
