### ISSUE TITLE
Unable to read the meta files from NP2013 Probes

### ISSUE THREAD

**Issue by shijiaaa** [SpikeInterface/spikeinterface#3333]
The following command worked well for the older versions of NP2 probes (24) but not the newer versions (NP2014):

```
stream_names, stream_ids = si.get_neo_streams('spikeglx', spikeglx_folder)

NotImplementedError: This meta file version of spikeglxis not implemented
```

Tried multiple versions of spikeGLX with the same channel configs as before, tried multiple NP2013 probes, and still got the same error.

However, if I copy and paste the .meta file from an older probe to the new probe's recording folder, the error was resolved, so I believe it is a meta file thing.
[ErrorMetaFile_g0_t0.imec0.ap.txt](https://github.com/user-attachments/files/16737829/ErrorMetaFile_g0_t0.imec0.ap.txt)
[SuccessMetaFile_g0_t0.imec0.ap.txt](https://github.com/user-attachments/files/16737830/SuccessMetaFile_g0_t0.imec0.ap.txt)

I am attaching the two meta files below. What might be different between these two meta files? 

Much appreciated for any thoughts!

**Comment by alejoe91** [comment]
Thanks @shijiaaa 

This is a NEO problem. Could you open the same issue here: https://github.com/NeuralEnsemble/python-neo ?

**Comment by alejoe91** [comment]
You should also try to upgrade your NEO installation, since `2013` seems supported: 
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/spikeglxrawio.py#L522

**Comment by shijiaaa** [comment]
Thanks. Upgrading the NEO installation solved the issue!
