### ISSUE TITLE
loading matlab into SpikeInterface 

### ISSUE THREAD

**Issue by ajcheng1** [SpikeInterface/spikeinterface#3340]
I am following this guide to use spikeinterface with matlab data: [https://spikeinterface.readthedocs.io/en/stable/how_to/load_matlab_data.html#exporting-data-from-matlab](url)
I write the matlab data into a bin file 
![image](https://github.com/user-attachments/assets/16d38e81-85f8-41a6-8e8a-6082bcfd2318)
I then put the bin file into my python folder 

![image](https://github.com/user-attachments/assets/babdb9c0-0c95-4c15-973f-58578b2012e2)

During pre-processing, I get the downstream error
![image](https://github.com/user-attachments/assets/2615641f-1100-474b-9048-5616b2998703)

I don't think the code is wrong, but I am also not sure what's wrong with my data file. Any advice? 

Addition: I checked the bin file and somehow it got (73,). Something must be wrong with writing the file into bin in matlab? 
![image](https://github.com/user-attachments/assets/6174845a-f3f7-4f0f-8a79-51536ca97b90)

**Comment by chrishalcrow** [comment]
Hi @ajcheng1 , I don't have much MATLAB experience, but I think you're missing the step when you read the data in. At the moment your `data` variable is just your filepath. You should have something like:
```
data_path = 'C:\Users\blahblah'
data = importdata(data_path)
```

At the moment it looks like your `your_data_as_a_binary.bin` file is empty. You can check how big it is in your File Explorer. I think it will be very small. Once you update the code, it will be about the same size of your raw data file.

Let me know if that works :)

**Comment by alejoe91** [comment]
Good catch @chrishalcrow 

I think you just need a `load`:
```matlab
data = load("C:/..../unsorted.mat")
```

**Comment by ajcheng1** [comment]
yep haha, I figured it out. I have another issue with the file, but I'll just create a new issue for it. Thanks!
