### ISSUE TITLE
paircomparison.py print_summary assertionerror despite exhaustive_gt = False

### ISSUE THREAD

**Issue by Djoels** [SpikeInterface/spikeinterface#3344]
Despite setting `exhaustive_gt=False`, the `print_summary` function in `paircomparison.py` raises an `AssertionError` because of 2 function calls: `count_redundant_units` and `count_overmerged_units` which in turn call `get_redundant_units` and `get_overmerged_units` respectively.

The 2 relevant dictionary items probably need to be moved to bottom of the function which only runs `if self.exhaustive_gt`

https://github.com/SpikeInterface/spikeinterface/blob/ff930d280f90818d7593215d756be7853b4b7d2b/src/spikeinterface/comparison/paircomparisons.py#L455-L466

**Comment by alejoe91** [comment]
Thanks @Djoels 

Do you want to take a stab and make a PR to fix this? :)

**Comment by Djoels** [comment]
Sure, but what is the correct fix? 

Removing the 2 asserts or moving the dictionary entries and template summary texts?
Is it sensible to report number of redundant units and number of overmerged units if the GT is not exhaustive?
