### ISSUE TITLE
`get_potential_auto_merges` returns units themselves as potential merges when using `feature_neighbors`

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#3345]
We were testing the new presets and `feature_neighbors` looked pretty good with the defaults, but it returned a bunch of units as potential merges with themselves.

```python
[(1,1), (2,2), (1,2)]
```

things like that. Is there a reason for that or is it okay to add a clean-up step before we return the merges?

@yger @DradeAW (I forget which of you implemented this one? )

**Comment by alejoe91** [comment]
Yep they should be removed ;)
