### ISSUE TITLE
cannot detect the installed mountainsort4

### ISSUE THREAD

**Issue by betty-hbr** [SpikeInterface/spikeinterface#3367]
Hi team,

I'm trying to use mountainsort4 in Spikeinterface 0.101.0. Although I have correctly installed the mountainsort4 to the same environment as Spikeinterface, it cannot detect or to run it. 

The output of ss.installed_sorters() are ['mountainsort5', 'simple', 'spykingcircus2', 'tridesclous2'].

I also tried with Spikeinterface 0.97.0 and 0.98.0. Same issues for them.

Can you please advice on this?

Many thanks

**Comment by alejoe91** [comment]
Can you try to import it?
```
import mountainsort4
```

The `installed_sorters` will list sorters that are importable

**Comment by betty-hbr** [comment]
Thank you so much for the prompt response! I tried with your suggestion. It wasn't importable, because I didn't have `requests` installed. The problem was fixed after  `pip install requests`
