### ISSUE TITLE
about kilosort4

### ISSUE THREAD

**Issue by bxy666666** [SpikeInterface/spikeinterface#3384]
Hello, I have some new questions about the Kilosort4.  Questions below are all based on Kilosort4.
1. The number of neurons detected across different organoids with default parameters is consistent across chips. We suspect this might be due to overly high sensitivity.
2. Will discontinuous data have a significant impact on neuron classification?

**Comment by JoeZiminski** [comment]
Hi @bxy666666 thanks for your question, I think this will be better answered by the kilosort team. You can raise an issue on their [github repo](https://github.com/MouseLand/Kilosort).
