### ISSUE TITLE
Error running Mountainsort4

### ISSUE THREAD

**Issue by szbalazs98** [SpikeInterface/spikeinterface#340]
When running _sorting_MS4 = ss.run_mountainsort4(recording_loaded, output_folder='results_MS4', verbose=True,filter=False)_ command I get this error: 

Error running mountainsort4
Traceback (most recent call last):
  File "C:\Users\SortingStation\anaconda3\lib\site-packages\spikeinterface\sorters\basesorter.py", line 198, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "C:\Users\SortingStation\anaconda3\lib\site-packages\spikeinterface\sorters\mountainsort4\mountainsort4.py", line 118, in _run_from_folder
    old_api_sorting = mountainsort4.mountainsort4(
  File "C:\Users\SortingStation\anaconda3\lib\site-packages\mountainsort4\mountainsort4.py", line 32, in mountainsort4
    tmpdir = tempfile.mkdtemp(dir=os.environ.get('TEMPDIR', '/tmp'))
  File "C:\Users\SortingStation\anaconda3\lib\tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [WinError 3] The system doesn't find the given path: '/tmp\\tmphpb9vlk8'

Is there a solution to this, or am I doing something wrong? Thank you in advance!

**Comment by magland** [comment]
Yes, mountainsort has never been tested on windows.

**Comment by ghostrider77** [comment]
There is an easy fix for that. From the trace it it clear that `mpdir = tempfile.mkdtemp(dir=os.environ.get('TEMPDIR', '/tmp'))` causes the problem, since in Windows the temporary directory is not called '/tmp', moreover, the slash at the front causes issues when it tries to resolve the path.

The best way is to create an environmental variable `TEMPDIR` by yourself.
```
import os
import tempdir

os.environ['TEMPDIR'] = tempfile.gettempdir()

# insert MS code that you run after the lines above
```

**Comment by szbalazs98** [comment]
Thank you so much for the answers! This solved solved the problem.

**Comment by szbalazs98** [comment]
I may have a small problem. After I sort with MountainsSort4 and open the result in Phy, on the ProbeView the channels are not next to each other as I would expect.

What could be the problem? Mountainsort doesn't take the previously given mapping into account? This problem doesn't occur with other sorters.
![mountainsort_phy](https://user-images.githubusercontent.com/85197786/139709575-97def93f-51d4-4010-8f51-67118cf85fe8.png)

**Comment by alejoe91** [comment]
Hi @szbalazs98, this is indeed a weird behavior. @magland could you double check that the new mountainsort4 implementation is handling location info correctly?

**Comment by alejoe91** [comment]
> @szbalazs98 @alejoe91
> 
> The mountainsort4 algorithm only outputs the unit times and cluster labels. So if I'm thinking about it correctly, this must be related to the export_to_phy. Indeed, @szbalazs98 says: "This problem occur with other sorters when I use the function called export_to_phy."

Right! Sorry @magland I should have read more carefully. @szbalazs98 does this happen for all units? Are you using the same `recording` object that you input to MS4 when extracting waveforms?

**Comment by alejoe91** [comment]
Also, how are you loading probe information?

**Comment by szbalazs98** [comment]
Yes it happens with all the units. I only use one recording object. Can the problem be the wiring? (Because it shuffles the order of the channels)
I attached the loading of the probe information:
![probing](https://user-images.githubusercontent.com/85197786/139855764-83282de2-a137-4971-9ad8-3bd0954d3ed8.png)
n

**Comment by alejoe91** [comment]
Yeah I think that the problem could be the wiring indeed. Can you double check that the plotted device indices correspond to the one you expect from your mapping? Where does your recording come from? Did you use the H32>RHD2132 pathway in your experiment?

**Comment by samuelgarcia** [comment]
Yes. It looks like a wiring problem.

**Comment by szbalazs98** [comment]
I've consulted with the lab, and indeed the wiring was wrong. However after I customized it appropriately it doesn't seem to be entirely correct because channels are missing from the WaveformView next to channels where the waveform is relatively great. (I attached a picture from SpikingCircus)
![SC_new](https://user-images.githubusercontent.com/85197786/140776309-d109b84b-b888-448f-926d-b325ecf5db10.png)
