### ISSUE TITLE
get_probe assumes a single probe, but it's used throughout the modules

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#343]
https://github.com/SpikeInterface/spikeinterface/issues/342 pointed out that when a probegroup is used instead of a single probe, some steps may fail (in the issue running HS).

After a quick check, having a probe group also affects `widgets` and `sortingcomponents`

**Comment by samuelgarcia** [comment]
I know. I guess it is the behavior we want.
When we have several probe we need to split before sorting.
Maybe we could have a check in BaseSorter to have a correct error message for that.

About the wodget that don't  deal woth probegroup I think this is OK. The end end can do the split externally if the error mesage is well written. no ?

**Comment by alejoe91** [comment]
I'm not sure it's what we want..one might also want to sort without splitting, no? From the widget side, I think it's better to always deal with probegroups, as it's more general

**Comment by samuelgarcia** [comment]
The problem is that for probegroup could be at the same location and so the sorting would be wrong.
I think we should forgive by default the sorting on several probe. It could be possible with a flag and a clear doc about absolut vs relative probe map.
