### ISSUE TITLE
How to increase the sensitivity of register_online_lfp?

### ISSUE THREAD

**Issue by DaohanZhang** [SpikeInterface/spikeinterface#3464]
Hello! In my recent recording, I found register_online_lfp can not recognize my probe drifting which can be recognized by naked eyes. Even if I used
```python
# spatial filters: second derivative and averageing same-depth channels
lfprec = si.directional_derivative(lfprec, order=2, edge_order=1)
```
twice in order to further sharpen the border. Is there any parameters I can tuning to get register_online_lfp more sensitive? I guess there is no other problem since the default parameters worked pretty nice on my previous recordings.

Details are in https://github.com/evarol/dredge/issues/2

**Comment by zm711** [comment]
We would need @cwindolf or @samuelgarcia to comment here. It could be any dredge work hasn't been propagated here yet.

**Comment by cwindolf** [comment]
Thanks for the ping @zm711 -- I've responded at the issue on the dredge repo.

**Comment by cwindolf** [comment]
(We are discussing over there at https://github.com/evarol/dredge/issues/2, so I'll close this issue -- feel free to reopen if you like!)
