### ISSUE TITLE
Loading filtered data?

### ISSUE THREAD

**Issue by jazlynntan** [SpikeInterface/spikeinterface#3470]
Hi, I used kilosort4 outside of spikeinterface for preprocessing and spike sorting. I did some brief checks and curation in Phy. I now want to load the data into spikeinterface to do other visualizations and calculate additional quality metrics. However, when I loaded the recording using read_openephys, the sorting using read_kilosort and read_phy, the waveforms extracted looked wrong despite them looking fine in templates.npy. 

The units visualized with the templates.npy
<img width="256" alt="Screenshot 2024-10-09 at 5 01 18 PM" src="https://github.com/user-attachments/assets/37b85a43-f77b-4308-9f9a-be20066605be">

The units visualized using the waveformextractor on the sortinganalyzer created from the sorting from read_phy and recording from read_openephys. 
<img width="225" alt="Screenshot 2024-10-09 at 5 02 59 PM" src="https://github.com/user-attachments/assets/8d565a67-d66a-4afd-8619-fcf7771076fb">

In addition, when I ran compute_quality_metrics(), the median amplitudes and snr were odd - all units had the same median amplitude and the noise level estimated for snr calculation were mostly negative. 

I suspect that it has to do with the recording in the sortinganalyzer being the unprocessed raw data. Is this the case? If so, how can I load the preprocessed recording from kilosort so that I can perform visualizations and quality metric computation in spikeinterface?

Thank you.

**Comment by zm711** [comment]
Hey @jazlynntan, you would regenerate the same filtering and referencing inside of spikeinterface. We can't really take the exact preprocessing of kilosort, but instead you could do something like:

```python
import spikeinterface.extractors as se
import spikeinterface.preprocessing as spre
recording = se.read_openephys(xx)
recording_f= spre.bandpass_filter(recording)
recording_cmr = spre.common_reference(recording_f)
```

You could also do other preprcessing/look up what kilosort is doing to replicate the same preprocessing in spikeinterface.

**Comment by jazlynntan** [comment]
Thanks for the prompt response.

Kilosort4 has an option to save preprocessed data to a temp_wh.dat file. Does spikeinterface have extractor modules that can read the dat file? 

Also, just so that I understand correctly, spikeinterface allows the use of multiple spike sorters (eg. kilosort, spykingcircus, etc.) but this is only for the sorting stage itself? If I wanted to use the preprocessing or other features of these spike sorters I would have to directly use the software outside of spikeinterface?

Thanks!

**Comment by zm711** [comment]
I think Joe has answered this question. Please reopen if you have more questions (or open a new issue). Let us know if we help!
