### ISSUE TITLE
Not dumpable AssertionError when running MountainSort4

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#348]
I ran the latest version of _ss.run_mountainsort4(recording, **params, output_folder)_ on Google Colab, in which recording is the _CommonReferenceRecording_ object. However, it turned out to be Assertion Error like this:
![image](https://user-images.githubusercontent.com/78635669/140832044-43fe43b2-120a-4a4a-b070-e6f600b045f8.png)
So why is this happening, and what should I do to fix it? Thanks in advance!

**Comment by samuelgarcia** [comment]
Recording need to be dumpable in some case.
If it is not the case (like NumpyRecording) you can save then and run on the saved recording.

`saved_rec = rec.save(folder='/path/to/my/saved_rec')`
