### ISSUE TITLE
SpikeSortingError when running MountainSort4

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#349]
When I ran the latest version of ss.run_mountainsort4(recording, **params, output_folder) on Google Colab, in which recording is the NumpyRecording object. However, it turned out to be SpikeSortingError like this:
![image](https://user-images.githubusercontent.com/78635669/140833368-3ea2ff7c-a2e9-4233-b76f-51e4a23dd53f.png)
And I think it's the same issue with the one in the documentations of Sorters Tutorial:
![image](https://user-images.githubusercontent.com/78635669/140833496-96683b54-6d51-4654-b8f0-4511f7103581.png)
So are there any solutions to this problem? Thanks in advance~

**Comment by samuelgarcia** [comment]
I think it is due to numba which is jnot compatible with numpy 1.21.

do `pip install numpy==1.20` (or conda)
