### ISSUE TITLE
IBL Test Failing in Full Tests

### ISSUE THREAD

**Issue by zm711** [SpikeInterface/spikeinterface#3507]
@h-mayorquin is this you or @alejoe91 that manages IBL extractor stuff?

**Comment by h-mayorquin** [comment]
Most likely I will be working in a short project with IBL. I can take care next week. The error seems simple though.

**Comment by zm711** [comment]
Test is now passing. Closing.

**Comment by h-mayorquin** [comment]
Good, my problem is gone without me doing anything : )
