### ISSUE TITLE
Decompress Zarr to Binary Files

### ISSUE THREAD

**Issue by atombysx** [SpikeInterface/spikeinterface#3529]
Hi all, this is particularly about spikeinterface backward-compatibility with SpikeGLX/catGT:
I'm currently compressing two NPX2.0 probes recordings with WavPack (Zarr) and save as Zarr and it seems very good in terms of compression (~60-70% reduced). But one concern is how easy it is to convert back to spikeGLX binary files as we have NIDQ events recorded and need to synchronise the two probes or something we miss before compression and we can revert back to do catGT preprocessing. Any chance spikeinterface has an easy way to deal with this?

**Comment by h-mayorquin** [comment]
Hi, as far as I know, there is no way in Spikeinterface to accomplish this. I would suggest that the better way around this would be to implement the routine of catGT on spikeinterface. Altought, there must be a good reason why we don't have something like this yet.  Any ideas @alejoe91 ?

**Comment by h-mayorquin** [comment]
Oh, I stand corrected. I could not find a reference to `catGT` in the preprocessing section which is where I expected:

https://spikeinterface.readthedocs.io/en/stable/how_to/analyze_neuropixels.html#preprocess-the-recording

Two questions and I guess we can close this issue:
1) Should we mention in the analysis of neuropixels how to that that preprocessing is like catGT?
2) Do you think it would be useful for users to have a preprocessing step call catGt that just applies highpass filter + phase shift + CMR as a pipe?

**Comment by alejoe91** [comment]
hey @h-mayorquin 

1. Yes we should definitely mention that this is similar to CatGT!
2. I don't think we should. I think our API is clearer and also instructive :) Having a tutorial that shows the chain and explains the different steps is good enough for me (but we should make it more discoverable)

**Comment by h-mayorquin** [comment]
Makes sense, another reason against 2 is that it will tie us to a level of support that we might now want as we have discussed previously with quality metric naming. I can do the brief correction on the how-to when I have some time.

**Comment by zm711** [comment]
It's just a flat binary file, what specs were you hoping for?

**Comment by atombysx** [comment]
> It's just a flat binary file, what specs were you hoping for?

Well you can have different dtypes, headers and flat raw binary files are 8 bits, especially that the document says spikeinterface binary format is for internal use so it could potentially have extra info stored. Anyway, I went through the source code and found both Spikeinterface and SpikeGLX use int16 on default and there's no extra info - in case anyone wants to know. Thanks everyone for answering patiently! Closing now.

**Comment by h-mayorquin** [comment]
Thanks a lot for writing what you found. The code for this can be found under `write_binary_*` on our codebase if anyone is looking.

**Comment by samuelgarcia** [comment]
> 1. Yes we should definitely mention that this is similar to CatGT!

We do have a clear ref to catGt here https://spikeinterface.readthedocs.io/en/stable/modules/preprocessing.html#how-to-implement-ibl-destriping-or-spikeglx-catgt-in-spikeinterface

**Comment by h-mayorquin** [comment]
Thanks, @samuelgarcia , this would be useful for anyone stumbling upon this issue. I will also change the title to cover the intent so this appears on search services correctly.
