### ISSUE TITLE
Missing requirements in docker container for spike sorting with kilosort3

### ISSUE THREAD

**Issue by steevelaquitaine** [SpikeInterface/spikeinterface#3540]
Two requirements are missing to run kilosort3 container "remfile" and "pynwb"-

e.g., The code below produces ModuleNotFoundError for these two dependencies: 

```
# spike sort with kilosort 3 from container (uses apptainer)
sorting_KS3 = ss.run_sorter(sorter_name="kilosort3", singularity_image=True, recording=recording)
```

Currently the container runs successfully by adding the extra_requirements argument:

```
# spike sort with kilosort 3 from container (uses apptainer)
sorting_KS3 = ss.run_sorter(sorter_name="kilosort3", singularity_image=True, recording=recording, extra_requirements=["remfile","pynwb"])
```

**Comment by alejoe91** [comment]
@samuelgarcia this is not true. Each extractor comes with additional `extra_requirements` that are automatically installed in the containers. I think that the streaming NWB is just missing `remfile`
