### ISSUE TITLE
SortingAnalyzer export to phy show different waveforms than the native sorting

### ISSUE THREAD

**Issue by MarinManuel** [SpikeInterface/spikeinterface#3544]
Hi,
I couldn't track the issue that I am having, hopefully someone else could have a better idea of what I am doing wrong.

I run kilosort2.5 on some NPX data (recorded with Open ePhys). My workflow is:
- preprocess data (time shift, bandpass, CAR, remove bad channels, etc) and save the pre-processed data as zarr
- run kilosort and save in folder
- load the sorting from the folder, create a sortingAnalyzer, compute quality metrics
- export to phy to look at the units.

I noticed that when I open the phy folder created from the sortingAnalyzer, the units appear mostly (though not exclusively) like noise. However, opening phy from the `sorter_output` folder created when running kilosort, the units are overwhelming good quality.

See screenshot below:
![Screenshot from 2024-11-14 15-12-20](https://github.com/user-attachments/assets/b1531b90-2be9-4fa7-91cc-17094948ae9a)
The left window is from opening the `sorter_output` directly, with the right window is opening the version exported by sortingAnalyzer. Notice how different the traces look, and the waveforms, and the PCAs. The only things that are not affect seem to be autocorrelogram, ISIview and FRView.

I'm attaching the script I am using.
[run_sorter_slurm.txt](https://github.com/user-attachments/files/17824831/run_sorter_slurm.txt)

**Comment by zm711** [comment]
What file are you pointing to in the `params.py` for the `export_to_phy`. in your script I don't see any filtering or referencing. KS2.5 saves a `.dat` file that has been filtered and referenced. Could you try to filter and reference your recording before making your sorting analyzer?

**Comment by MarinManuel** [comment]
Hi Zach,
You're right, I forgot to include part of the code
```python
rec = si.concatenate_recordings(recs)
rec_NPX = rec
rec_NPX = si.phase_shift(rec_NPX)
rec_NPX = si.bandpass_filter(rec_NPX, freq_min=300, freq_max=6000)
rec_NPX = si.common_reference(rec_NPX, operator="median", reference="global")
bad_channel_ids, channel_labels = si.detect_bad_channels(rec_NPX)
rec_NPX = rec_NPX.remove_channels(bad_channel_ids)
target_file = scratch_folder / 'all_sessions_probeA_pre_processed.zarr'
if target_file.exists():
    rec_NPX = si.read_zarr(target_file)
else:
    rec_NPX = rec_NPX.save(format='zarr', folder=target_file, verbose=True, **job_kwargs)
```

The pre-processed file is saved as `zarr` and then passed to the script above to run the sorter.

I open phy using:

`phy template-gui all_sessions_probeA_pre_processed_kilosort2_5_sorting/sorter_output/params.py`
for the version created by kilosort2_5

and 

for the version exported from the SortingAnalyzer
`phy template-gui all_sessions_probeA_pre_processed_kilosort2_5_phy/params.py`

**Comment by MarinManuel** [comment]
this is the content of params.py
from kilosort2.5:
```python
dat_path = '/scratch2/workspace/mmanuel_uri_edu-2024-11-13/all_sessions_probeA_pre_processed_kilosort2_5_sorting/sorter_output/temp_wh.dat'
n_channels_dat = 384
dtype = 'int16'
offset = 0
sample_rate = 30000.
hp_filtered = True
```

from `export_to_phy`:
```python
dat_path = r'/scratch2/workspace/mmanuel_uri_edu-2024-11-13/all_sessions_probeA_pre_processed_kilosort2_5_phy/recording.dat'
n_channels_dat = 384
dtype = 'int16'
offset = 0
sample_rate = 30000.0
hp_filtered = True
```

**Comment by alejoe91** [comment]
Hi @MarinManuel 

Can you check which Kilosort version you're using? 

You should make sure you checkout v2.5.2 and v3.0.2. In the *.0.1 versions, there was a misalignment issue that got fixed.

**Comment by MarinManuel** [comment]
Hi Alessio,
I confirm that I am using v2.5.2 from https://github.com/MouseLand/Kilosort/releases/tag/v2.5.2

**Comment by MarinManuel** [comment]
I'm pretty sure I've got the same problem using Kilosort4. The output from the SortingAnalyzer's `export_to_phy` is full of noisy units

![image](https://github.com/user-attachments/assets/d30d62ac-4288-4ea3-a53c-ba1c3f7912d9)

I'm sure I should get much better than that, although I cannot open the `params.py` from the `sorter_output` folder because of this error https://github.com/cortex-lab/phy/issues/1273 . What is the easiest way to convert my pre-processed `zarr` file into a format that can be read by phy?

**Comment by alejoe91** [comment]
@MarinManuel do the templates look correct when you use the `sw.plot_unit_templates` function?

**Comment by MarinManuel** [comment]
I guess maybe I misunderstand how the SortingAnalyzer is supposed to be used.

Here is unit 2 straight from Kilosort 2.5 (not a great one)
![image](https://github.com/user-attachments/assets/a7f30f68-ae2e-4770-8af1-b8db0f375cad)

Here is unit 2 from the SortingAnalyzer's export_to_phy
![image](https://github.com/user-attachments/assets/490de9df-e8df-4c85-8064-e3bc45bfb3b7)

and here are the templates using `sw.plot_unit_templates(analyzer, unit_ids=[2])` which look like the ones shown in phy
![image](https://github.com/user-attachments/assets/80911acb-475d-41e4-9a44-f3974c8d0236)

I also looked at the units with the largest number of spikes.
This is unit 159, with 475745 spikes (the second largest, the first one was noise)
![image](https://github.com/user-attachments/assets/e68a5d0a-7f25-497f-88ff-65204da6528a)

But when I open the SortingAnalyzer version, the unit with the second to largest number of units has 475733 spikes and is number 138
![image](https://github.com/user-attachments/assets/ca83c72f-f337-4fed-a0ea-1d1b303d8893)
but the template that seem to match using `sw.plot_unit_templates` seem to be number 159

![image](https://github.com/user-attachments/assets/d324029c-0ad3-4e3a-8b95-fa4c5358555d)

**Comment by alejoe91** [comment]
Ah the problem is that Phy needs linearly increasing integers as ids..you can see there is a "si unit id" column in Phy that corresponds to the unit id in spikeinterface :)

**Comment by MarinManuel** [comment]
Ok, I see that unit 139 in phy has number 159 in the column `si_unit_id` so that makes sense. I still don't understand why the number of spikes, the traceview and the templates are different between the two versions

**Comment by alejoe91** [comment]
Did you do any curation step? Like removing duplicated spikes??

**Comment by MarinManuel** [comment]
hmmm yes, my script does
```python
sorting = sorting.remove_empty_units()
sorting = si.remove_duplicated_spikes(sorting, censored_period_ms=0.3, method="keep_first_iterative")
sorting = si.remove_excess_spikes(sorting=sorting, recording=rec)
sorting = si.remove_redundant_units(sorting, align=False, remove_strategy="max_spikes")
```
before creating the SortingAnalyzer, so that makes sense, thanks.

What about the TraceView? Here are the first 250ms of the file, which looks nothing alike after the SortingAnalyzer
![image](https://github.com/user-attachments/assets/944d2454-83a2-4370-9114-eb262972a076)
![image](https://github.com/user-attachments/assets/47ca477a-9573-4997-a3b6-07d87346362c)

**Comment by MarinManuel** [comment]
I think I understand what you mean, but where do all those units come from after the SortingAnalyzer? if they were not there in the output of Kilosort? Or is it just that the templates are present over a larger number of channels after SortingAnalyzer, so there seem to be more of them?

**Comment by alejoe91** [comment]
you don't have more units :) Just the IDs might be different.

You can check as follows:
```
print(len(sorting_analyzer.unit_ids))

# read the kilosort folder
sorting_ks = se.read_kilosort("path-to/sorter_output")
print(len(sorting_ks.unit_ids))
```

**Comment by MarinManuel** [comment]
Thank you Alessio, I think I am starting to realize where my assumptions were wrong.
You have to admit, though, that the TimeViews look very different.
