### ISSUE TITLE
Issue with Highpass Filtering

### ISSUE THREAD

**Issue by majidkhalili** [SpikeInterface/spikeinterface#3551]
Hello everyone,

I’m encountering unexpected behavior when applying a highpass filter to my data. After filtering, all meaningful information seems to be lost.

To investigate, I manually filtered a segment of the signal and compared it to the results from the spikeinterface filtering function. However, the outputs are dramatically different.

Below is the code for filtering with spikeinterface and using scipy:

```
# Spikeinterface filtering
recording_HF = sif.highpass_filter(recording, freq_min=300)
ch133 = recording.get_traces(start_frame=5440*30000, end_frame=5460*30000, channel_ids=['AP133'])
ch133_filt_spikeinterface = recording_HF.get_traces(start_frame=5440*30000, end_frame=5460*30000, channel_ids=['AP133'])

# Manual filtering
lowcut = 300  
fs = 30000  
order = 4  

b, a = scipy.signal.butter(order, lowcut / (fs / 2), btype='low')
ch133_filt_scipy = scipy.signal.filtfilt(b, a, ch133.T)
```

And here is the result:

![Spikeinterface_filtering_Issue](https://github.com/user-attachments/assets/213fb654-c885-4f3d-9c6f-8ffc948cb77b)

Environment Details:

> Recording: Neuropixels
> spikeinterface version: I tried both SpikeInterface 0.101.2 and SpikeInterface 0.101.0
> Python version: 3.11
> Operating system: Windows

I would appreciate any insights or suggestions on how to resolve this discrepancy. Could this be due to differences in filter implementation or parameter settings? Could you please also provide insights into best practices for applying highpass filters in this context? 

Thank you

**Comment by alejoe91** [comment]
Hi, in your example you're applying a low-pass filter. For spike sorting, the interesting information is in the high frequency!

**Comment by majidkhalili** [comment]
OMG, it has been bugging me for several hours today, I have oversighted the the filtering parameter in the btype paramer in the butter function. Thanks a lot
