### ISSUE TITLE
silence_periods with mode 'noise' is incompatible with get_noise_levels

### ISSUE THREAD

**Issue by maxjuv** [SpikeInterface/spikeinterface#3554]
Hello,
I recently added in my preprocessing silence_periods(mode='noise'). Since then I was not able to estimate noise level. I got the following error :
```
  File "/home/users/j/juventin/local_python_package/spikeinterface/src/spikeinterface/preprocessing/silence_periods.py", line 76, in __init__
    noise_levels = get_noise_levels(
  File "/home/users/j/juventin/local_python_package/spikeinterface/src/spikeinterface/core/recording_tools.py", line 789, in get_noise_levels
    recording_slices = get_random_recording_slices(recording, **random_slices_kwargs)
TypeError: get_random_recording_slices() got an unexpected keyword argument 'noise_generator'
```

I tracked the error. It happened that during the silence_period preprocessing, 'noise_generator' is added in the recording kwargs 
https://github.com/SpikeInterface/spikeinterface/blob/853d8a48abcf40f5a47401ed2f7baa83e1c3295f/src/spikeinterface/preprocessing/silence_periods.py#L100
 Then, when estimating the noise levels (get_noise_levels), spikeinterface passes the variables 'noise_generator' in random_slices_kwargs, which is not recognized. 
Is it really useful to put 'noise_generator' in the kwargs ?
In my script I solved it by removing 'noise_generator' from the kwargs.

**Comment by zm711** [comment]
I think this is likely @samuelgarcia , but maybe @alejoe91 knows this?

**Comment by yger** [comment]
I've made a putative patch in #3557
