### ISSUE TITLE
Some potential bugs for sorter output from kilosort2.5 and kilosort4 might cause error when using UnitMatchPy

### ISSUE THREAD

**Issue by MingChingChiang** [SpikeInterface/spikeinterface#3577]
Hi 
This is Ming-Ching Chiang from OIST, Japan.

Thank you for developing such useful tools, I am a faithful spikeinterface user since you published the eLife paper.
I'm now working on the Neuropixels dataset and using spikeinterface to run both kilosort2.5 and kilosort4.
After the sorting I'm running the bombcell for quality matrices and then try to run UnitMatch for multiple sessions.
However when I try to run the UnitMatch on kilosort2.5 outputs I always got error.
After several debugging process I found that the output file 'spike_times.npy' from kilosort2.5 and kilosort4 have different shape.
For example form one of my sorting, the KS25_spike_times.npy.shape is  (165379, 1), but the KS4_spike_times.npy.shape is (876132,). 
The output of kilosort4 is an array of numbers, but the output of kilosort2.5 is an array of arrays. (I hope my explaination make sense...)
![Screenshot 2024-12-12 180744](https://github.com/user-attachments/assets/9785cdd8-b2dd-4b19-a226-b35700bb2b6f)

I think I can manually adjust the output form the kilosort2.5, but I also want to raise this inconsistent ouptut dimension from your codes.

But anyway, 
Thank you very much for developing these useful tools.

Best regards,
Ming-Ching

**Comment by zm711** [comment]
We can close this one, but feel free to come back with any other questions you have @MingChingChiang !
