### ISSUE TITLE
How to run Mountainsort4?

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#370]
So basically I need to set probe before I ran Mountainsort4, right? Could you please provide / show me a simple example on the pipeline of running Mountainsort4, including saving Recording object, setting probes, etc.? Since I read about the tutorial on how to use run_tridesclous(), but it seems that there are some spikesorting errors... Thanks in advance~

----------------------------------------------------------------------------------------------------

Hi, you are not doing anything wrong :) Mountainsort4 uses the old API, so internally we print this message to remind ourselves that we need to update it.

Regarding the error, I think it's because MS4 requires locations and it doesn't seem to find it in your recording object. Did you set a probe?

_Originally posted by @alejoe91 in https://github.com/SpikeInterface/spikeinterface/issues/355#issuecomment-965749124_

**Comment by samuelgarcia** [comment]
It will be exactly the same for all sorters including Mountainsort4.
just use
`sorting = run_sorter('mountainsort4', recording)`
internally there is a wrapper to old API (this is why you have the message) but at end user you have have to worry about it.

**Comment by Yuhao-Zhang-SV** [comment]
OK, so do I need to set probe info first before run_sorter()? Should I set probe like this if there's no probe info in the recording object?
![image](https://user-images.githubusercontent.com/78635669/142508447-dbb5ca4c-d8c6-4b86-b64b-78df7a27d4b3.png)

**Comment by samuelgarcia** [comment]
Yes, you need to attach a probebefore any run_sorter.

**Comment by Yuhao-Zhang-SV** [comment]
So I'm currently using the recording with probe information. But I still get the same error as the recording without probe info. So what could that issue be? Thanks in advance~ We are trying to migrate from version **0.13** to the **newest** version of spikeinterface. (**SpikeSortingError: Spike sorting failed.**)
![image](https://user-images.githubusercontent.com/78635669/145319807-f8852c92-c438-4b19-95dc-a5d6f6c767d1.png)

**Comment by samuelgarcia** [comment]
What do you have when you do `rec.get_property('location')` ?
Normaly after `rec = rec.set_probe(a_probe)'` the location property is set automatically.

**Comment by Yuhao-Zhang-SV** [comment]
OK, thanks! Actually it's None before, and then I managed to use a NumpyRecording object with available and correct get_property('location') info and it works! Thanks again.
