### ISSUE TITLE
create SortingExtractor from manually sorted data

### ISSUE THREAD

**Issue by Yizhar-Lab** [SpikeInterface/spikeinterface#371]
How do I create a "ground-truth" `SortingExtractor` for the `compare_sorter_to_ground_truth` function from a simple text file (say .txt, .csv or .npy) which contains my manually sorted spike-times and spike-clusters?

**Comment by samuelgarcia** [comment]
The simpler is to create a sorting from numpy array with `NumpySorting` see
https://spikeinterface.readthedocs.io/en/latest/modules/core/plot_2_sorting_extractor.html
