### ISSUE TITLE
Saving waveforms to nwb

### ISSUE THREAD

**Issue by khl02007** [SpikeInterface/spikeinterface#397]
Right now the extracted waveforms are saved as npy files but I wonder if it would be good to store it in a single NWB. Given that NWB is largely self-documenting and is (expected) to be widely adopted by the community, this could be a useful feature. I looked at the code but wasn't sure where this modification would go since it seems to make use of a job handler for parallel processing. Would be happy to discuss further and / or submit a PR once I understand the code better.

**Comment by samuelgarcia** [comment]
I think @alejoe91 and @Saksham20 have done this in https://github.com/catalystneuro/nwb-conversion-tools.
I let then comment.
