### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by mhhennig** [SpikeInterface/spikeinterface#4]
When installing SI from this location, the `requests` package is not installed.
`spikesorters/ironclust/mdaio.py` wants it.

**Comment by samuelgarcia** [comment]
I think we planed to move mdio from sorters to extractirs and make a weak dependency.
@colehurwitz @alejoe91 @magland is it still the case ?

**Comment by magland** [comment]
my opinion is to include mdaio in spikesorters to reduce the dependencies. I don't think that spikeextractors should necessarily expose mdaio.

**Comment by alejoe91** [comment]
then we should add requests as requirement in the setup.py!

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/50

**Comment by samuelgarcia** [comment]
So we can remove from requirement.txt no ?

**Comment by alejoe91** [comment]
yes, I'll merge, release, and update

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/23
