### ISSUE TITLE
Not able to run_mountainsort4 due to not dumpable issue

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#405]
When I call run_mountainsort4, there is a weird issue. Basically I had a NumpyRecording first, and then call st.preprocessing.common_reference, and then get a CommonReferenceRecording object. Finally I call run_mountainsort4 with this CommonReferenceRecording object. However, I don't know if the CommonReferenceRecording object and the NumpyRecording object are dumpable, since the result seems that it is dumpable, but later it did not pass the assert statement, as is shown below.
![image](https://user-images.githubusercontent.com/78635669/145469523-5aff6053-706e-43e6-b6fb-61b100bae221.png)
And the dict is like this, which shows that there is something not dumpable, but basically is the dict seems correct? Where could I be wrong?
![image](https://user-images.githubusercontent.com/78635669/145470980-da4d7ffd-53e5-417c-add1-72b9a51a1d0c.png)
Thanks in advance~

**Comment by alejoe91** [comment]
Hi, sorry for the late reply. Can you `save` the numpy recording fisrt before applying any preprocessing? (`recording = recording.save(fodler='my-folder')`. This will fix all "dumpable" issues
