### ISSUE TITLE
KeyError: 'relative_paths' when calling run_mountainsort4

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#406]
Hi,

I'm trying to migrate from spikeinterface 0.13 to the newest version. And when I call run_mountainsort4, it shows the 'relative_paths' error. What's the meaning of the error? How can I fix it? Thanks in advance~
![image](https://user-images.githubusercontent.com/78635669/145522547-f287de17-2f06-479e-8261-1be4c50de510.png)

**Comment by samuelgarcia** [comment]
It is not possible to load an older folder computed with SI-0.13 from a version with the new API.
You need to recompute.

**Comment by Yuhao-Zhang-SV** [comment]
Got it. Thanks~
