### ISSUE TITLE
Waveforms extractor and memory usage

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#442]
It would be nice if the WaveformExtractor could have an option not to cache all the waveforms in memory. Because for large recordings, a call to waveform.get_all_templates() for example is consuming almost all the memory, since waveforms are loaded, but kept by the objects internally. Why such a behavior?

**Comment by samuelgarcia** [comment]
It is on my todo list.

**Comment by alejoe91** [comment]
duplicate of https://github.com/SpikeInterface/spikeinterface/issues/331

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/451
