### ISSUE TITLE
Automatic citation maker

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeinterface#48]
I was discussing with another open source developer who is implementing an automatic citation creator for people that use the framework.

I think we can do something similar with SpikeInterface where the citations can be grabbed for different file formats or spike sorters from some internal property that stores citation formats (bibtex, etc.). I can try to do something like this for spikeextractors first maybe..

**Comment by colehurwitz** [comment]
I will get to this soon! I have some ideas. :)

**Comment by yarikoptic** [comment]
not sure if that "open source developer" might have been me, but I would like to pitch about http://duecredit.org/ project which might be of help here! ;-)

**Comment by yarikoptic** [comment]
so what you have converged on?  duecredit sounds like a good fit FWIW ;)

**Comment by samuelgarcia** [comment]
Hi Yarik,
We decide to do nothing at the moment.
We will re open this later if someone have time.
