### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by paul-aparicio** [SpikeInterface/spikeinterface#495]
Hello! I had a few issues, I hope its ok to put them in a single post. Thanks for any help.

(1) In the old version of spikeinterface ```remove_bad_channels``` had an option to explicitly list bad channels for removal. It doesn't seem to have this option any more, is there another way to accomplish this? 

(2) When I run ```compare_multiple_sorters``` I get the error below over and over again, but the command seems to complete (i.e. when I run ```w = sw.plot_multicomp_agreement(mcmp)``` I get reasonable looking results). Is this ok?

```
KeyError: '/dev/shm/joblib_memmapping_folder_18661_b72bda93ef6d4fcb9e02afbbc52f0767_4e89a7fb355249b2a6fe46c9d65784f2/18661-140679081454992-9702f7ecc3d94e9c9f7b8d76101bfd23.pkl' Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/si_env/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py", line 287, in main registry[rtype][name] -= 1
 ```
(3) When I run ```compare_multiple_sorters```, I get an error that says there were different sampling frequency between the sorters? There was no change in the data between the sorters, so I am not sure what is causing the problem. The sorter that seems to be the problem is WaveClus.

(4) Is there a way to specify parameters in spyking circus that are not in the sorter parameter list? I would like to change the cc_merge and smart_search parameters.

Thanks again

**Comment by samuelgarcia** [comment]
1. now you can `sorting_clean = sorting.select_units(keep_unit_ids)` you handle the list you want to keep.

2. We need to have a look. You can do n_jobs=1 but it will be slow.

3. there is normally a tolerance ratio to allow small diff in sampling rate. Can you display sampling rate for all your sorting objects ?

4. If they are not in the list : no. But you can make a small patch to handle this or ask Pierre to do it @yger.

**Comment by alejoe91** [comment]
> 1. now you can `sorting_clean = sorting.select_units(keep_unit_ids)` you handle the list you want to keep.

Actually it's:
```
recording_clean = recording.channel_slice(keep_channel_ids)
```
