### ISSUE TITLE
How are unit_ids linked channel_ids between recordings and sortings

### ISSUE THREAD

**Issue by McD-NMI** [SpikeInterface/spikeinterface#50]
Hello, 

I am trying to build a sorting extractor for MCS H5 files. I am able to extract the spiketrains by each channel, and assign each of these a unit_id (I am assuming at most one 'unit' per channel). I am a little stuck on how to link these spiketrains to the recordings. 

For example, if I want to use:
`st.postprocessing.get_unit_waveforms(recordings, sorting, ms_before=1, ms_after=2)`

Then I would think that the sorting object should have some attribute 'channel_ids' to know which recording channel to pull the waveforms from. However, it seems that the only think necessary for building a sorting object are two arrays, for the timestamps, and for the unit_ids. 

I am wondering what I need to add, to be able to run `get_unit_waveforms( )`. For example, should I use:
`set_unit_property(unit_ids, 'channel_ids', channel_ids)`

I can't figure out how they handle this in other sorting extractors. 

My sorting object currently looks something like below when printed... 
> unit_ids
> [ 1  2  3  4  5  6  7  8  9 10]
> spike_indexes
> [   812   2608   2861   3719   4900   5062   5388   5575   6418   7484
>    8207   9992  12209  15112  15706  16533  17435  17508  17850  21099
>   21407  24460  25028  26140  26850  26882  27180  27526  29174  30143
>   34677  37132  39569  40039  41176  41849  41998  43455  43933  44085
>   44389  47825  49483  51557  52088  53824  54346  54985  55880  56561
>   62242  63385  63622  63994  65198  69223  71343  72158  73611  77606
>   78189  81099  81670  82169  82342  82533  83289  83419  83721  84226
>   85528  91341  92214 100190 101696 101822 106568 106773 107013 107834
>  108885 108963 109649 110943 111988 112289 113718 115033 116184 116213
>  118819 119347 119899 120993 121854 122173 123675 124399 126162 127218
>  129536 129987 130467 132251 132611 134788 135547 136121 136779 138021
>  139073 140821 144269 150008 150631 152495 152691 152943 153729 153851
>  154128 155461 159224 159259 163465 164645 164924 167211 169220 171018
>  171173 171643 171767 172726 172990 173142 176693 177834 179768 179957
>  180308 181236 183641 185598 187117 188982 193769 194394 194758 197106
>  197328 199704 201615 203193 203278 204636 204985 208187 208581 208688
>  208846 210645 211688 215058 216044 216159 218114 218586 219213 219257
>  219572 220332 225000 225127 229581 230588 231174 231203 231835 233794
>  233998 234159 234303 235093 237431 239748 240746 244816 246015 246230
>  246717 251757 252416 254892 257437 259480 260847 261325 261425 261455
>  261577 261924 262372 264143 264723 265318 266451 267394 271511 272653
>  273359 274751 275017 276347 276691 277679 280604 282775 283236 283893
>  284211 284658 284721 286441 286916 287368 287492 290390 290515 291018
>  293876 294447 294773 295390 295827 297622 298587]
> spike_labels
> [ 8 10  8  5  6  8  8  3  6 10 10  6  3  3  3 10 10  7  5  6  7  5  4  1
>  10  5  2  8  8  6  9  4  5  8  9  4  8  4  2  5  2  6  2  7  3  9  5  4
>   6  4  4  4  8  4  2  3  7  7  5  6  9  5  9  5  9 10  4  4  8  2  5  7
>  10  8  3  3 10 10  6  2  2  6  3  2  3  7  7  1  5  1  4  2 10  4 10  5
>   5  1  5  1  9  2  9  1  8  7  7  7  6  5  4  3  2  3  3  3  2  8  3  2
>  10  4  1 10  1  1  1  5  9  2  9  1  4  6  6  8  4  9  9  3  8  7  3  6
>   8  8  1  2  1  9  9 10  5  5  8 10  5  8  8  5  5  8  7  4  1 10  5  5
>   7  4  4  5  3  3  9  4  5 10  9  1  3  1  1  3  8  1 10  6  8  6  9  7
>   2  6  6  3  6  9  1  4  6  9  3  2  2  7 10 10  4  6 10 10  2  2  2  1
>   9  7  3  4  4  8  6  4  8  9 10  7  7  8  2  1  3  9  2 10  7]
> sampling_frequency
> [30000.]

**Comment by mhhennig** [comment]
Yes, at the moment you would add the channel as a property, and then read that when looking for the relevant waveform. It is not straight forward to have a common method for relating channels and units as this may depend on the location of the spikes (e.g. HS2), or the template (KS2 etc.). We could think about adding convenience functions perhaps. How would you like to see this implemented/
