### ISSUE TITLE
Typo in quality_metrics.misc_metrics

### ISSUE THREAD

**Issue by cristofer-holobetz** [SpikeInterface/spikeinterface#518]
Line 247 in spikeinterface.toolkit.quality_metrics.misc_metrics.py currently reads:

`res = namedtuple('isi_violaion',`
but should probably read
`res = namedtuple('isi_violation',`

https://github.com/SpikeInterface/spikeinterface/blob/b6b2a54e66f2b5b985e4c0dafc6a0dec2b303813/spikeinterface/toolkit/qualitymetrics/misc_metrics.py#L247

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/519

**Comment by alejoe91** [comment]
Thanks for spotting it!
