### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by caniko** [SpikeInterface/spikeinterface#532]
Hello, I was having trouble determining the license of the package. Is it MIT or Apache? On `setup.py` it is Apache, and on the LICENSE file it is MIT

**Comment by caniko** [comment]
I just noticed that Apache license is also mentioned on the `README.md`.

**Comment by alejoe91** [comment]
> I just noticed that Apache license is also mentioned on the `README.md`.

It will automatically update at next release (taken from stup.py)
