### ISSUE TITLE
Getting stuck on the toy example of sorting

### ISSUE THREAD

**Issue by chengchichu** [SpikeInterface/spikeinterface#55]
I was running the mountainsort4 with python version3.6 with anaconda environment. When I went through the toy example provided on 

https://spikeinterface.readthedocs.io/en/latest/getting_started/plot_getting_started.html

I got stuck on the sorting step. It return the message
```

  File "/home/chang/anaconda3/envs/myenv1/lib/python3.6/site-packages/spikesorters/mountainsort4/mountainsort4.py", line 110, in _run
    verbose=self.verbose

TypeError: mountainsort4() got an unexpected keyword argument 'verbose'
```

and can't proceed 

Do you know how to solve this? I am a user of previous version ml3 and would like to use some new feature from spikeinterface to extract the spike waveform.

**Comment by samuelgarcia** [comment]
Could you check with the actual master ?

**Comment by alejoe91** [comment]
this is fixed eith later ms_m4alg releases
