### ISSUE TITLE
[contribution] Windows-compatible container for Spike Interface

### ISSUE THREAD

**Issue by vncntprvst** [SpikeInterface/spikeinterface#561]
I heard something similar is in the works, but just in case this is of interest to anyone in the meantime, I made a Jupyterlab container for Spike Interface with a few sorters pre-installed. It can run on any OS, but could make life easier for Windows users. 
The repo is here: https://github.com/vncntprvst/spikeinterface-dockerfiles. 
Any feedback welcome! 
Thanks

**Comment by alejoe91** [comment]
Thank you so much @vncntprvst 

Can you make  a PR with the Dockerfile here: https://github.com/SpikeInterface/spikeinterface-dockerfiles/pulls ?

So we can push it to our dockerhub too!

**Comment by vncntprvst** [comment]
Sure. I'll make a new branch on my side for the PR, to isolate the relevant commits.
