### ISSUE TITLE
Mismatch in sw.plot_timeseries

### ISSUE THREAD

**Issue by vincisLab** [SpikeInterface/spikeinterface#569]
Hi all,

when we use a multishank probe, we observe a mismatch between the probe mapping and the order in which the channels are plotted using sw.plot_timeseries when the boolean "order_channel_by_depth=True".
The Y axis of the plot does not have the channels organized based on their depth position. However, when we use a linear probe we dont have this issue.
Any suggestions?

**Comment by alejoe91** [comment]
Hi @vincisLab 

Could you send us the probeinterface json file so we can test? 

You can use the [`probeinterface.io.write_probeinterface()`](https://github.com/SpikeInterface/probeinterface/blob/main/probeinterface/io.py#L59) function.

**Comment by vincisLab** [comment]
Hi @alejoe91 

Here the json file.
Also I added two pdf files: one with the plot of the probe and the other with the plot_timeseries with order_channel_by_depth=True.

Thanks!


[extracellular_example.pdf](https://github.com/SpikeInterface/spikeinterface/files/8350468/extracellular_example.pdf)
[Probe.pdf](https://github.com/SpikeInterface/spikeinterface/files/8350469/Probe.pdf)
[prbFile.zip](https://github.com/SpikeInterface/spikeinterface/files/8350471/prbFile.zip)

**Comment by hpay** [comment]
I ran into a similar issue.  It's particularly apparent when plotting two recordings overlaid (e.g. filtered and filtered+CMR). Probe.json file is attached below.

When I run:
```
w = si.plot_timeseries({"filt": recording_f, "common": recording_cmr},
                        clim=(-1000, 1000), order_channel_by_depth=False,show_channel_ids=True, backend="ipywidgets")
```
I get (zoomed in to show that the spikes match before and after CMR): 
![order_false](https://user-images.githubusercontent.com/16298546/193160812-cb3c3bb5-ff21-4089-b398-4c22aaadbb50.png)


When I run:
```
w = si.plot_timeseries({"filt": recording_f, "common": recording_cmr},
                        clim=(-1000, 1000), order_channel_by_depth=True,show_channel_ids=True, backend="ipywidgets")
```
I get (notice the big spike at time 0.41 s is now on different channels in the two versions of the recording. And the channel numbers don't make sense to me):
![image](https://user-images.githubusercontent.com/16298546/193160944-6b3330f0-5749-4c21-b1b2-4a46e99a8aeb.png)

I'm only using a single shank probe actually, but the sites are arrayed in two columns, in case that matters.

Probe.json file:
[probe.zip](https://github.com/SpikeInterface/spikeinterface/files/9679660/probe.zip)

**Comment by alejoe91** [comment]
Thanks for the additional report! We'll check on this!

**Comment by alejoe91** [comment]
Should be fixed by this PR: https://github.com/SpikeInterface/spikeinterface/pull/1000

**Comment by hpay** [comment]
Awesome!!
