### ISSUE TITLE
Is there a way to sort by group using only one sorter?

### ISSUE THREAD

**Issue by mfvd** [SpikeInterface/spikeinterface#572]
Hello,

According to the documentation, it is possible to split by group and then use `run_sorters` to get a sorter object per group. However, if possible, I would like to a single object with data from all my groups (shanks)

In version 0.11.0 one could use `grouping_property='group'` to sort by group and to keep the data in a single sorter object. Is there a similar method with 0.93.0? 

Cheers

**Comment by alejoe91** [comment]
HI @mfvd 

Sure! Checkout the [run_sorter_by_property()](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sorters/launcher.py#L46) function! I think it's exactly what you need :)

**Comment by mfvd** [comment]
Hi @alejoe91 ,

Thanks! 
I completely missed that one when reading the docs. I'll give it a try!

Cheers

**Comment by alejoe91** [comment]
Ok that's a hidden one: after sorting by property if you want to export to phy and also keep the property grouping you have to set the sparsity correctly with the argument `sparsity_dict=dict(method="by_property", by_property="group")`

You can check the `export_to_phy` docs for more info ;)

**Comment by alejoe91** [comment]
It seems that the recording doesn't have the group property from the message...can you check?

**Comment by mfvd** [comment]
When I check with `rec_cashed.get_property_keys()`, the recording has a group property and the channels have assigned groups with `rec_cashed.get_channel_groups()`.

**Comment by alejoe91** [comment]
@mfvd what is the output of:

```
rec_by = rec_cashed.split_by("group")
print(rec_by.keys())
```

?

**Comment by mfvd** [comment]
Hi @alejoe91 

The output is:  `dict_keys([0, 1, 2])`.

**Comment by alejoe91** [comment]
what about `np.unique(waveforms_ms4.sorting.get_property("group"))`?

**Comment by mfvd** [comment]
I get the following: `['0' '1' '2']`

**Comment by alejoe91** [comment]
Ah I see! There seems to be a mismatch in the dtype: `groups` for recordings are `int` anf for sorting are `str`..I'll look into it!

**Comment by alejoe91** [comment]
@mfvd should be fixed with this PR: https://github.com/SpikeInterface/spikeinterface/pull/579

Can you try?

**Comment by mfvd** [comment]
Thanks @alejoe91 
Sorry, I'm quite new to github... how can I install this PR to test it?

**Comment by mfvd** [comment]
I managed to do it and it solved the issue! Thanks!
