### ISSUE TITLE
Problems with Recording extractor using SpikeInterface 

### ISSUE THREAD

**Issue by HazelPinto** [SpikeInterface/spikeinterface#573]
[Ens99.zip](https://github.com/SpikeInterface/spikeinterface/files/8351735/Ens99.zip)
The following file (nev) isn't even recognized as a nev file, I've tried with nsx files and it works (it extracts wrong the channels, but at leat it recognize it as a file)

**Comment by samuelgarcia** [comment]
I guess it is a blackrock file.
nev is file that contain spikes. it is not a "recording" so
nsx contain traces this one is a "recording".

If you want to open the nev files to extarct spiketrain we should use neo package directly.
