### ISSUE TITLE
MCS .h5 file format not supported anymore?

### ISSUE THREAD

**Issue by jonasort** [SpikeInterface/spikeinterface#590]
Hello, 

I have used a former version of Spikeinterface to extract from MCS .h5 files via MCSH5RecordingExtractor

This issue was raised before but is closed:
https://github.com/SpikeInterface/spikeinterface/issues/216

Is there any way this feature will be reimplemented? All of our other analysis use the .h5 format and exporting the files in two different formats appears suboptimal.

Thank you!

**Comment by samuelgarcia** [comment]
Hi thanks,
for opening this again.
reader where moved to neo module and spiekinetrace only wraper thoses reader.
During this refactoring MCSH5RecordingExtractor was leasily forgotten.

We can try to add this back but we run a bit out of time.
waiting for that could you try MCSRawRecordingExtractor and export your data in this format.
