### ISSUE TITLE
Parameter issue for sw.plot_isi_distribution

### ISSUE THREAD

**Issue by Yuhao-Zhang-SV** [SpikeInterface/spikeinterface#607]
Hi,

I'm using the latest version of Spikeinterface APIs. And when I called the API like this:
sw.plot_isi_distribution(sorting, unit_ids=units, bins=10, window=1)
There is a type error: __init__() got an unexpected keyword argument 'bins'.
<img width="819" alt="1650612729(1)" src="https://user-images.githubusercontent.com/78635669/164628330-83d0d1b5-732d-4795-914d-b5089cb02545.png">
<img width="557" alt="1650612756(1)" src="https://user-images.githubusercontent.com/78635669/164628404-b28f9331-6864-4955-977b-6bc083f1a157.png">

But I checked the API document and found that we actually have 'bins' as one of the input parameters. Why do we get this error? Thanks in advance~

**Comment by alejoe91** [comment]
Hi @Yuhao-Zhang-SV 

There is probably a mismatch here: you can check the actual arguments with in the `ISIDistributionWidget` init (see https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/widgets/isidistribution.py#L34-L35). The parameter is `bin_ms`! we''l change it in the docs. Thanks for reporting it
