### ISSUE TITLE
Q: is release coming?

### ISSUE THREAD

**Issue by yarikoptic** [SpikeInterface/spikeinterface#61]
ATM at 0.9.1-39-g6da0e53 with 0.9.1 released a good number of months back.  Just wanted to check if a new release being brewed to possibly chase fresh release of the spikextractors? ;)

**Comment by samuelgarcia** [comment]
I think @alejoe91 plan to do it or have done it already.

**Comment by alejoe91** [comment]
Waiting for TDC 1.6. do you think you can release today?

**Comment by samuelgarcia** [comment]
tdc 1.6 is not release yet but you can release spikesorter now.
it will works.
