### ISSUE TITLE
Klusta units are not unique! Using unique unit ids

### ISSUE THREAD

**Issue by jkb521** [SpikeInterface/spikeinterface#610]
I use the Klusta sorts , but when finished,
I got  "Klusta units are not unique! Using unique unit ids"., and  did not generate files such as spike_times.npy ......,
and thus cannot compute quality_metrics analyses 

I have four groups 16 channels.

**Comment by samuelgarcia** [comment]
@alejoe91 : can you help on this ?

**Comment by alejoe91** [comment]
Hi @jkb521 

Can you share the entire code and error? `"Klusta units are not unique! Using unique unit ids"` is just a warning and it renames the unit ids.. the problem should not be related. Note that spike times are not in the file list for klusta, which generates a `kwik` file.

**Comment by alejoe91** [comment]
This is not an error, but a warning that klusta units from different channel groups are renamed
