### ISSUE TITLE
spikeinterface did not apply preprocessing steps to exported .dat files for spikesorting  ,right?

### ISSUE THREAD

**Issue by jkb521** [SpikeInterface/spikeinterface#611]
When I did the spike sorting in spikeinterface, I found that it seems it only export the raw .dat file, but did not apply any my preprocessing steps, such as filt the data, apply common reference,  because the specitifc sorter would do those steps,  but I am not sure whether my findings are true.  Can someone tell me whether this is true? Thanks.

**Comment by alejoe91** [comment]
if you pass a preprocessed recording to the sorter, then all the processing steps are applied and the preprocessed data is saved as dat file

**Comment by samuelgarcia** [comment]
Note that this is true for sorter that need bin/dat file as input (Ks, klusta, spyking cicus, ...).
Some sorter (ms4, HS) do not need to cache (save) the preprocessed as a raw binary in the folder.
