### ISSUE TITLE
`CommonReferenceRecording` missing keyword for JSON

### ISSUE THREAD

**Issue by miketrumpis** [SpikeInterface/spikeinterface#633]
Hi, the CommonReferenceRecording preprocessor constructor is

https://github.com/SpikeInterface/spikeinterface/blob/5d218a25328c49e76d1e667f2909320b42709138/spikeinterface/toolkit/preprocessing/common_reference.py#L48-L49

and it is not fully reproducible from JSON without saving the "operator" argument.

https://github.com/SpikeInterface/spikeinterface/blob/5d218a25328c49e76d1e667f2909320b42709138/spikeinterface/toolkit/preprocessing/common_reference.py#L99-L100

I'll do a quick pr

**Comment by alejoe91** [comment]
Closed via https://github.com/SpikeInterface/spikeinterface/pull/634
