### ISSUE TITLE
Kilosort hidden parameters

### ISSUE THREAD

**Issue by maurotoro** [SpikeInterface/spikeinterface#652]
Dearest,

During my sorting adventures, I realized that kilosort has a parameter that controls the length of the waveform that is taken from the recording that is not mentioned on their StandardConfig.m files. From my experience, changing their default value of 60 to 30 improve tremendously my results, so I would like to be able to change it directly through spikeInterface. Currently, I have to make the pipeline with SI, and before it runs the sorter, I add a hack to add it on the resulting `kilosort_config.m`.

Can I make a pull request to have access to this `ops.nt0` parameter from SI, pretty please??

Many thanks for the library, and all the amazing work,

Suerte!

**Comment by alejoe91** [comment]
Hola @maurotoro 

Of course! Can you make a PR to expose the parameter? As you might have seen,we are currently refactoring the KS implementations, so please make it as soon as you can so we can propagate the changes ;)

Cheers
Alessio

**Comment by alejoe91** [comment]
Fixed via https://github.com/SpikeInterface/spikeinterface/pull/655
