### ISSUE TITLE
test class inheritance 

### ISSUE THREAD

**Issue by bendichter** [SpikeInterface/spikeinterface#659]
https://github.com/SpikeInterface/spikeinterface/blob/ae679aff788a6dd4d8e7783e1f72ec7e550c1bf9/spikeinterface/extractors/tests/common_tests.py#L10

@samuelgarcia Why not have this class inherit from `unittest.TestCase`? Then you can avoid multiple inheritance in descendant classes.

**Comment by samuelgarcia** [comment]
I don't remember.
I think because after we use plain function in pytest mode.
I did this 14 month ago.
