### ISSUE TITLE
Sortingextractor missing for Blackrock

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#753]
This was available in `spikeextractors`:

https://github.com/SpikeInterface/spikeextractors/blob/48a86a048a4e6c5b9d669fd4f3bbf58caa97583a/spikeextractors/extractors/neoextractors/blackrockextractor.py#L40-L62

Is there any reason that this is missing here or is there something that is yet to be implemented?

**Comment by alejoe91** [comment]
@h-mayorquin can you give it a shot based on the `NeoBaseSortingExtractor`?

**Comment by h-mayorquin** [comment]
I will add this to my to-do list.
