### ISSUE TITLE
Documentation claims that `CellExplorerSortingExtractor` is supported but it is not

### ISSUE THREAD

**Issue by h-mayorquin** [SpikeInterface/spikeinterface#757]
https://spikeinterface.readthedocs.io/en/latest/supported_formats_and_sorters.html

The link above claims that ``CellExplorerSortingExtractor` is supported but I can't find it on the code base.

**Comment by alejoe91** [comment]
We should either 1) port the probably out-of-date extractor or 2) remove the claim from the docs. I vote for 2) for now

**Comment by samuelgarcia** [comment]
Also vote for 2

**Comment by alejoe91** [comment]
@h-mayorquin could you make a small PR removing it from the list? :)

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/1158
