### ISSUE TITLE
get_noise_levels with return_scaled

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#763]
Just a quick question. Why is it not possible to use the get_noise_levels without sometimes explicitly stating return_scaled=False. What kind of recordings are triggering such an error. Can it be such that by default, the function does not need any argument to work?

**Comment by samuelgarcia** [comment]
Salut Pierre.
Some recording do not have scaling because they do not have gain/offset properties.
For instance they are already scaled because store in float32 in that case return_scaled=False is already scaled and so return_scaled=True do not make sens.

**Comment by yger** [comment]
Ok, I got the spirit, but why not considering then that the gain is 1? Because this is strange that for the tests of the sorters, one need to specify such a flag to avoid crashes

**Comment by alejoe91** [comment]
You can check if a recording has scaled traces: `recording.has_scaled_traces()`
