### ISSUE TITLE
typo in spikeinterface/spikeinterface/core/channelslicerecording.py ?

### ISSUE THREAD

**Issue by maxjuv** [SpikeInterface/spikeinterface#775]
Hello there !

I got some issues when I set a probe to my multi-recording (multirecording = si.concatenate_recordings(recording_list)). I got an assertion error from  line31  spikeinterface/spikeinterface/core/channelslicerecording.py
By inspecting the code below, I guess '==' should rather  be "!="
assert self._channel_ids.size == np.unique(self._channel_ids).size, 'ChannelSliceRecording : channel_ids not unique'

Best
 Maxime

**Comment by samuelgarcia** [comment]
Salut Maxime.
No this is correct, we are checking that the size is identique the size of "unqiue" and so detect redundant channel ids which is not allowed by spikeinterface.
