### ISSUE TITLE
autoRecordingExtractor a local kach db error examples/modules/widgets/plot_3_recsort_gallery.py

### ISSUE THREAD

**Issue by nahawtho** [SpikeInterface/spikeinterface#80]
Hi all. I was wondering if you are aware of a potential bug on plot_unit_waveforms() and perhaps other fcns when loading from an autosorting extractor using a kachery pointer. I created my own kachery pointers to my recording and sorting, and that's when I run into this problem. The toy example in examples/modules/widgets/plot_3_recsort_gallery.py works fine for me. This problem only occurs in functions in plot_3_recsort_gallery.py but the galleries 1 and 2 work fine from the sorting and recording loaded by the auto sorting extractor. 

input snippet:
```
from spikeforest2_utils import AutoRecordingExtractor, AutoSortingExtractor
import kachery as ka
import spikeinterface.widgets as sw
import pickle

universal_sorting_path = ka.store_file(sorting_out_short)

recording = AutoRecordingExtractor(recording_path, download=False)
sorting_true = AutoSortingExtractor(universal_sorting_path)

print(recording.get_channel_locations())
print(sorting_true.get_unit_ids())

with open('plot_objs.pkl', 'wb') as output:
    #WORKS FINE:   
    w_ts = sw.plot_timeseries(recording)
    pickle.dump(w_ts, output, pickle.HIGHEST_PROTOCOL)
       
    #WORKS FINE:
    w_rs = sw.plot_rasters(sorting_true, sampling_frequency=fs)
    pickle.dump(w_rs, output, pickle.HIGHEST_PROTOCOL)

    #DOES NOT WORK:
    w_wf = sw.plot_unit_waveforms(recording, sorting_true, max_spikes_per_unit=100)
    pickle.dump(w_wf, output, pickle.HIGHEST_PROTOCOL)
    
    
```
output
`  File "/usr/local/lib/python3.8/dist-packages/spikewidgets/widgets/unitwaveformswidget/unitwaveformswidget.py", line 221, in _do_plot
    random_wf = st.postprocessing.get_unit_waveforms(recording=self._recording, sorting=self._sorting,
  File "/usr/local/lib/python3.8/dist-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 131, in get_unit_waveforms
    if not recording.check_if_dumpable():
  File "/usr/local/lib/python3.8/dist-packages/spikeextractors/baseextractor.py", line 310, in check_if_dumpable
    return _check_if_dumpable(self.make_serialized_dict())
  File "/usr/local/lib/python3.8/dist-packages/spikeextractors/baseextractor.py", line 59, in make_serialized_dict
    'key_properties': self._key_properties, 'version': imported_module.__version__,
AttributeError: module 'spikeforest2_utils' has no attribute '__version__'`

**Comment by alejoe91** [comment]
Hi @nahawtho 

The spikeforest AutoExtractors are compatible with parts of SI at the moment. The error you are seeing is because SI tries to dump objects to dictionaries (e.g. for passing them to other processes), but this requires the module.to have a version (as spikeextractors and spiketoolkit objects). The fix here is relatively easy: we just need to add the `__verison__` to spikeforest!
