### ISSUE TITLE
Resample recording

### ISSUE THREAD

**Issue by mfvd** [SpikeInterface/spikeinterface#807]
Is there a way to resample a recording in the latest API? 
Previously ```st.preprocessing.resample``` would do the job but is no longer available.

Cheers

**Comment by alejoe91** [comment]
We are still finailzing this: https://github.com/SpikeInterface/spikeinterface/pull/632

there are a few issues with resampling that need to be considered, but I think we can finalize and merge it next week!

**Comment by alejoe91** [comment]
Enjoy FENS! If you are ok I can take your files and your commits and make a clean PR ;)

**Comment by maurotoro** [comment]
Absolutely! All for the greater good!

Suerte!
