### ISSUE TITLE
mismatch between phy and si unit ids

### ISSUE THREAD

**Issue by AlanoudAlsubhi** [SpikeInterface/spikeinterface#814]
Hi, 

I saw the fix for the mismatch between phy and si unit ids. I tried the solution but the problem still exists in my end. 
Any suggestion of what I should try? 

Thanks, 
Alanoud

**Comment by alejoe91** [comment]
Hi @AlanoudAlsubhi 

Phy internally uses sequential IDs from 0 to N-1. Since spikeinterface IDs could be different, we save an additional property called `si_unit_id` that should show as an additional column in the phy unit list. 

These `si_unit_ids` are then loaded back in spikeinterface if you load a curated phy output.

**Comment by alejoe91** [comment]
@AlanoudAlsubhi is it clearer now?

**Comment by AlanoudAlsubhi** [comment]
Yeah but now I'm running into another thing that is confusing me. It might be related to this, not sure. 

I'm using the `spikeinterface.postprocessing.get_template_extremum_channel(waveform_extractor, peak_sign: str = 'neg', mode: str = 'extremum', outputs: str = 'id')`

Some of the extremum channels are not consistent pre and post-curation. In this case it is just the first one.
Pre curation it is (0:0), post curation it is (0:11).  Any ideas? 

![image](https://user-images.githubusercontent.com/79871345/183684603-6075e33e-a7a6-4381-becc-b0032e1c87f4.png)

![image](https://user-images.githubusercontent.com/79871345/183684762-955908bd-f587-4ba7-a087-7fe6c324b261.png)

Thanks

**Comment by alejoe91** [comment]
Did you do some merges or just removed noisy units?

**Comment by AlanoudAlsubhi** [comment]
I just removed noisy units

**Comment by alejoe91** [comment]
Ok, it seems that the mismatch is only for unit `0`, right? 

I think this is happening: 
Unit 0 probably have waveforms which are almost as large on two channels (0 and 11). When you extract waveforms, you subsample them (by default 500), so it is possible that different subsampling make the peak channel fall in one of the two channels. 

Can you try to re-extract waveforms adding the `max_spikes_per_unit=None`? This forces the waveform extraction on all waveforms, so the extremum channels should correspond. 

Let me know! 

PS: you can also try to plot the templates!

**Comment by AlanoudAlsubhi** [comment]
Thanks for the suggestions! Unfortunately, nothing changed. 
But there is something interesting from plotting the templates Pre and Post. There seems to be something wrong with unit 0 post curation, `sorting_SC_phy_curated = spikeinterface.extractors.read_phy('phy_SC/', exclude_cluster_groups=['noise'])`. 
![image](https://user-images.githubusercontent.com/79871345/183708087-ff399897-adcb-4e58-9ad7-39adb152797c.png)
![image](https://user-images.githubusercontent.com/79871345/183708134-c95b4bd1-df11-49fe-9c8e-84915c163d07.png)

**Comment by alejoe91** [comment]
Yes indeed it looks wrong..can you try to compare the spike trains? If you share the phy folder I'll take a look

**Comment by AlanoudAlsubhi** [comment]
[https://drive.google.com/drive/folders/1gQgiNWabO1npZYje4LfG7wkUrTG33K8T?usp=sharing](url)

**Comment by alejoe91** [comment]
@AlanoudAlsubhi thanks for the data and thanks for spotting this! Indeed there was a bug!

It is fixed in this PR: https://github.com/SpikeInterface/spikeinterface/pull/876

Can you try to install from there?

**Comment by AlanoudAlsubhi** [comment]
This actually fixed the issue. 
Thank you!
