### ISSUE TITLE
Why are channel groups only int?

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface#819]
See https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/baserecording.py#L493

Especially when setting with `shank_ids`, I think we should enable at least str, since shank ids could have a name

@samuelgarcia

**Comment by samuelgarcia** [comment]
Yep we can also put str.
I am OK with this.
We could have something more explicit like 'probeXshankY' as group key in case of complex montage.
