### ISSUE TITLE
Option to change datatype for whitening

### ISSUE THREAD

**Issue by lfrank** [SpikeInterface/spikeinterface#864]
We store recording traces as int16 to save space and then whiten within mountainsort4 for sorting.

We also use whitened recordings for the metrics, and currently the whitened extractor is stored as int16 as well, which loses quite a lot of resolution as a result of the normalization that occurs during whitening.

It would be very helpful to have a dtype argument for whitening so we could stored the whitened waveforms as float16 instead.

**Comment by khl02007** [comment]
Hi @lfrank, I learned that (1) we can specify the dtype when we call `save` on the whitened recording and (2) we can also specify the dtype of the waveforms when we call `extract_waveforms`. I will make these changes to our pipeline.
