### ISSUE TITLE
Error using pykilosort to sort concatenated recordings 

### ISSUE THREAD

**Issue by kortdriessen** [SpikeInterface/spikeinterface#877]
I am trying to sort some multichannel data using spikeinterface and pykilosort, and am getting an error that may be a bug. The process that caused it is the following:
1. I wrote each channel of the probe to a binary file, and loaded each of those files using `read_binary`. I get a `BinaryRecordingExtractor` with 16 channels and 16 corresponding segments.
2. I give that `BinaryRecordingExtractor` to `concatenate_recordings` and get a `ConcatenateSegmentRecording` object.
3. I use `set_probe` to set the probe on that object. 
4. I then pass that to `run_sorter('pykilosort')`.

A very similar process to that found in the docs [here](https://spikeinterface.readthedocs.io/en/latest/modules/sorters/plot_4_sorting_concatenated_recordings.html?highlight=multirecording.set_probe#run-spike-sorting-on-concatenated-recordings). 

The sorting fails, apparently on the line `assert isinstance(recording, BinaryRecordingExtractor)`

Should I be doing something to convert back to a `BinaryRecordingExtractor` before running the sorting? Or, is there something I can do in step one to get a `BinaryRecordingExtractor` with 16 channels but only one segment?

**Comment by TomBugnon** [comment]
Thanks a lot for the quick fix, we'll give it a shot within a week or two
