### ISSUE TITLE
Ironclust error

### ISSUE THREAD

**Issue by crewl2** [SpikeInterface/spikeinterface#92]
I ran into a strange error. I have been able to run spikeinterface and Ironclust on Windows since I installed it. However, out of nowhere I started receiving this error. I'm not sure how or why this happened as I left it overnight and came back to rerun it with different data and got this error. I appreciate any help you can give me. Thank you.

# run spike sorting by group
sorting_IC = ss.run_ironclust(recording_cache, 
                              output_folder='results_split_ic', 
                              grouping_property='group', parallel=True, verbose=True)
print(f'IronClust found {len(sorting_IC.get_unit_ids())} units')

TypeError                                 Traceback (most recent call last)
<ipython-input-12-7f7cb2cdc43d> in <module>
      1 # run spike sorting by group
----> 2 sorting_IC = ss.run_ironclust(recording_cache, 
      3                               output_folder='results_split_ic',
      4                               grouping_property='group', parallel=True, verbose=True)
      5 print(f'IronClust found {len(sorting_IC.get_unit_ids())} units')

~\spikesorters\sorterlist.py in run_ironclust(*args, **kwargs)
    377         The spike sorted data
    378     """
--> 379     return run_sorter('ironclust', *args, **kwargs)
    380 
    381 

~\spikesorters\sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, verbose, raise_error, n_jobs, joblib_backend, **params)
     91                          verbose=verbose, delete_output_folder=delete_output_folder)
     92     sorter.set_params(**params)
---> 93     sorter.run(raise_error=raise_error, parallel=parallel, n_jobs=n_jobs, joblib_backend=joblib_backend)
     94     sortingextractor = sorter.get_result()
     95 

~\spikesorters\basesorter.py in run(self, raise_error, parallel, n_jobs, joblib_backend)
    128     def run(self, raise_error=True, parallel=False, n_jobs=-1, joblib_backend='loky'):
    129         for i, recording in enumerate(self.recording_list):
--> 130             self._setup_recording(recording, self.output_folders[i])
    131 
    132         # dump again params because some sorter do a folder reset (tdc)

~\spikesorters\ironclust\ironclust.py in _setup_recording(self, recording, output_folder)
    159         dataset_dir = output_folder / 'ironclust_dataset'
    160         # Generate three files in the dataset directory: raw.mda, geom.csv, params.json
--> 161         se.MdaRecordingExtractor.write_recording(recording=recording, save_path=str(dataset_dir),
    162                                                  n_jobs=p["n_jobs_bin"], chunk_mb=p["chunk_mb"], verbose=self.verbose)
    163 

TypeError: write_recording() got an unexpected keyword argument 'n_jobs'

**Comment by alejoe91** [comment]
Fixed in new release
