### ISSUE TITLE
EDF EXTRACTOR 

### ISSUE THREAD

**Issue by olesnits** [SpikeInterface/spikeinterface#930]
Hi,

I have used Edf Extractor with many files (MEA recordings), but always I have the same prolem - metadata of the file is not properly read (wrong time in seconds, wrong sampling frequency.) I guess the problem how it reads header. Hope you can fix it!

**Comment by olesnits** [comment]
I have checked the same files with H5 extractor, and metadata was read correctly.

**Comment by alejoe91** [comment]
@h-mayorquin can you take a look at this? :)

**Comment by h-mayorquin** [comment]
@olesnits Do you think you could share your data with us?

**Comment by olesnits** [comment]
hello! sorry, i can't. data is private from patient's. I can share with you notebook, where i open file with edf extractor and h5 extractor to see comparison in meta-data. or i can be avalaible for call to open data with you. let me know
