### ISSUE TITLE
AttributeError: module 'spikeinterface.extractors' has no attribute 'SubRecordingExtractor'

### ISSUE THREAD

**Issue by olesnits** [SpikeInterface/spikeinterface#935]

**Comment by alejoe91** [comment]
Hi @olesnits 

You should follow the documentation for the new API (version>=0.90).

The `SubRecordingExtractor` has been superseeded by 2 functions:

* `recording.channel_slice(channel_ids)`: select a subset of channels
* `recording.frame_slice(start_frame, end_frame)`: cut the recording in time
