### ISSUE TITLE
Bug in plot_spikes_on_traces()

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#949]
I was trying this function, sounds pretty cool, but with the ipywidgets backend this leads to a crash quite quickly after playing with the control bars (scrolling in time)

     71 waveform_idxs = spike_frames_to_plot[:, None] + np.arange(-we.nbefore, we.nafter) - frame_range[0]
---> 73 times = dp.timeseries["times"][waveform_idxs]
     74 # discontinuity

IndexError: index 32000 is out of bounds for axis 0 with size 32000

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/pull/989
