### ISSUE TITLE
Error in recording.py if chunk_size is greater than number of frames in recording

### ISSUE THREAD

**Issue by jtyoung84** [SpikeInterface/spikeinterface#957]
Getting an error in `spikeinterace/core/recording.py` setting up a unit test for a small recording because the number of frames is less than the chunk size. In lines 36-38:

```
        length = recording.get_num_frames(segment_index)
        random_starts = np.random.RandomState(seed=seed).randint(0,
                                                                 length - chunk_size, size=num_chunks_per_segment)
```
if `length <=chunk_size`, then an error is thrown.

**Comment by alejoe91** [comment]
Thanks for the report @jtyoung84 

I wonder whether throwing an error is the correct behavior here. If you ask a chunk size of 1000 but only have 900 samples, then it's not possible to get the requested chunk size. What do you think?

**Comment by jtyoung84** [comment]
I think raising a custom error message might suffice. Maybe add a quick check if `length <= chunk_size`, then let the user know to set the chunk_size on their end?

**Comment by alejoe91** [comment]
> I think raising a custom error message might suffice. Maybe add a quick check if `length <= chunk_size`, then let the user know to set the chunk_size on their end?

Sounds good!
