### ISSUE TITLE
How to get data for clustering after run_sorter?

### ISSUE THREAD

**Issue by gwq123456** [SpikeInterface/spikeinterface#958]
Hello, When I execute run_sorter, how can I call the method to get the data after sorter for clustering operation?
Is there a relevant reference example？

Thank-you for your time,
gwq

**Comment by alejoe91** [comment]
Hi @gwq123456 

What kind of cllustering operation are you referring to? You can get the spike trains wiht:

```
st = sorting.get_unit_spike_train(unit_id=unit)
```
