### ISSUE TITLE
Bug with memory mode of WaveformExtractor

### ISSUE THREAD

**Issue by yger** [SpikeInterface/spikeinterface#970]
The memory mode of the waveform extractor sounds cool, but it looks like some features are not properly handled. For example if such a memory object is created, the computations of metrics is crashing, because expecting a folder. Not sure I'm using it properly, but still pasting the issue

File ~/github/spikeinterface/spikeinterface/qualitymetrics/quality_metric_calculator.py:175, in compute_quality_metrics(waveform_extractor, load_if_exists, metric_names, sparsity, skip_pc_metrics, n_jobs, verbose, progress_bar, **params)
    143 """Compute quality metrics on waveform extractor.
    144 
    145 Parameters
   (...)
    171     Data frame with the computed metrics
    172 """
    174 folder = waveform_extractor.folder
--> 175 ext_folder = folder / QualityMetricCalculator.extension_name
    176 if load_if_exists and ext_folder.is_dir():
    177     qmc = QualityMetricCalculator.load_from_folder(folder)

TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'

**Comment by alejoe91** [comment]
@yger now it's supported https://github.com/SpikeInterface/spikeinterface/pull/981
