### ISSUE TITLE
Avoid segmentation error during kilosort2 cluster splitting

### ISSUE THREAD

**Issue by TomBugnon** [SpikeInterface/spikeinterface#987]
Hi
We have been experiencing [segmentation errors](https://github.com/MouseLand/Kilosort/issues/199) during cluster splitting with kilosort2.5 
We resolved this [by installing a different version of the mkl library](https://github.com/MouseLand/Kilosort/issues/199#issuecomment-754971599) and, in our fork, [setting the corresponding (system specific) paths as environment variables in kilosort_master.m](https://github.com/CSC-UW/spikeinterface/commit/1aae5e902c12e0560b54c1dc74fc43c238a3248e) as follows:

```
setenv('BLAS_VERSION', '/usr/lib/x86_64-linux-gnu/mkl/libblas.so');
setenv('LAPACK_VERSION', '/usr/lib/x86_64-linux-gnu/mkl/liblapack.so');
```

Allowing this in df spikeinterface is pretty much the last step we need before we can get rid of our fork
Do you think that would be possible? Do you have a preference about how to do this? We could for instance add the paths to BLAS and LAPACK as kilosort parameters.

We'll be happy to submit a PR implementing whichever approach seems preferable.
Best
Tom

**Comment by alejoe91** [comment]
Fixed by https://github.com/SpikeInterface/spikeinterface/pull/893
