### ISSUE TITLE
All the other sorter failed except of tridesclous

### ISSUE THREAD

**Issue by betty6you** [SpikeInterface/spikeinterface#994]
Hi 

I am using SpikeInterface to perform spike sorting on my binary file extracted from EDF.

But only "tridesclous" worked so far, the other sorters all failed. 

Here is a copy of my code and output. https://github.com/betty6you/EDFRecordingExtractor/blob/main/EDF_extractor_test_1.ipynb

What will be the reason and how to solve it?

Many thanks!
Jing

**Comment by alejoe91** [comment]
HI @betty6you 

Looking at the notebook it seems that tridesclous only found 1 good unit..Is it possible that the recording doesn't have any clearly isolated unit? This could explain the spike sorters failure!

**Comment by betty6you** [comment]
Thanks for your explanation.
I will try another file today.


Sent from my iPhone

On Oct 13, 2022, at 6:16 AM, Alessio Buccino ***@***.***> wrote:

﻿

HI @betty6you<https://github.com/betty6you>

Looking at the notebook it seems that tridesclous only found 1 good unit..Is it possible that the recording doesn't have any clearly isolated unit? This could explain the spike sorters failure!
